### ISSUE TITLE
502 response code and unhandled error when dns-service authentication fails

### ISSUE THREAD

**Issue by MatApple** [opstrace/opstrace#10]
When running the destroy operation with auth tokens generated yesterday:
```
2020-11-27T16:21:09.528Z info: Try to delete policy matdev-eks-linked-service
2020-11-27T16:21:09.529Z info: Try to delete policy matdev-cortex-s3
2020-11-27T16:21:09.531Z info: Try to delete policy matdev-loki-s3
2020-11-27T16:21:09.532Z info: Try to delete policy matdev-externaldns
2020-11-27T16:21:10.306Z info: All policy-role attachments detached
2020-11-27T16:21:36.913Z error: error during cluster teardown (attempt 1):
Error: Request failed with status code 502
    at createError (/snapshot/opstrace/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/opstrace/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/snapshot/opstrace/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function (anonymous)]
}
2020-11-27T16:21:36.913Z error: JSON representation of err: {
  "message": "Request failed with status code 502",
  "name": "Error",
  "stack": "Error: Request failed with status code 502\n    at createError (/snapshot/opstrace/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/snapshot/opstrace/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/snapshot/opstrace/node_modules/axios/lib/adapters/http.js:236:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:485:12)\n    at endReadableNT (_stream_readable.js:1224:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "config": {
    "url": "https://dns-api.opstrace.net/dns/",
    "method": "delete",
    "data": "{\"clustername\":\"matdev\"}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "authorization": "Bearer eyJh<snip>A",
      "x-opstrace-id-token": "eyJhbG<snip>k8eAw",
      "Content-Type": "application/json",
      "User-Agent": "axios/0.19.2",
      "Content-Length": 24
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1
  }
}
2020-11-27T16:21:36.915Z info: start attempt 2 in 30 s
```

After deleting the tokens with `rm id.jwt access.jwt` it prompted a new login in the CLI and succeeded. Would be nice to handle this auth failure automatically by deleting the local tokens and prompt for login.

**Comment by jgehrcke** [comment]
That problem still exists:
```
2020-12-17T12:05:23.287Z info: Removing DNS records
2020-12-17T12:05:53.957Z error: error during cluster teardown (attempt 5):
Error: Request failed with status code 502
    at createError (/snapshot/build/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/build/node_modules/axios/lib/core/settle.js:17:12)
```

which service generates the 502 response?
