### ISSUE TITLE
ci-instability: waiting for selector "[data-test='tenant/deleteBtn/${tenantName}']" failed

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1003]
**Describe the bug**

Looks like #1002 broke the upgrade tests?

```
[2021-07-07T05:41:36Z]   1) tests/zfUDg_tenant.spec.ts:56:3 › [Chromium] after auth0 authentication user can delete a Tenant 
[2021-07-07T05:41:36Z]
[2021-07-07T05:41:36Z]     Timeout of 120000ms exceeded.
[2021-07-07T05:41:36Z]
[2021-07-07T05:41:36Z]     Pending operations:
[2021-07-07T05:41:36Z]       - page.click at tests/zfUDg_tenant.spec.ts:71:16
[2021-07-07T05:41:36Z]
[2021-07-07T05:41:36Z]     page.click: Protocol error (Runtime.callFunctionOn): Target closed.
[2021-07-07T05:41:36Z]     =========================== logs ===========================
[2021-07-07T05:41:36Z]     waiting for selector "[data-test='tenant/deleteBtn/treetops8306']"
[2021-07-07T05:41:36Z]     ============================================================
[2021-07-07T05:41:36Z]     Note: use DEBUG=pw:api environment variable to capture Playwright logs.
[2021-07-07T05:41:36Z]
[2021-07-07T05:41:36Z]       69 |
[2021-07-07T05:41:36Z]       70 |     // first, ensure clicking "no" doesn't delete the tenant
[2021-07-07T05:41:36Z]     > 71 |     await page.click(`[data-test='tenant/deleteBtn/${tenantName}']`);
[2021-07-07T05:41:36Z]          |                ^
[2021-07-07T05:41:36Z]       72 |     await page.click("[data-test='pickerService/option/no']");
[2021-07-07T05:41:36Z]       73 |     expect(
[2021-07-07T05:41:36Z]       74 |       await page.isVisible(`[data-test='tenant/row/${tenantName}']`)
```

https://buildkite.com/opstrace/upgrade-tests/builds/941#0527ad35-2585-468c-8bf7-81e2fb9b0fde/3223-3240
https://buildkite.com/opstrace/upgrade-tests/builds/942#b973a4d1-b275-408a-bc98-7eb9d4e7a1e0/3370-3387

**Comment by terrcin** [comment]
Now that the upgrade tests have run a few more times I can see that this failure is not occuring all the time, and not always on the same test.

I have lined up two PRs to aid with debugging:

https://github.com/opstrace/opstrace/pull/1008
https://github.com/opstrace/opstrace/pull/1010

**Comment by terrcin** [comment]
Update:

#1010 has been merged just now

I've disabled the change from #1008 as the amount of output was v.frustrating and I wasn't really using it. Can enable in future on a case by case basis.

There has also been other PRs merged yesterday and today that may help with this, I'll wait and see what effect this has before plotting next steps.

**Comment by terrcin** [comment]
latest failure is now not in the browser testing, where all my focus has been:

```
[2021-07-13T01:42:06Z] [0m  1) test_ui_api
[2021-07-13T01:42:06Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-13T01:42:06Z] [0m[31m     page.waitForSelector: Timeout 30000ms exceeded.
[2021-07-13T01:42:06Z] =========================== logs ===========================
[2021-07-13T01:42:06Z] waiting for selector "text=Don't remember your password?" to be visible
[2021-07-13T01:42:06Z] ============================================================
[2021-07-13T01:42:06Z] Note: use DEBUG=pw:api environment variable to capture Playwright logs.[0m[90m
[2021-07-13T01:42:06Z]   Error: 
[2021-07-13T01:42:06Z]       at Object.captureStackTrace (/build/node_modules/playwright/lib/utils/stackTrace.js:51:19)
[2021-07-13T01:42:06Z]       at Connection.sendMessageToServer (/build/node_modules/playwright/lib/client/connection.js:73:48)
[2021-07-13T01:42:06Z]       at Proxy.<anonymous> (/build/node_modules/playwright/lib/client/channelOwner.js:64:61)
[2021-07-13T01:42:06Z]       at /build/node_modules/playwright/lib/client/frame.js:193:42
[2021-07-13T01:42:06Z]       at Frame._wrapApiCall (/build/node_modules/playwright/lib/client/channelOwner.js:77:34)
[2021-07-13T01:42:06Z]       at Frame.waitForSelector (/build/node_modules/playwright/lib/client/frame.js:188:21)
[2021-07-13T01:42:06Z]       at /build/node_modules/playwright/lib/client/page.js:212:60
[2021-07-13T01:42:06Z]       at Page._attributeToPage (/build/node_modules/playwright/lib/client/page.js:202:20)
[2021-07-13T01:42:06Z]       at Page.waitForSelector (/build/node_modules/playwright/lib/client/page.js:212:21)
[2021-07-13T01:42:06Z]       at performLoginFlow (test_ui.ts:120:14)
[2021-07-13T01:42:06Z]       at runNextTicks (node:internal/process/task_queues:61:5)
[2021-07-13T01:42:06Z]       at processImmediate (node:internal/timers:437:9)
[2021-07-13T01:42:06Z]       at Context.<anonymous> (test_ui.ts:217:5)
[2021-07-13T01:42:06Z] [0m
```

https://buildkite.com/opstrace/upgrade-tests/builds/980#cbe23f30-668a-4588-9116-2a9ad5a5bc66

**Comment by terrcin** [comment]
For that above `test_ui_api` error I've doubled the timeout with this pr to see what effect that had: https://github.com/opstrace/opstrace/pull/1039

It does seem to be getting past that to a new error now, that looks to a legit error:

```
[2021-07-13T21:38:18Z] [0m  1) test_ui_api
[2021-07-13T21:38:18Z]        create_tenant_and_use_custom_authn_token:
[2021-07-13T21:38:18Z] [0m[31m     Error: env var TENANT_RND_NAME_FOR_TESTING_ADD_TENANT is not defined but required[0m[90m
[2021-07-13T21:38:18Z]       at Context.<anonymous> (test_ui_api.ts:353:13)
[2021-07-13T21:38:18Z]       at processImmediate (node:internal/timers:464:21)
[2021-07-13T21:38:18Z] [0m
```

**Comment by terrcin** [comment]
The last four AWS failures have been due to the above error. It looks like a recent change to the tests started using `TENANT_RND_NAME_FOR_TESTING_ADD_TENANT` which isn't being setup for the upgrade tests.

**Comment by terrcin** [comment]
@sreis I've got this change in a branch which is a guess at fixing this problem: https://github.com/opstrace/opstrace/commit/ca8cf8e95167b315afc9afb8d746169808a88596

I'm not sure on how to run the upgrade tests against a branch/pr so would be good to get some help from you here.

Also just looking at the `ci/test-upgrade/run.sh` file compared to `ci/deploy-testremote-teardown.sh`, would it make sense to pull out the common parts around setting up and running the tests into a seperate file. They both do it differently with the upgrades not keeping an artifacts, for example.

**Comment by terrcin** [comment]
Closing this issue now and the original problem now isn't occuring after my changes were merged. Can reopen if it comes up again.

**Comment by sreis** [comment]
@terrcin Reopening since it just occurred in the upgrades pipeline. 

```
[2021-07-19T17:50:50Z]   1) test_ui_api
[2021-07-19T17:50:50Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-19T17:50:50Z]      page.waitForSelector: Timeout 60000ms exceeded.
[2021-07-19T17:50:50Z] =========================== logs ===========================
[2021-07-19T17:50:50Z] waiting for selector "text=Getting Started" to be visible
[2021-07-19T17:50:50Z] ============================================================
[2021-07-19T17:50:50Z] Note: use DEBUG=pw:api environment variable to capture Playwright logs.
[2021-07-19T17:50:50Z]   Error: 
[2021-07-19T17:50:50Z]       at Object.captureStackTrace (/build/node_modules/playwright/lib/utils/stackTrace.js:51:19)
[2021-07-19T17:50:50Z]       at Connection.sendMessageToServer (/build/node_modules/playwright/lib/client/connection.js:73:48)
[2021-07-19T17:50:50Z]       at Proxy.<anonymous> (/build/node_modules/playwright/lib/client/channelOwner.js:64:61)
[2021-07-19T17:50:50Z]       at /build/node_modules/playwright/lib/client/frame.js:193:42
[2021-07-19T17:50:50Z]       at Frame._wrapApiCall (/build/node_modules/playwright/lib/client/channelOwner.js:77:34)
[2021-07-19T17:50:50Z]       at Frame.waitForSelector (/build/node_modules/playwright/lib/client/frame.js:188:21)
[2021-07-19T17:50:50Z]       at /build/node_modules/playwright/lib/client/page.js:212:60
[2021-07-19T17:50:50Z]       at Page._attributeToPage (/build/node_modules/playwright/lib/client/page.js:202:20)
[2021-07-19T17:50:50Z]       at Page.waitForSelector (/build/node_modules/playwright/lib/client/page.js:212:21)
[2021-07-19T17:50:50Z]       at performLoginFlow (test_ui_api.ts:138:14)
[2021-07-19T17:50:50Z]       at Context.<anonymous> (test_ui_api.ts:222:5)
```

https://buildkite.com/opstrace/upgrade-tests/builds/1037#6715bc07-89e5-45d6-aad3-31a55c807107/8111-8286

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/prs/builds/5218#7a0149d7-fd8c-482a-af56-029846774c10/2488-2809

```
[2021-07-27T23:17:41Z]   1) test_ui_api
--
  | [2021-07-27T23:17:41Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
  | [2021-07-27T23:17:41Z]      Error: Login did not succeed within 300 s
  | [2021-07-27T23:17:41Z]       at performLoginFlowWithRetry (test_ui_api.ts:198:13)
  | [2021-07-27T23:17:41Z]       at Context.<anonymous> (test_ui_api.ts:266:5)
  | [2021-07-27T23:17:41Z]
```

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2757#4292c915-55e3-4126-860c-9267ba7e3d5b/5855-6176

```
[2021-07-29T12:57:14Z]   1) test_ui_api
[2021-07-29T12:57:14Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-29T12:57:14Z]      Error: Login did not succeed within 300 s
[2021-07-29T12:57:14Z]       at performLoginFlowWithRetry (test_ui_api.ts:198:13)
[2021-07-29T12:57:14Z]       at Context.<anonymous> (test_ui_api.ts:266:5)
```

**Comment by jgehrcke** [comment]
```
https://buildkite.com/opstrace/prs/builds/5218#7a0149d7-fd8c-482a-af56-029846774c10/2488-2809

[2021-07-27T23:17:41Z]   1) test_ui_api
--
  | [2021-07-27T23:17:41Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
  | [2021-07-27T23:17:41Z]      Error: Login did not succeed within 300 s
  | [2021-07-27T23:17:41Z]       at performLoginFlowWithRetry (test_ui_api.ts:198:13)
  | [2021-07-27T23:17:41Z]       at Context.<anonymous> (test_ui_api.ts:266:5)
```
@terrcin this symptom is not tracked by this ticket.

https://github.com/opstrace/opstrace/issues/1137 would be that :). I am carrying that over.

**Comment by jgehrcke** [comment]
and we also misled @sreis. The two comments above with 'thumbs down' have been carried over to https://github.com/opstrace/opstrace/issues/1137.

**Comment by jgehrcke** [comment]
The symptom we want to track here is `waiting for selector "[data-test='tenant ...`.

I am closing this for now, haven't seen that in a while.
