### ISSUE TITLE
ci-instability: test_ui_api create_tenant_and_use_custom_authn_token failed: Expectation not fulfilled within 2100 s

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1004]
**Describe the bug**

```
[2021-07-07T05:46:46Z]   1) test_ui_api
[2021-07-07T05:46:46Z]        create_tenant_and_use_custom_authn_token:
[2021-07-07T05:46:46Z]      Error: Expectation not fulfilled within 2100 s
[2021-07-07T05:46:46Z]       at Context.<anonymous> (test_ui.ts:426:15)
```

For now, it seems to be failing consistently on AWS:

https://buildkite.com/opstrace/scheduled-main-builds/builds/2620#72c302c8-1970-4fea-874b-b0e5de3b47b4/6-4040
https://buildkite.com/opstrace/scheduled-main-builds/builds/2619#9ada46f3-49fc-4dcf-bc7e-8d8914334938/6-3133

**Comment by jgehrcke** [comment]
Transition from ENOUTFOUND to 503 response:
```
[2021-07-07T01:20:31Z] 2021-07-07T01:20:31.746Z info: GET HTTP request to https://cortex.testtenant-ccefvm.schedul-bk-2619-2d9-a.opstrace.io/api/v1/labels failed. Attempt: 6. Error: ENOTFOUND, getaddrinfo ENOTFOUND cortex.testtenant-ccefvm.schedul-bk-2619-2d9-a.opstrace.io. Retry in 15.0 s.
[2021-07-07T01:20:46Z] 2021-07-07T01:20:46.944Z info: GET HTTP request to https://cortex.testtenant-ccefvm.schedul-bk-2619-2d9-a.opstrace.io/api/v1/labels failed. Attempt: 7. Error: undefined, Response code 503 (Service Temporarily Unavailable). Retry in 15.0 s. Response code: 503. Response body[:500]: <html>
[2021-07-07T01:20:46Z] <head><title>503 Service Temporarily Unavailable</title></head>
[2021-07-07T01:20:46Z] <body>
[2021-07-07T01:20:46Z] <center><h1>503 Service Temporarily Unavailable</h1></center>
[2021-07-07T01:20:46Z] <hr><center>nginx</center>
[2021-07-07T01:20:46Z] </body>
[2021-07-07T01:20:46Z] </html>
```

**Comment by jgehrcke** [comment]
was trying to follow the 503 through logs but didn't get anywhere in reasonable time, aborting

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2622#ed9881af-6134-470b-a57f-a0ff0917e083/6-1993

**Comment by jgehrcke** [comment]
AWS build here affected: https://buildkite.com/opstrace/prs/builds/4992#2269583b-a8f2-4e7b-a0f6-f25c863e800b

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/5002#2af8b8e2-4226-49e6-9164-a6df1d8b967a/6-2066

**Comment by sreis** [comment]
```
[2021-07-09T16:19:26Z] [92m [0m[32m 6 passing[0m[90m (39m)[0m
[2021-07-09T16:19:26Z] [31m  1 failing[0m
[2021-07-09T16:19:26Z] 
[2021-07-09T16:19:26Z] [0m  1) test_ui_api
[2021-07-09T16:19:26Z]        create_tenant_and_use_custom_authn_token:
[2021-07-09T16:19:26Z] [0m[31m     Error: Expectation not fulfilled within 2100 s[0m[90m
[2021-07-09T16:19:26Z]       at Context.<anonymous> (test_ui.ts:422:15)
[2021-07-09T16:19:26Z] [0m
```

https://buildkite.com/opstrace/prs/builds/5028#b918d3bc-3526-44ec-9848-31ff4e5c0968 (note: Builkite UI truncates the log)

**Comment by sreis** [comment]
```
[2021-07-09T17:49:43Z] [92m [0m[32m 6 passing[0m[90m (40m)[0m
[2021-07-09T17:49:43Z] [31m  1 failing[0m
[2021-07-09T17:49:43Z] 
[2021-07-09T17:49:43Z] [0m  1) test_ui_api
[2021-07-09T17:49:43Z]        create_tenant_and_use_custom_authn_token:
[2021-07-09T17:49:43Z] [0m[31m     Error: Expectation not fulfilled within 2100 s[0m[90m
[2021-07-09T17:49:43Z]       at Context.<anonymous> (test_ui.ts:422:15)
[2021-07-09T17:49:43Z] [0m
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2635#f6f5c262-e24b-4560-b560-18ba598fbf9c

**Comment by sreis** [comment]
```
[2021-07-10T05:54:51Z]   1) test_ui_api
[2021-07-10T05:54:51Z]        create_tenant_and_use_custom_authn_token:
[2021-07-10T05:54:51Z]      Error: Expectation not fulfilled within 2100 s
[2021-07-10T05:54:51Z]       at Context.<anonymous> (test_ui.ts:422:15)
[2021-07-10T05:54:51Z] 
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2638#eda0a021-be63-4f44-ac19-0c28e77ec854/6-2672

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2636#2e7bc7cd-ef68-4fc7-bed1-7a5ddf301635/6-3078

**Comment by sreis** [comment]
```
[2021-07-10T21:43:52Z] [92m [0m[32m 6 passing[0m[90m (38m)[0m
[2021-07-10T21:43:52Z] [31m  1 failing[0m
[2021-07-10T21:43:52Z] 
[2021-07-10T21:43:52Z] [0m  1) test_ui_api
[2021-07-10T21:43:52Z]        create_tenant_and_use_custom_authn_token:
[2021-07-10T21:43:52Z] [0m[31m     Error: Expectation not fulfilled within 2100 s[0m[90m
[2021-07-10T21:43:52Z]       at Context.<anonymous> (test_ui.ts:422:15)
[2021-07-10T21:43:52Z] [0m
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2642#4c3b0eff-f087-4bf6-b3b3-c0f553f57c9b

**Comment by sreis** [comment]
```
[2021-07-12T05:52:12Z]   6 passing (38m)
[2021-07-12T05:52:12Z]   1 failing
[2021-07-12T05:52:12Z]
[2021-07-12T05:52:12Z]   1) test_ui_api
[2021-07-12T05:52:12Z]        create_tenant_and_use_custom_authn_token:
[2021-07-12T05:52:12Z]      Error: Expectation not fulfilled within 2100 s
[2021-07-12T05:52:12Z]       at Context.<anonymous> (test_ui.ts:422:15)
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2650#67581d8a-0163-409f-80ed-46320a5bfe9d/6-2354

**Comment by sreis** [comment]
nginx controller logs only show the following:

```
2021-07-10 12:41:49	
192.168.45.55 - - [10/Jul/2021:12:41:49 +0000] "GET /api/v1/labels HTTP/1.1" 503 190 "-" "got (https://github.com/sindresorhus/got)" 847 0.000 [testtenantuvlwru-tenant-cortex-api-8080] [] - - - - 4ac83ec47e89c9b33d403046a3820ea6
```

I'm running tests in a branch with increased log level in nginx ingress controller to see if show something else.

**Comment by jgehrcke** [comment]
> I'm running tests in a branch with increased log level in nginx ingress controller to see if show something else.

Actually, we should always collect the nginx error log -- it is supposed to have much less volume than the access log. 

I assume that it's actually Cortex that emits the 503 response, and from nginx' point of view everything's cool (also from the API proxy's point of view).

**Comment by sreis** [comment]
> Actually, we should always collect the nginx error log -- it is supposed to have much less volume than the access log.

Yeah we're not setting the right option in [the config map](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#logging).

> I assume that it's actually Cortex that emits the 503 response, and from nginx' point of view everything's cool (also from the API proxy's point of view).

There are no errors in the Cortex logs (either querier or query-frontend) hence the attempt to look at nginx running with increased log level output.

**Comment by nickbp** [comment]
Several instances over a week in July, may have been fixed
