### ISSUE TITLE
ci-instability: debugging this should FAIL all the time

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1011]
**Describe the bug**

```
2021-07-08T09:31:13Z]   1) tests/I6FiM_debugging.spec.ts:34:3 › [Pixel-4] debugging this should FAIL all the time ========
[2021-07-08T09:31:13Z]
[2021-07-08T09:31:13Z]     page.waitForSelector: Timeout 30000ms exceeded.
[2021-07-08T09:31:13Z]     =========================== logs ===========================
[2021-07-08T09:31:13Z]     waiting for selector "[data-test=getting-started]" to be visible
[2021-07-08T09:31:13Z]     ============================================================
[2021-07-08T09:31:13Z]     Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```
https://buildkite.com/opstrace/upgrade-tests/builds/950#2aa6a13c-68b5-4000-8070-76355a1f2aeb/874-8571

**Expected behavior**

The test should be [skipped](https://github.com/opstrace/opstrace/blob/main/test/browser/tests/debugging.spec.ts#L34-L35
).

**Comment by sreis** [comment]
```
[2021-07-13T09:17:12Z]   1) tests/PUpNM_debugging.spec.ts:29:3 › [Chromium] debugging this should FAIL all the time =======
[2021-07-13T09:17:12Z]
[2021-07-13T09:17:12Z]     Timeout of 120000ms exceeded.
[2021-07-13T09:17:12Z]
[2021-07-13T09:17:12Z]     Pending operations:
[2021-07-13T09:17:12Z]       - page.waitForSelector at utils/authentication.ts:24:14
[2021-07-13T09:17:12Z]
[2021-07-13T09:17:12Z]     browserContext.newPage: Protocol error (Target.createTarget): browserContextId
[2021-07-13T09:17:12Z]
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2657#a34d6922-62e4-4780-a538-b48992370130/8286-8305

**Comment by jgehrcke** [comment]
```
[2021-07-13T13:38:12Z] Running 80 tests using 1 worker
[2021-07-13T14:02:22Z] ··°°············°···········×··±°°°··············×°×··±···········°°············
[2021-07-13T14:02:38Z] ·
[2021-07-13T14:02:38Z]
[2021-07-13T14:02:38Z]   1) tests/mXUmw_debugging.spec.ts:29:3 › [Pixel-4] debugging this should FAIL all the time ========
[2021-07-13T14:02:38Z]
[2021-07-13T14:02:38Z]     Timeout of 120000ms exceeded.
[2021-07-13T14:02:38Z]
```
https://buildkite.com/opstrace/prs/builds/5068#76b86627-0027-4456-aaeb-e8cdbc1e6b5a/2421-2441

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2687#e032fa68-9e74-460a-a4bc-bf60f4447caa/3069-3089

```
[2021-07-18T09:52:29Z]   1) tests/olo9s_debugging.spec.ts:29:3 › [Chromium] debugging this should FAIL all the time =======
[2021-07-18T09:52:29Z]
[2021-07-18T09:52:29Z]     Timeout of 120000ms exceeded.
[2021-07-18T09:52:29Z]
[2021-07-18T09:52:29Z]     Pending operations:
[2021-07-18T09:52:29Z]       - page.waitForSelector at utils/authentication.ts:29:14
[2021-07-18T09:52:29Z]
[2021-07-18T09:52:29Z]     browserContext.newPage: Protocol error (Target.createTarget): browserContextId
[2021-07-18T09:52:29Z]
[2021-07-18T09:52:29Z]       1 | /**
[2021-07-18T09:52:29Z]       2 |  * Copyright 2021 Opstrace, Inc.
[2021-07-18T09:52:29Z]       3 |  *
[2021-07-18T09:52:29Z]
[2021-07-18T09:52:29Z]     Error
[2021-07-18T09:52:29Z]         at Object.captureStackTrace (/build/test/browser/node_modules/@playwright/test/lib/utils/stackTrace.js:51:19)
[2021-07-18T09:52:29Z]         at Connection.sendMessageToServer (/build/test/browser/node_modules/@playwright/test/lib/client/connection.js:73:48)
[2021-07-18T09:52:29Z]         at Proxy.<anonymous> (/build/test/browser/node_modules/@playwright/test/lib/client/channelOwner.js:64:61)
[2021-07-18T09:52:29Z]         at /build/test/browser/node_modules/@playwright/test/lib/client/browserContext.js:166:52
[2021-07-18T09:52:29Z]         at BrowserContext._wrapApiCall (/build/test/browser/node_modules/@playwright/test/lib/client/channelOwner.js:77:34)
[2021-07-18T09:52:29Z]         at BrowserContext.newPage (/build/test/browser/node_modules/@playwright/test/lib/client/browserContext.js:163:21)
[2021-07-18T09:52:29Z]         at Object.page [as fn] (/build/test/browser/node_modules/@playwright/test/lib/test/index.js:214:33)
[2021-07-18T09:52:29Z]         at Fixture.setup (/build/test/browser/node_modules/@playwright/test/lib/test/fixtures.js:69:73)
[2021-07-18T09:52:29Z]         at runNextTicks (node:internal/process/task_queues:61:5)
[2021-07-18T09:52:29Z]         at processImmediate (node:internal/timers:437:9)
[2021-07-18T09:52:29Z]         at FixtureRunner.setupFixtureForRegistration (/build/test/browser/node_modules/@playwright/test/lib/test/fixtures.js:251:9)
[2021-07-18T09:52:29Z]         at FixtureRunner.resolveParametersAndRunHookOrTest (/build/test/browser/node_modules/@playwright/test/lib/test/fixtures.js:238:29)
[2021-07-18T09:52:29Z]         at WorkerRunner._runTestWithBeforeHooks (/build/test/browser/node_modules/@playwright/test/lib/test/workerRunner.js:290:13)
[2021-07-18T09:52:29Z]
[2021-07-18T09:52:29Z]   Slow test: dsWpT_tenant.spec.ts (16m)
[2021-07-18T09:52:29Z]   Slow test: olo9s_debugging.spec.ts (3m)
[2021-07-18T09:52:29Z]   Slow test: QeZuE_regression.spec.ts (3m)
[2021-07-18T09:52:29Z]   Slow test: jNJv2_authentication.spec.ts (2m)
[2021-07-18T09:52:29Z]
[2021-07-18T09:52:29Z]   1 failed
[2021-07-18T09:52:29Z]     tests/olo9s_debugging.spec.ts:29:3 › [Chromium] debugging this should FAIL all the time ========
[2021-07-18T09:52:29Z]   9 skipped
[2021-07-18T09:52:29Z]   80 passed (24m)
```

**Comment by sreis** [comment]
https://buildkite.com/opstrace/prs/builds/5098

**Comment by sreis** [comment]
```
[2021-07-23T05:50:15Z]   1) tests/6RAOD_debugging.spec.ts:29:3 › [Chromium] debugging this should FAIL all the time =======
[2021-07-23T05:50:15Z]
[2021-07-23T05:50:15Z]     Timeout of 120000ms exceeded.
[2021-07-23T05:50:15Z]
[2021-07-23T05:50:15Z]     Pending operations:
[2021-07-23T05:50:15Z]       - page.waitForSelector at utils/authentication.ts:29:14
[2021-07-23T05:50:15Z]
[2021-07-23T05:50:15Z]     browserContext.newPage: Protocol error (Target.createTarget): browserContextId
[2021-07-23T05:50:15Z]
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2716#f0958f63-09ab-4d45-bdc2-1775c12ccd58/2725-2745

**Comment by sreis** [comment]
```
[2021-07-22T18:04:29Z]   1) tests/zlwH0_debugging.spec.ts:29:3 › [Chromium] debugging this should FAIL all the time =======
[2021-07-22T18:04:29Z]
[2021-07-22T18:04:29Z]     Timeout of 120000ms exceeded.
[2021-07-22T18:04:29Z]
[2021-07-22T18:04:29Z]     Pending operations:
[2021-07-22T18:04:29Z]       - page.waitForSelector at utils/authentication.ts:29:14
[2021-07-22T18:04:29Z]
[2021-07-22T18:04:29Z]     browserContext.newPage: Protocol error (Target.createTarget): browserContextId
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2713#0ae3800e-bae3-4220-9466-641139456aa8/9487-9507

**Comment by jgehrcke** [comment]
```
[2021-07-23T11:24:13Z] Running 90 tests using 1 worker
[2021-07-23T11:55:22Z] °°·······×··±····················°°················°×··°··×··±··×°±··×··±·····°·
[2021-07-23T11:58:59Z] ············°
[2021-07-23T11:58:59Z]
[2021-07-23T11:58:59Z]   1) tests/yoIa2_debugging.spec.ts:29:3 › [WebKit] debugging this should FAIL all the time =========
[2021-07-23T11:58:59Z]
[2021-07-23T11:58:59Z]     Timeout of 120000ms exceeded.
[2021-07-23T11:58:59Z]
[2021-07-23T11:58:59Z]     Pending operations:
[2021-07-23T11:58:59Z]       - page.waitForSelector at utils/authentication.ts:38:14
[2021-07-23T11:58:59Z]
[2021-07-23T11:58:59Z]     browserContext.newPage: Protocol error (Playwright.createPage): Could not find browser context for given id [{"code":-32000,"message":"Could not find browser context for given id"}]
```
https://buildkite.com/opstrace/prs/builds/5139#e92d7aca-c427-4a94-a4e7-de8c28ab3b70/1989-2005

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/5140#58abbc65-034f-43ac-96a4-c9db2db16a33/1062-1087
```
[2021-07-23T12:11:06Z]   1) tests/yoIa2_debugging.spec.ts:29:3 › [Chromium] debugging this should FAIL all the time =======
[2021-07-23T12:11:06Z]
[2021-07-23T12:11:06Z]     Timeout of 120000ms exceeded.
[2021-07-23T12:11:06Z]
[2021-07-23T12:11:06Z]     Pending operations:
[2021-07-23T12:11:06Z]       - page.waitForSelector at utils/authentication.ts:38:14
[2021-07-23T12:11:06Z]
[2021-07-23T12:11:06Z]     browserContext.newPage: Protocol error (Target.createTarget): browserContextId
```

**Comment by sreis** [comment]
```
 1) tests/RpK1q_debugging.spec.ts:29:3 › [Pixel-4] debugging this should FAIL all the time ========
[2021-07-27T05:06:57Z]     Timeout of 120000ms exceeded.
[2021-07-27T05:06:57Z]
[2021-07-27T05:06:57Z]     Pending operations:
[2021-07-27T05:06:57Z]       - page.waitForSelector at utils/authentication.ts:54:16
[2021-07-27T05:06:57Z]
[2021-07-27T05:06:57Z]     browserContext.newPage: Protocol error (Target.createTarget): browserContextId
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2740#f6c90111-fa61-4325-8513-0a6e540e7cdd/6705-6724

**Comment by sreis** [comment]
```
[2021-07-27T04:55:45Z]   1) tests/RpK1q_debugging.spec.ts:29:3 › [Chromium] debugging this should FAIL all the time =======
[2021-07-27T04:55:45Z]
[2021-07-27T04:55:45Z]     Error: browserContext.addCookies: cookies: expected array, got object
[2021-07-27T04:55:45Z]     Timeout of 120000ms exceeded.
[2021-07-27T04:55:45Z]
[2021-07-27T04:55:45Z]     Pending operations:
[2021-07-27T04:55:45Z]       - page.waitForSelector at utils/authentication.ts:54:16
[2021-07-27T04:55:45Z]
[2021-07-27T04:55:45Z]     browserContext.newPage: Protocol error (Target.createTarget): browserContextId
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2740#1d54a8ff-df84-4678-b561-01a7e68b2d77/5690-5730

**Comment by nickbp** [comment]
Hasn't repro'ed after several instances in July, guessing something was fixed
