### ISSUE TITLE
upgrade tests: OPSTRACE_INSTANCE_DNS_NAME not properly set for looker tests

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1041]
looker tests failed on https://buildkite.com/opstrace/upgrade-tests/builds/973 because of a bad URL:
```
2021-07-12T12:49:39.609Z [32minfo[39m: rendered config:
{
  "apibaseurl": "https://loki.default.",
```
That was resulting in 
```
2021-07-12T12:55:21.779Z [32minfo[39m: POST PushRequest(md5=188281e135509b418c4d59ced1d9667d): schedule to perform attempt 17 in 30.00 s
2021-07-12T12:55:24.624Z [31mwarning[39m: POST PushRequest(md5=f0494f7b8199bb5fb4469996a127afde): attempt 16: transient problem: getaddrinfo ENOTFOUND loki.default.
2021-07-12T12:55:24.624Z [32minfo[39m: POST PushRequest(md5=f0494f7b8199bb5fb4469996a127afde): schedule to perform attempt 17 in 30.00 s
2021-07-12T12:55:51.779Z [31mcrit[39m: consider critical: Error: Failed to POST PushRequest(md5=188281e135509b418c4d59ced1d9667d): attempt 17 would trigger 12.12 s over the deadline (360 s).
    at customPostWithRetryOrError (/build/_tscbuild/index.js:680:19)
    at async _genAndPost (/build/_tscbuild/index.js:559:13)
    at async _produceAndPOSTpushrequest (/build/_tscbuild/index.js:588:9)
    at async pushrequestProducerAndPOSTer (/build/_tscbuild/index.js:618:9)
    at async Promise.all (index 0)
    at async generateAndPostFragments (/build/_tscbuild/index.js:450:5)
    at async writePhase (/build/_tscbuild/index.js:277:5)
    at async performWriteReadCycle (/build/_tscbuild/index.js:208:24)
    at async main (/build/_tscbuild/index.js:106:13)
```

**Comment by jgehrcke** [comment]
Hm looks like I was looking at an old build. In https://buildkite.com/opstrace/upgrade-tests/builds/975 the looker tests passed.
