### ISSUE TITLE
ci-instability: fluentbit(grafana loki plugin) with basic auth: Error: Expectation not fulfilled within 30 s

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1059]
**Describe the bug**
```
[2021-07-15T05:16:25Z]   1) Loki API test suite
[2021-07-15T05:16:25Z]        fluentbit(grafana loki plugin) with basic auth:
[2021-07-15T05:16:25Z]      Error: Expectation not fulfilled within 30 s
[2021-07-15T05:16:25Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:265:9)
[2021-07-15T05:16:25Z]       at runMicrotasks (<anonymous>)
[2021-07-15T05:16:25Z]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-07-15T05:16:25Z]       at Context.<anonymous> (test_loki_log_ingest_api.ts:236:5)
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2668#edafbedf-6ca8-4372-99af-9b69af463dc9/6-588

**Comment by jgehrcke** [comment]
I looked at the fluentbit log output :
```
[2021-07-15T05:02:01Z] [2021/07/15 05:01:50] [ info] [sp] stream processor started
[2021-07-15T05:02:01Z] ������ï¿½[2021/07/15 05:01:50] [debug] [input:tail:tail.0] inode=234972070 file=/tmp/opstrace-test-remote/fbit-log-input--30-KfjcyTMJp0DW-.log promote to TAIL_EVENT
[2021-07-15T05:02:01Z] ������ï¿½[2021/07/15 05:01:50] [ info] [input:tail:tail.0] inotify_fs_add(): inode=234972070 watch_fd=1 name=/tmp/opstrace-test-remote/fbit-log-input--30-KfjcyTMJp0DW-.log
[2021-07-15T05:02:01Z] ������I[2021/07/15 05:01:51] [debug] [task] created task=0x7f85cf437500 id=0 OK
[2021-07-15T05:02:01Z] ������ï¿½[0] tail.0: [1626325310.546936056, {"log"=>"aaaaaaa"}]
[2021-07-15T05:02:01Z] [1] tail.0: [1626325310.546945240, {"log"=>"bbbbbb"}]
[2021-07-15T05:02:01Z] [2] tail.0: [1626325310.546945449, {"log"=>"cccccccc"}]
[2021-07-15T05:02:01Z] ������ï¿½[2021/07/15 05:01:51] [debug] [out coro] cb_destroy coro_id=0
[2021-07-15T05:02:01Z] [2021/07/15 05:01:51] [debug] [out coro] cb_destroy coro_id=0
[2021-07-15T05:02:01Z] [2021/07/15 05:01:51] [debug] [task] destroy task=0x7f85cf437500 (task_id=0)
[2021-07-15T05:02:01Z] ������l[2021/07/15 05:01:51] [engine] caught signal (SIGTERM)
[2021-07-15T05:02:01Z] [2021/07/15 05:01:51] [ info] [input] pausing tail.0
[2021-07-15T05:02:01Z] ������F[2021/07/15 05:01:51] [ warn] [engine] service will stop in 5 seconds
[2021-07-15T05:02:01Z] �����-[2021/07/15 05:01:56] [ info] [engine] service stopped
[2021-07-15T05:02:01Z] [2021/07/15 05:01:56] [debug] [input:tail:tail.0] inode=234972070 removi
```

I think what happened here is exactly what I was talking about in https://github.com/opstrace/opstrace/pull/1043#discussion_r669485222.

Will add a bit of leeway to make this more stable.

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/upgrade-tests/builds/1134#6f36ebc4-6a29-492a-838e-7e29c83a3808/4106-5944

**Comment by nickbp** [comment]
Hasn't repro'ed for a couple months after having repros every week or two, may have been fixed
