### ISSUE TITLE
ci instability: End-to-end alerts for ...: Expectation not fulfilled within 300 s

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1102]
**NOTE, August 2**: the original main symptom tracked here was `Expectation not fulfilled within 30 s`.

Since then, code had changed, and a _different_ instability symptom (not unlikely as of the same root cause) popped up, showing as `Expectation not fulfilled within 300 s`. Usually we should have created a new ticket for the new symptom, but now it's ok to track the new symptom here. I've updated the title.

------------

```
[2021-07-26T01:09:32Z]   21 passing (26m)
[2021-07-26T01:09:32Z]   4 pending
[2021-07-26T01:09:32Z]   2 failing
[2021-07-26T01:09:32Z]
[2021-07-26T01:09:32Z]   1) End-to-end alert tests
[2021-07-26T01:09:32Z]        End-to-end alerts for default tenant:
[2021-07-26T01:09:32Z]      Error: Expectation not fulfilled within 30 s
[2021-07-26T01:09:32Z]       at Object.waitForQueryResult (testutils/index.ts:931:9)
[2021-07-26T01:09:32Z]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-07-26T01:09:32Z]       at getE2EAlertCountMetric (test_alerts.ts:301:23)
[2021-07-26T01:09:32Z]       at testE2EAlertsForTenant (test_alerts.ts:365:17)
[2021-07-26T01:09:32Z]       at Context.<anonymous> (test_alerts.ts:422:5)
```

```
[2021-07-26T00:45:15Z] 2021-07-26T00:45:15.952Z info: Waiting for cortex E2E alerting metric for tenant=default job=testalerts-pqoch-job with zero value
[2021-07-26T00:45:15Z] 2021-07-26T00:45:15.952Z info: Cortex query parameter (object):
[2021-07-26T00:45:15Z] {
[2021-07-26T00:45:15Z]   "query": "e2ealerting_webhook_receiver_evaluations_total{job=\"testalerts-pqoch-job\"}"
[2021-07-26T00:45:15Z] }
[2021-07-26T00:45:15Z] 2021-07-26T00:45:15.952Z info: Cortex query parameters (query string):
[2021-07-26T00:45:15Z] query=e2ealerting_webhook_receiver_evaluations_total%7Bjob%3D%22testalerts-pqoch-job%22%7D
[2021-07-26T00:45:15Z] 2021-07-26T00:45:15.953Z info: Waiting for query to return a match, deadline in 30s
[2021-07-26T00:45:15Z] 2021-07-26T00:45:15.953Z info: read token from /tmp/opstrace-bk-2733-7aff1e6-1-gcp/tenant-api-token-default
[2021-07-26T00:48:19Z] 2021-07-26T00:48:19.147Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'request' for 60000ms -- ignore, proceed with next iteration
[2021-07-26T00:48:19Z] 2021-07-26T00:48:19.147Z error: Reached 30s deadline, giving up
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2733#5fb3b7d5-051e-4e8e-8a97-5f8c0f4f7ebb/2655-2772

**Comment by jgehrcke** [comment]
```
[2021-07-25T17:05:35Z] 2021-07-25T17:05:35.313Z [32minfo[39m: Cortex query parameters (query string):
[2021-07-25T17:05:35Z] query=e2ealerting_webhook_receiver_evaluations_total%7Bjob%3D%22testalerts-bO6_K-job%22%7D
[2021-07-25T17:05:35Z] 2021-07-25T17:05:35.313Z [32minfo[39m: Waiting for query to return a match, deadline in 30s
[2021-07-25T17:05:35Z] 2021-07-25T17:05:35.313Z [32minfo[39m: read token from /tmp/opstrace-bk-2731-7aff1e6-1-aws/tenant-api-token-system
[2021-07-25T17:08:38Z] 2021-07-25T17:08:38.573Z [32minfo[39m: waitForQueryResult() loop: http request failed: Timeout awaiting 'request' for 60000ms -- ignore, proceed with next iteration
[2021-07-25T17:08:38Z] 2021-07-25T17:08:38.573Z [31merror[39m: Reached 30s deadline, giving up
[2021-07-25T17:08:38Z]   [31m  1) End-to-end alerts for system tenant[0m
```

**Comment by jgehrcke** [comment]
same observation as for https://github.com/opstrace/opstrace/issues/1103#issuecomment-886452492

**Comment by jgehrcke** [comment]
```
[2021-07-25T12:48:52Z] 2021-07-25T12:48:52.076Z info: Waiting for query to return a match, deadline in 30s
[2021-07-25T12:48:52Z] 2021-07-25T12:48:52.076Z info: read token from /tmp/opstrace-bk-2730-a0fb5b7-1-gcp/tenant-api-token-system
[2021-07-25T12:51:55Z] 2021-07-25T12:51:55.296Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'request' for 60000ms -- ignore, proceed with next iteration
[2021-07-25T12:51:55Z] 2021-07-25T12:51:55.296Z error: Reached 30s deadline, giving up
[2021-07-25T12:51:55Z]     1) End-to-end alerts for system tenant
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2730#742bc765-3134-4144-9d7a-188edb5b6681

**Comment by terrcin** [comment]
and again: https://buildkite.com/opstrace/prs/builds/5203#bca1b55b-eda3-47db-b6a4-0118a620f8f5/2971-4834

**Comment by terrcin** [comment]
and again: https://buildkite.com/opstrace/prs/builds/5206#6ef2d5ba-d1a1-47bb-b5e7-f345a5d274fd/1059-2970

**Comment by terrcin** [comment]
and again: https://buildkite.com/opstrace/prs/builds/5203#bca1b55b-eda3-47db-b6a4-0118a620f8f5/2971-4834

but not all the time

**Comment by jgehrcke** [comment]
after the changes in https://github.com/opstrace/opstrace/pull/1104 we got additional valuable detail on how things are failing:
```
2021-07-27T05:49:34Z] 2021-07-27T05:49:34.805Z [32minfo[39m: Waiting for query to return a match, deadline in 30s
[2021-07-27T05:49:44Z] 2021-07-27T05:49:44.906Z [32minfo[39m: waitForQueryResult() loop: http request failed: Timeout awaiting 'response' for 10000ms -- ignore, proceed with next iteration
[2021-07-27T05:49:54Z] 2021-07-27T05:49:54.916Z [32minfo[39m: waitForQueryResult() loop: http request failed: Timeout awaiting 'response' for 10000ms -- ignore, proceed with next iteration
[2021-07-27T05:50:04Z] 2021-07-27T05:50:04.936Z [32minfo[39m: waitForQueryResult() loop: http request failed: Timeout awaiting 'response' for 10000ms -- ignore, proceed with next iteration
[2021-07-27T05:50:04Z] 2021-07-27T05:50:04.937Z [31merror[39m: Reached 30 s deadline, giving up
[2021-07-27T05:50:04Z]   [31m  1) End-to-end alerts for default and system tenants[0m
[2021-07-27T05:50:04Z] 2021-07-27T05:50:04.991Z [32minfo[39m: suite teardown
```
main test aws on https://buildkite.com/opstrace/prs/builds/5204

**Comment by terrcin** [comment]
got it again, but yes with a bunch more detail :-)

```
[2021-07-27T22:57:26Z]   1) End-to-end alert tests
--
  | [2021-07-27T22:57:26Z]        End-to-end alerts for default and system tenants:
  | [2021-07-27T22:57:26Z]
  | [2021-07-27T22:57:26Z]       AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  | [2021-07-27T22:57:26Z]
  | [2021-07-27T22:57:26Z]   resources.push(
  | [2021-07-27T22:57:26Z]    new V1ServicemonitorResource(
  | [2021-07-27T22:57:26Z]      {
  | [2021-07-27T22:57:26Z]        apiVersion: "monitoring.coreos.com/v1",
  | [2021-07-27T22:57:26Z]        kind: "ServiceMonitor",
  | [2021-07-27T22:57:26Z]        metadata: {
  | [2021-07-27T22:57:26Z]          name,
  | [2021-07-27T22:57:26Z]          namespace,
  | [2021-07-27T22:57:26Z]          labels
  | [2021-07-27T22:57:26Z]        },
  | [2021-07-27T22:57:26Z]        spec: {
  | [2021-07-27T22:57:26Z]          jobLabel: "job", // point to 'job' label in the pod
  | [2021-07-27T22:57:26Z]          endpoints: [
  | [2021-07-27T22:57:26Z]            {
  | [2021-07-27T22:57:26Z]              // Spam it at 5s to get faster responses in tests
  | [2021-07-27T22:57:26Z]              interval: "5s",
  | [2021-07-27T22:57:26Z]              port: "http",
  | [2021-07-27T22:57:26Z]              path: "/metrics"
  | [2021-07-27T22:57:26Z]            }
  | [2021-07-27T22:57:26Z]          ],
  | [2021-07-27T22:57:26Z]          selector: {
  | [2021-07-27T22:57:26Z]            matchLabels
  | [2021-07-27T22:57:26Z]          }
  | [2021-07-27T22:57:26Z]        }
  | [2021-07-27T22:57:26Z]      },
  | [2021-07-27T22:57:26Z]      kubeConfig
  | [2021-07-27T22:57:26Z]    )
  | [2021-07-27T22:57:26Z]   )
  | [2021-07-27T22:57:26Z]
  | [2021-07-27T22:57:26Z]       + expected - actual
  | [2021-07-27T22:57:26Z]
  | [2021-07-27T22:57:26Z]       -false
  | [2021-07-27T22:57:26Z]       +true
  | [2021-07-27T22:57:26Z]
  | [2021-07-27T22:57:26Z]       at storeE2EAlertsConfig (test_alerts.ts:241:3)
  | [2021-07-27T22:57:26Z]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
  | [2021-07-27T22:57:26Z]       at setupE2EAlertsForTenant (test_alerts.ts:348:3)
  | [2021-07-27T22:57:26Z]       at Context.<anonymous> (test_alerts.ts:445:33)
  | [2021-07-27T22:57:26Z]
```





https://buildkite.com/opstrace/prs/builds/5219#1260481d-5ba2-4ed1-96da-5617124734e5/3367-5087

**Comment by terrcin** [comment]
Different failure output this time:

```
[2021-07-27T23:03:10Z]   1) End-to-end alert tests
--
  | [2021-07-27T23:03:10Z]        End-to-end alerts for default and system tenants:
  | [2021-07-27T23:03:10Z]      Error: Failed to get non-zero alerts metric value after 300s. Are alerts successfully reaching the e2ealerting pod?
  | [2021-07-27T23:03:10Z]       at waitForE2EAlertFiring (test_alerts.ts:398:13)
  | [2021-07-27T23:03:10Z]       at Context.<anonymous> (test_alerts.ts:458:5)
  | [2021-07-27T23:03:10Z]
```

https://buildkite.com/opstrace/prs/builds/5218#5d9c5a86-beb3-49d1-83a7-4c66221cfcb5/2941-4883

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/prs/builds/5222#5e7d212e-6f7f-4b34-bdfa-db85f9845df3/2980-4923

**Comment by sreis** [comment]
```
[2021-07-30T13:22:04Z]   1) End-to-end alert tests
[2021-07-30T13:22:04Z]        End-to-end alerts for default and system tenants:
[2021-07-30T13:22:04Z]      Error: Expectation not fulfilled within 300 s
[2021-07-30T13:22:04Z]       at Object.waitForQueryResult (testutils/index.ts:933:9)
[2021-07-30T13:22:04Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:80:5)
[2021-07-30T13:22:04Z]       at waitForE2EAlertFiring (test_alerts.ts:388:3)
[2021-07-30T13:22:04Z]       at Context.<anonymous> (test_alerts.ts:453:5)
[2021-07-30T13:22:04Z] 
```

https://buildkite.com/opstrace/upgrade-tests/builds/1103#3fea8fe3-b89f-496e-bd62-5697d8c781b1/4011-5784

**Comment by sreis** [comment]
```
[2021-08-01T01:23:36Z]   1) End-to-end alert tests
[2021-08-01T01:23:36Z]        End-to-end alerts for default and system tenants:
[2021-08-01T01:23:36Z]      Error: Expectation not fulfilled within 300 s
[2021-08-01T01:23:36Z]       at Object.waitForQueryResult (testutils/index.ts:933:9)
[2021-08-01T01:23:36Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:80:5)
[2021-08-01T01:23:36Z]       at waitForE2EAlertFiring (test_alerts.ts:388:3)
[2021-08-01T01:23:36Z]       at Context.<anonymous> (test_alerts.ts:453:5)
```

https://buildkite.com/opstrace/upgrade-tests/builds/1112#bed28904-3949-4eff-bf53-2703333c402c/4055-5834

**Comment by sreis** [comment]
```
[2021-08-01T20:47:27Z]   1) End-to-end alert tests
[2021-08-01T20:47:27Z]        End-to-end alerts for default and system tenants:
[2021-08-01T20:47:27Z]      Error: Expectation not fulfilled within 300 s
[2021-08-01T20:47:27Z]       at Object.waitForQueryResult (testutils/index.ts:933:9)
[2021-08-01T20:47:27Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:80:5)
[2021-08-01T20:47:27Z]       at waitForE2EAlertFiring (test_alerts.ts:388:3)
[2021-08-01T20:47:27Z]       at Context.<anonymous> (test_alerts.ts:453:5)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2777#d58df843-a6b4-45c8-b208-a5249aa086e6/2917-4694

**Comment by jgehrcke** [comment]
The symptom is that Cortex responds to queries, but the query result does not reflect the anticipated change within 5 minutes (300 s):

```
[2021-08-01T20:40:42Z] 2021-08-01T20:40:42.355Z info: Waiting for query to return a match, deadline in 300s
[2021-08-01T20:40:42Z] 2021-08-01T20:40:42.487Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:40:50Z] 2021-08-01T20:40:50.585Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:40:58Z] 2021-08-01T20:40:58.684Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:41:06Z] 2021-08-01T20:41:06.781Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:41:14Z] 2021-08-01T20:41:14.881Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:41:22Z] 2021-08-01T20:41:22.979Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:41:31Z] 2021-08-01T20:41:31.081Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:41:39Z] 2021-08-01T20:41:39.180Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:41:47Z] 2021-08-01T20:41:47.278Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:41:55Z] 2021-08-01T20:41:55.375Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:42:03Z] 2021-08-01T20:42:03.476Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:42:11Z] 2021-08-01T20:42:11.576Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:42:19Z] 2021-08-01T20:42:19.675Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:42:27Z] 2021-08-01T20:42:27.773Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:42:35Z] 2021-08-01T20:42:35.871Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:42:43Z] 2021-08-01T20:42:43.969Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:42:52Z] 2021-08-01T20:42:52.072Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:43:00Z] 2021-08-01T20:43:00.169Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:43:08Z] 2021-08-01T20:43:08.268Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:43:16Z] 2021-08-01T20:43:16.368Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:43:24Z] 2021-08-01T20:43:24.466Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:43:32Z] 2021-08-01T20:43:32.565Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:43:40Z] 2021-08-01T20:43:40.665Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:43:48Z] 2021-08-01T20:43:48.762Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:43:56Z] 2021-08-01T20:43:56.861Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:44:04Z] 2021-08-01T20:44:04.958Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:44:13Z] 2021-08-01T20:44:13.058Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:44:21Z] 2021-08-01T20:44:21.157Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:44:29Z] 2021-08-01T20:44:29.258Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:44:37Z] 2021-08-01T20:44:37.359Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:44:45Z] 2021-08-01T20:44:45.457Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:44:53Z] 2021-08-01T20:44:53.558Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:45:01Z] 2021-08-01T20:45:01.657Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:45:09Z] 2021-08-01T20:45:09.758Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:45:17Z] 2021-08-01T20:45:17.858Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:45:25Z] 2021-08-01T20:45:25.956Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:45:34Z] 2021-08-01T20:45:34.055Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:45:42Z] 2021-08-01T20:45:42.154Z info: query response data not yet as expected, retry query in 8 s
[2021-08-01T20:45:50Z] 2021-08-01T20:45:50.156Z error: Reached 300 s deadline, giving up
```

**Comment by jgehrcke** [comment]
```
[2021-08-02T12:45:26Z] 2021-08-02T12:45:26.768Z info: Waiting for query to return a match, deadline in 300s
[2021-08-02T12:45:26Z] 2021-08-02T12:45:26.880Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:45:34Z] 2021-08-02T12:45:34.996Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:45:43Z] 2021-08-02T12:45:43.112Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:45:51Z] 2021-08-02T12:45:51.224Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:45:59Z] 2021-08-02T12:45:59.333Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:46:07Z] 2021-08-02T12:46:07.442Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:46:15Z] 2021-08-02T12:46:15.552Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:46:23Z] 2021-08-02T12:46:23.669Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:46:31Z] 2021-08-02T12:46:31.782Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:46:39Z] 2021-08-02T12:46:39.893Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:46:48Z] 2021-08-02T12:46:48.002Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:46:56Z] 2021-08-02T12:46:56.111Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:47:04Z] 2021-08-02T12:47:04.220Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:47:12Z] 2021-08-02T12:47:12.330Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:47:20Z] 2021-08-02T12:47:20.443Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:47:28Z] 2021-08-02T12:47:28.559Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:47:36Z] 2021-08-02T12:47:36.667Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:47:44Z] 2021-08-02T12:47:44.779Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:47:52Z] 2021-08-02T12:47:52.886Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:48:00Z] 2021-08-02T12:48:00.997Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:48:09Z] 2021-08-02T12:48:09.106Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:48:17Z] 2021-08-02T12:48:17.218Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:48:25Z] 2021-08-02T12:48:25.328Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:48:33Z] 2021-08-02T12:48:33.437Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:48:41Z] 2021-08-02T12:48:41.545Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:48:49Z] 2021-08-02T12:48:49.655Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:48:57Z] 2021-08-02T12:48:57.764Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:49:05Z] 2021-08-02T12:49:05.879Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:49:13Z] 2021-08-02T12:49:13.988Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:49:22Z] 2021-08-02T12:49:22.100Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:49:30Z] 2021-08-02T12:49:30.208Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:49:38Z] 2021-08-02T12:49:38.322Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:49:46Z] 2021-08-02T12:49:46.431Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:49:54Z] 2021-08-02T12:49:54.545Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:50:02Z] 2021-08-02T12:50:02.655Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:50:10Z] 2021-08-02T12:50:10.764Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:50:18Z] 2021-08-02T12:50:18.877Z info: query response data not yet as expected, retry query in 8 s
[2021-08-02T12:50:26Z] 2021-08-02T12:50:26.880Z error: Reached 300 s deadline, giving up
...


[2021-08-02T12:52:09Z]   21 passing (7m)
[2021-08-02T12:52:09Z]   4 pending
[2021-08-02T12:52:09Z]   1 failing
[2021-08-02T12:52:09Z]
[2021-08-02T12:52:09Z]   1) End-to-end alert tests
[2021-08-02T12:52:09Z]        End-to-end alerts for default and system tenants:
[2021-08-02T12:52:09Z]      Error: Expectation not fulfilled within 300 s
[2021-08-02T12:52:09Z]       at Object.waitForQueryResult (testutils/index.ts:933:9)
[2021-08-02T12:52:09Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:80:5)
[2021-08-02T12:52:09Z]       at waitForE2EAlertFiring (test_alerts.ts:388:3)
[2021-08-02T12:52:09Z]       at Context.<anonymous> (test_alerts.ts:453:5)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2781#9358f814-437d-45dd-8f13-a273a1b0dbca/4243-6022

**Comment by jgehrcke** [comment]
> got it again, but yes with a bunch more detail :-)

@terrcin this was a very different symptom from the one originally tracked in the ticket, and also from the one now tracked here. 

You had seen `AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value`. About this one @sreis created a new GH issue today. See here: https://github.com/opstrace/opstrace/issues/1151 I will carry over the occurrence spotted by you.

**Comment by jgehrcke** [comment]
> Different failure output this time:

@terrcin this also was a rather different symptom from the one tracked in this ticket. You had seen `Error: Failed to get non-zero alerts metric value after 300s. Are alerts successfully reaching the e2ealerting pod?` which is tracked here: https://github.com/opstrace/opstrace/issues/1130  -- I am carrying this over :)

**Comment by nickbp** [comment]
in the most recent run it looks like the `e2ealerting` pod took a long time to get started due to an image pull flake:
```
Events:
  Type     Reason          Age                From               Message
  ----     ------          ----               ----               -------
  Normal   Scheduled       6m53s              default-scheduler  Successfully assigned default-tenant/e2ealerting-5d46f976b7-755xj to gke-pr-upgr-bk-2781-251-g-primary-c2f16930-467f
  Normal   Pulling         6m52s              kubelet            Pulling image "grafana/e2ealerting:master-db38b142"
  Warning  Failed          101s               kubelet            Failed to pull image "grafana/e2ealerting:master-db38b142": rpc error: code = Unknown desc = context canceled
  Warning  Failed          101s               kubelet            Error: ErrImagePull
  Normal   SandboxChanged  100s               kubelet            Pod sandbox changed, it will be killed and re-created.
  Normal   BackOff         99s (x2 over 99s)  kubelet            Back-off pulling image "grafana/e2ealerting:master-db38b142"
  Warning  Failed          99s (x2 over 99s)  kubelet            Error: ImagePullBackOff
  Normal   Pulled          98s                kubelet            Container image "grafana/e2ealerting:master-db38b142" already present on machine
  Normal   Created         98s                kubelet            Created container e2ealerting
  Normal   Started         97s                kubelet            Started container e2ealerting
```

I checked the 2nd most recent run and it looks like it had the same problem:
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  24m                default-scheduler  Successfully assigned default-tenant/e2ealerting-85b6b7fdd-5kq2z to gke-schedul-bk-2777-a90-g-primary-0e899db0-jzdd
  Warning  Failed     19m                kubelet            Failed to pull image "grafana/e2ealerting:master-db38b142": rpc error: code = Unknown desc = context canceled
  Warning  Failed     19m                kubelet            Error: ErrImagePull
  Normal   BackOff    19m                kubelet            Back-off pulling image "grafana/e2ealerting:master-db38b142"
  Warning  Failed     19m                kubelet            Error: ImagePullBackOff
  Normal   Pulling    19m (x2 over 24m)  kubelet            Pulling image "grafana/e2ealerting:master-db38b142"
  Normal   Pulled     19m                kubelet            Successfully pulled image "grafana/e2ealerting:master-db38b142"
  Normal   Created    19m                kubelet            Created container e2ealerting
  Normal   Started    19m                kubelet            Started container e2ealerting
```

Given this I think a reasonable fix would be to add an explicit check for the e2ealerting pod to be up and running. It looks like the pod gets unstuck after ~5 minutes (311s in the first example) so 7 or maybe 6 minutes feels like a good amount of time to wait.

**Comment by jgehrcke** [comment]
This specific symptom here hasn't been seen in a while. Closing.
