### ISSUE TITLE
ci instability: check if container metrics exist: Expectation not fulfilled within 30 s

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1103]
```
[2021-07-26T01:17:17Z]     1) check if container metrics exist
[2021-07-26T01:17:17Z] 2021-07-26T01:17:17.811Z info: suite teardown
[2021-07-26T01:17:17Z]
[2021-07-26T01:17:17Z]
[2021-07-26T01:17:17Z]   22 passing (24m)
[2021-07-26T01:17:17Z]   4 pending
[2021-07-26T01:17:17Z]   1 failing
[2021-07-26T01:17:17Z]
[2021-07-26T01:17:17Z]   1) system metrics test suite
[2021-07-26T01:17:17Z]        check if container metrics exist:
[2021-07-26T01:17:17Z]      Error: Expectation not fulfilled within 30 s
[2021-07-26T01:17:17Z]       at Object.waitForQueryResult (testutils/index.ts:931:9)
[2021-07-26T01:17:17Z]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-07-26T01:17:17Z]       at Context.<anonymous> (test_systemmetrics.ts:51:25)
```

```
[2021-07-26T01:14:14Z]   system metrics test suite
[2021-07-26T01:14:14Z] 2021-07-26T01:14:14.669Z info: suite setup
[2021-07-26T01:14:14Z] 2021-07-26T01:14:14.669Z info: globalTestSuiteSetupOnce()
[2021-07-26T01:14:14Z] 2021-07-26T01:14:14.669Z info: Cortex query parameter (object):
[2021-07-26T01:14:14Z] {
[2021-07-26T01:14:14Z]   "end": "1627265654",
[2021-07-26T01:14:14Z]   "query": "process_cpu_seconds_total{container=\"ingester\", namespace=\"cortex\"}",
[2021-07-26T01:14:14Z]   "start": "1627258454",
[2021-07-26T01:14:14Z]   "step": "1"
[2021-07-26T01:14:14Z] }
[2021-07-26T01:14:14Z] 2021-07-26T01:14:14.669Z info: Cortex query parameters (query string):
[2021-07-26T01:14:14Z] query=process_cpu_seconds_total%7Bcontainer%3D%22ingester%22%2C+namespace%3D%22cortex%22%7D&start=1627258454&end=1627265654&step=1
[2021-07-26T01:14:14Z] 2021-07-26T01:14:14.670Z info: Waiting for query to return a match, deadline in 30s
[2021-07-26T01:14:14Z] 2021-07-26T01:14:14.670Z info: read token from /tmp/opstrace-bk-2733-7aff1e6-1-aws/tenant-api-token-system
[2021-07-26T01:17:17Z] 2021-07-26T01:17:17.788Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'request' for 60000ms -- ignore, proceed with next iteration
[2021-07-26T01:17:17Z] 2021-07-26T01:17:17.788Z error: Reached 30s deadline, giving up
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2733#a6a53275-be0a-406d-88a4-8bc3798a112e/6-584

**Comment by jgehrcke** [comment]
this is problematic:

```
[2021-07-26T01:14:14Z] 2021-07-26T01:14:14.670Z info: Waiting for query to return a match, deadline in 30s
[2021-07-26T01:14:14Z] 2021-07-26T01:14:14.670Z info: read token from /tmp/opstrace-bk-2733-7aff1e6-1-aws/tenant-api-token-system
[2021-07-26T01:17:17Z] 2021-07-26T01:17:17.788Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'request' for 60000ms -- ignore, proceed with next iteration
[2021-07-26T01:17:17Z] 2021-07-26T01:17:17.788Z error: Reached 30s deadline, giving up
```

log msg says "30s deadline", but log msg timestamps show that 3 minutes passed

**Comment by jgehrcke** [comment]
I find it suspicious that there is only _one_ log msg about the timed out HTTP request. It is expected that more than one HTTP request is performed within three minutes.

**Comment by jgehrcke** [comment]
```
[2021-07-25T20:59:42Z] 2021-07-25T20:59:42.852Z info: Waiting for query to return a match, deadline in 30s
[2021-07-25T20:59:42Z] 2021-07-25T20:59:42.852Z info: read token from /tmp/opstrace-bk-2732-7aff1e6-1-gcp/tenant-api-token-system
[2021-07-25T21:02:46Z] 2021-07-25T21:02:46.034Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'request' for 60000ms -- ignore, proceed with next iteration
[2021-07-25T21:02:46Z] 2021-07-25T21:02:46.034Z error: Reached 30s deadline, giving up
[2021-07-25T21:02:46Z]     1) check if container metrics exist
[2021-07-25T21:02:46Z] 2021-07-25T21:02:46.062Z info: suite teardown
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2732#894e5f70-eb1f-47a7-b60d-af5ab8e5cde9/1502-4985

**Comment by jgehrcke** [comment]
main-test-aws in https://buildkite.com/opstrace/scheduled-main-builds/builds/2729
```
[2021-07-25T09:19:17Z] 2021-07-25T09:19:17.127Z [32minfo[39m: Cortex query parameters (query string):
[2021-07-25T09:19:17Z] query=process_cpu_seconds_total%7Bcontainer%3D%22ingester%22%2C+namespace%3D%22cortex%22%7D&start=1627201157&end=1627208357&step=1
[2021-07-25T09:19:17Z] 2021-07-25T09:19:17.127Z [32minfo[39m: Waiting for query to return a match, deadline in 30s
[2021-07-25T09:19:17Z] 2021-07-25T09:19:17.127Z [32minfo[39m: read token from /tmp/opstrace-bk-2729-a0fb5b7-1-aws/tenant-api-token-system
[2021-07-25T09:22:20Z] 2021-07-25T09:22:20.283Z [32minfo[39m: waitForQueryResult() loop: http request failed: Timeout awaiting 'request' for 60000ms -- ignore, proceed with next iteration
[2021-07-25T09:22:20Z] 2021-07-25T09:22:20.283Z [31merror[39m: Reached 30s deadline, giving up
[2021-07-25T09:22:20Z]   [31m  1) check if container metrics exist[0m
[2021-07-25T09:22:20Z] 2021-07-25T09:22:20.319Z [32minfo[39m: suite teardown
[2021-07-25T09:22:20Z] 
[2021-07-25T09:22:20Z] 
[2021-07-25T09:22:20Z] [92m [0m[32m 22 passing[0m[90m (25m)[0m
[2021-07-25T09:22:20Z] [36m [0m[36m 4 pending[0m
[2021-07-25T09:22:20Z] [31m  1 failing[0m
[2021-07-25T09:22:20Z] 
[2021-07-25T09:22:20Z] [0m  1) system metrics test suite
[2021-07-25T09:22:20Z]        check if container metrics exist:
[2021-07-25T09:22:20Z] [0m[31m     Error: Expectation not fulfilled within 30 s[0m[90m
[2021-07-25T09:22:20Z]       at Object.waitForQueryResult (testutils/index.ts:931:9)
[2021-07-25T09:22:20Z]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-07-25T09:22:20Z]       at Context.<anonymous> (test_systemmetrics.ts:51:25)
[2021-07-25T09:22:20Z] [0m
[2021-07-25T09:22:20Z] 
[2021-07-25T09:22:20Z] 
[2021-07-25T09:22:20Z] [2K[1G[31merror[39m Command failed with exit code 1.
[2021-07-25T09:22:20Z] [2K[1G[34minfo[39m Visit [1mhttps://yarnpkg.com/en/docs/cli/run[22m for documentation about this command.
[2021-07-25T09:22:20Z] make[1]: *** [Makefile:603: test-remote] Error 1
[2021-07-25T09:22:20Z] make[1]: Leaving directory '/build'
[2021-07-25T09:22:20Z] ++ EXITCODE_MAKE_TESTREMOTE=2
[2021-07-25T09:22:20Z] ++ set -e
[2021-07-25T09:22:20Z] ++ echo '--- Exit status of make test-remote: 2'
```

**Comment by jgehrcke** [comment]
```
[2021-07-25T05:08:50Z] 2021-07-25T05:08:50.049Z [32minfo[39m: Cortex query parameters (query string):
[2021-07-25T05:08:50Z] query=process_cpu_seconds_total%7Bcontainer%3D%22ingester%22%2C+namespace%3D%22cortex%22%7D&start=1627186130&end=1627193330&step=1
[2021-07-25T05:08:50Z] 2021-07-25T05:08:50.050Z [32minfo[39m: Waiting for query to return a match, deadline in 30s
[2021-07-25T05:08:50Z] 2021-07-25T05:08:50.050Z [32minfo[39m: read token from /tmp/opstrace-bk-2728-a0fb5b7-1-aws/tenant-api-token-system
[2021-07-25T05:11:53Z] 2021-07-25T05:11:53.155Z [32minfo[39m: waitForQueryResult() loop: http request failed: Timeout awaiting 'request' for 60000ms -- ignore, proceed with next iteration
[2021-07-25T05:11:53Z] 2021-07-25T05:11:53.155Z [31merror[39m: Reached 30s deadline, giving up
[2021-07-25T05:11:53Z]   [31m  2) check if container metrics exist[0m
```
main-test-aws on https://buildkite.com/opstrace/scheduled-main-builds/builds/2728

**Comment by nickbp** [comment]
Not seen since late July
