### ISSUE TITLE
ci instability: dd_api_run_agent_container_query_sysuptime ... Expectation not fulfilled within 30 s

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1106]
```
[2021-07-25T13:12:30Z] 
[2021-07-25T13:12:30Z]   2) DD API test suite
[2021-07-25T13:12:30Z]        dd_api_run_agent_container_query_sysuptime:
[2021-07-25T13:12:30Z]      Error: Expectation not fulfilled within 30 s
[2021-07-25T13:12:30Z]       at Object.waitForQueryResult (testutils/index.ts:931:9)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2730#742bc765-3134-4144-9d7a-188edb5b6681/1907-5135

```
[2021-07-25T12:53:32Z]
[2021-07-25T12:53:32Z] 2021-07-25T12:53:32.780Z info: Cortex query parameter (object):
[2021-07-25T12:53:32Z] {
[2021-07-25T12:53:32Z]   "end": "1627218177",
[2021-07-25T12:53:32Z]   "query": "system_uptime{job=\"ddagent\", type=\"gauge\"}",
[2021-07-25T12:53:32Z]   "start": "1627214877",
[2021-07-25T12:53:32Z]   "step": "60s"
[2021-07-25T12:53:32Z] }
[2021-07-25T12:53:32Z] 2021-07-25T12:53:32.780Z info: Cortex query parameters (query string):
[2021-07-25T12:53:32Z] query=system_uptime%7Bjob%3D%22ddagent%22%2C+type%3D%22gauge%22%7D&start=1627214877&end=1627218177&step=60s
[2021-07-25T12:53:32Z] 2021-07-25T12:53:32.780Z info: Waiting for query to return a match, deadline in 30s
[2021-07-25T12:53:32Z] 2021-07-25T12:53:32.780Z info: read token from /tmp/opstrace-bk-2730-a0fb5b7-1-gcp/tenant-api-token-default
[2021-07-25T12:56:36Z] 2021-07-25T12:56:36.048Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'request' for 60000ms -- ignore, proceed with next iteration
[2021-07-25T12:56:36Z] 2021-07-25T12:56:36.048Z error: Reached 30s deadline, giving up
[2021-07-25T12:56:36Z]     2) dd_api_run_agent_container_query_sysuptime
```

**Comment by jgehrcke** [comment]
another one of these: https://github.com/opstrace/opstrace/issues/1103#issuecomment-886452492

**Comment by jgehrcke** [comment]
```
[2021-07-25T01:05:36Z] 
[2021-07-25T01:05:36Z] [0m  1) DD API test suite
[2021-07-25T01:05:36Z]        dd_api_run_agent_container_query_sysuptime:
[2021-07-25T01:05:36Z] [0m[31m     Error: Expectation not fulfilled within 30 s[0m[90m
[2021-07-25T01:05:36Z]       at Object.waitForQueryResult (testutils/index.ts:931:9)
[2021-07-25T01:05:36Z]       at runMicrotasks (<anonymous>)
[2021-07-25T01:05:36Z]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-07-25T01:05:36Z]       at Context.<anonymous> (test_dd.ts:350:25)
[2021-07-25T01:05:36Z] [0m
[2021-07-25T01:05:36Z] 
[2021-07-25T01:05:36Z] 
```
main-test-aws on 


https://buildkite.com/opstrace/scheduled-main-builds/builds/2727

**Comment by nickbp** [comment]
Not seen since late July
