### ISSUE TITLE
ci instability: test-remote: waitForQueryResult() loop takes three minutes, fails with `Timeout awaiting 'request'`

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1107]
```
[2021-07-25T05:05:43Z] 2021-07-25T05:05:43.916Z [32minfo[39m: Waiting for query to return a match, deadline in 30s
[2021-07-25T05:05:43Z] 2021-07-25T05:05:43.916Z [32minfo[39m: read token from /tmp/opstrace-bk-2728-a0fb5b7-1-aws/tenant-api-token-default
[2021-07-25T05:08:46Z] 2021-07-25T05:08:46.961Z [32minfo[39m: waitForQueryResult() loop: http request failed: Timeout awaiting 'request' for 60000ms -- ignore, proceed with next iteration
[2021-07-25T05:08:46Z] 2021-07-25T05:08:46.961Z [31merror[39m: Reached 30s deadline, giving up
[2021-07-25T05:08:47Z]   [31m  1) dummyseries short write, smoke read[0m
```
(main-test-aws on https://buildkite.com/opstrace/scheduled-main-builds/builds/2728)

seen this pattern on 

https://github.com/opstrace/opstrace/issues/1103
https://github.com/opstrace/opstrace/issues/1102
https://github.com/opstrace/opstrace/issues/1105

**Comment by jgehrcke** [comment]
Initial diagnosis / speculation: looks like the timeout settings were not respected and a certain 'default' timeout hit in (as of log msgs: three minutes). That in turn leads to only _one_ iteration in this query loop, being much longer than the overall desired runtime of the loop (~30 s).

What changed?

**Comment by jgehrcke** [comment]
```
[2021-07-26T12:51:36Z]   1) Prometheus remote_write (push to opstrace cluster) tests
[2021-07-26T12:51:36Z]        dummyseries short write, smoke read:
[2021-07-26T12:51:36Z]      Error: Expectation not fulfilled within 30 s
[2021-07-26T12:51:36Z]       at Object.waitForQueryResult (testutils/index.ts:931:9)
[2021-07-26T12:51:36Z]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-07-26T12:51:36Z]       at Context.<anonymous> (test_prom_remote_write.ts:115:25)
[2021-07-26T12:51:36Z] 
[2021-07-26T12:51:36Z]   2) system metrics test suite
[2021-07-26T12:51:36Z]        check if container metrics exist:
[2021-07-26T12:51:36Z]      Error: Expectation not fulfilled within 30 s
[2021-07-26T12:51:36Z]       at Object.waitForQueryResult (testutils/index.ts:931:9)
[2021-07-26T12:51:36Z]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-07-26T12:51:36Z]       at Context.<anonymous> (tes
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2736#d3bff7f4-60ec-4f94-bfd2-6be522c84b73/1443-5116

**Comment by jgehrcke** [comment]
Have not seen this in a while now. closing for now.
