### ISSUE TITLE
test_submit_cortex_runtime_config: RequestError: read ECONNRESET

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1109]
```
[2021-07-26T14:56:15Z]   1) test_ui_api
[2021-07-26T14:56:15Z]        test_submit_cortex_runtime_config:
[2021-07-26T14:56:15Z]      RequestError: read ECONNRESET
[2021-07-26T14:56:15Z]       at ClientRequest.<anonymous> (/build/node_modules/got/dist/source/core/index.js:956:111)
[2021-07-26T14:56:15Z]       at Object.onceWrapper (node:events:514:26)
[2021-07-26T14:56:15Z]       at ClientRequest.emit (node:events:406:35)
[2021-07-26T14:56:15Z]       at ClientRequest.emit (node:domain:470:12)
[2021-07-26T14:56:15Z]       at ClientRequest.origin.emit (/build/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
[2021-07-26T14:56:15Z]       at TLSSocket.socketErrorListener (node:_http_client:447:9)
[2021-07-26T14:56:15Z]       at TLSSocket.emit (node:events:394:28)
[2021-07-26T14:56:15Z]       at TLSSocket.emit (node:domain:470:12)
[2021-07-26T14:56:15Z]       at emitErrorNT (node:internal/streams/destroy:157:8)
[2021-07-26T14:56:15Z]       at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[2021-07-26T14:56:15Z]       at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2021-07-26T14:56:15Z]       at TLSWrap.onStreamRead (node:internal/stream_base_commons:211:20)
```

https://buildkite.com/opstrace/prs/builds/5168#73e893d4-267d-4f2b-be7d-c48fa891bb99/6375-6897

This is a sad stack trace because it does not tell us which of _our_ code actually ran.

**Comment by jgehrcke** [comment]
based on reading code, this is gladly unambiguous. it's this request: https://github.com/opstrace/opstrace/blob/8f5b008ede7639d55ab54876ad907c5bc269c966/test/test-remote/test_ui_api.ts#L481

**Comment by nickbp** [comment]
The above PR looks like it improved the logging situation, maybe repros of the underlying problem got reported separately? In any case this issue only has once sample from July
