### ISSUE TITLE
ci instability: test-browser:  net::ERR_NETWORK_CHANGED 

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1121]
Carried over from
https://github.com/opstrace/opstrace/issues/340#issuecomment-886507914
seen in upgrade tests in https://buildkite.com/opstrace/scheduled-main-builds/builds/2727
```
[2021-07-25T01:24:53Z] �[31m  1) tests/5J8m3_tenant.spec.ts:35:3 › [Pixel-4] after auth0 authentication user can create a new Tenant �[39m
[2021-07-25T01:24:53Z] 
[2021-07-25T01:24:53Z]     Pending operations:
[2021-07-25T01:24:53Z]       - page.hover at tests/5J8m3_tenant.spec.ts:30:16
[2021-07-25T01:24:53Z] 
[2021-07-25T01:24:53Z]     page.goto: net::ERR_NETWORK_CHANGED at https://pr-upgr-bk-2727-a0f-g.opstrace.io
[2021-07-25T01:24:53Z]     =========================== logs ===========================
[2021-07-25T01:24:53Z]     navigating to "https://pr-upgr-bk-2727-a0f-g.opstrace.io", waiting until "load"
[2021-07-25T01:24:53Z]     ============================================================
[2021-07-25T01:24:53Z]     Note: use DEBUG=pw:api environment variable to capture Playwright logs.
[2021-07-25T01:24:53Z] 
[2021-07-25T01:24:53Z]     �[0m �[90m 1 |�[39m �[90m/**�[39m�[0m
[2021-07-25T01:24:53Z]     �[0m �[90m 2 |�[39m �[90m * Copyright 2021 Opstrace, Inc.�[39m�[0m
[2021-07-25T01:24:53Z]     �[0m �[90m 3 |�[39m �[90m *�[39m�[0m
[2021-07-25T01:24:53Z] 
```

This ticket is specifically about `net::ERR_NETWORK_CHANGED` **during test-browser**

**Comment by jgehrcke** [comment]
```
[2021-08-13T06:37:15Z] Running 1 test using 1 worker
[2021-08-13T06:37:48Z] ×F
[2021-08-13T06:37:48Z]
[2021-08-13T06:37:48Z]   1) [Chromium] › tests/xa2bH_authentication.spec.ts:27:3 › after auth0 authentication user should see homepage, also OPSTRACE_PLAYWRIGHT_REUSE_STATE 
[2021-08-13T06:37:48Z]
[2021-08-13T06:37:48Z]     page.goto: net::ERR_NETWORK_CHANGED at https://schedul-bk-2849-a20-g.opstracegcp.com/
[2021-08-13T06:37:48Z]     =========================== logs ===========================
[2021-08-13T06:37:48Z]     navigating to "https://schedul-bk-2849-a20-g.opstracegcp.com/", waiting until "load"
[2021-08-13T06:37:48Z]     ============================================================
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2849#a03a2729-fce2-451c-a939-69e833b5b22d/5462-5481

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2990#fe0d975c-71c0-4dc2-bfb8-d191bc9ee243/6903-6925

```
[2021-08-30T12:51:02Z]   1) [Chromium] › tests/rGYfr_authentication.spec.ts:27:3 › after auth0 authentication user should see homepage, also OPSTRACE_PLAYWRIGHT_REUSE_STATE 
[2021-08-30T12:51:02Z]
[2021-08-30T12:51:02Z]     page.goto: net::ERR_NETWORK_CHANGED at https://schedul-bk-2990-1ba-ug.opstrace.io/
[2021-08-30T12:51:02Z]     =========================== logs ===========================
[2021-08-30T12:51:02Z]     navigating to "https://schedul-bk-2990-1ba-ug.opstrace.io/", waiting until "load"
[2021-08-30T12:51:02Z]     ============================================================
[2021-08-30T12:51:02Z]
[2021-08-30T12:51:02Z]         at performLogin (/build/test/browser/utils/authentication.ts:20:14)
[2021-08-30T12:51:02Z]         at Object.test.extend.authCookies.scope [as fn] (/build/test/browser/fixtures/authenticated.ts:44:19)
[2021-08-30T12:51:02Z]
```

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/3279#0b2e4a9e-e420-40a0-9da6-ce0c77be4382/6037-6057

```
[2021-10-05T12:50:00Z]   1) [Chromium] › tests/wYzk0_authentication.spec.ts:27:3 › after auth0 authentication user should see homepage, also OPSTRACE_PLAYWRIGHT_REUSE_STATE 
[2021-10-05T12:50:00Z]
[2021-10-05T12:50:00Z]     page.goto: net::ERR_NETWORK_CHANGED at https://schedul-bk-3279-01e-ug.opstrace.io/
[2021-10-05T12:50:00Z]     =========================== logs ===========================
[2021-10-05T12:50:00Z]     navigating to "https://schedul-bk-3279-01e-ug.opstrace.io/", waiting until "load"
[2021-10-05T12:50:00Z]     ============================================================
[2021-10-05T12:50:00Z]
[2021-10-05T12:50:00Z]         at performLogin (/build/test/browser/utils/authentication.ts:20:14)
[2021-10-05T12:50:00Z]         at Object.test.extend.authCookies.scope [as fn] (/build/test/browser/fixtures/authenticated.ts:44:19)
[2021-10-05T12:50:00Z]
[2021-10-05T12:50:00Z]     Retry #1 --------------------------------------------------------------------------------------
[2021-10-05T12:50:00Z]
[2021-10-05T12:50:00Z]     page.waitForSelector: Timeout 30000ms exceeded.
[2021-10-05T12:50:00Z]     =========================== logs ===========================
[2021-10-05T12:50:00Z]     waiting for selector "text=Don't remember your password?" to be visible
[2021-10-05T12:50:00Z]     ============================================================
[2021-10-05T12:50:00Z]
[2021-10-05T12:50:00Z]         at performLogin (/build/test/browser/utils/authentication.ts:29:14)
[2021-10-05T12:50:00Z]         at Object.test.extend.authCookies.scope [as fn] (/build/test/browser/fixtures/authenticated.ts:44:13)
```
