### ISSUE TITLE
ci instability: Login did not succeed within 300 s (browser-based flow)

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1137]
```
[2021-07-29T12:57:14Z]   1) test_ui_api
[2021-07-29T12:57:14Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-29T12:57:14Z]      Error: Login did not succeed within 300 s
```

reported by @sreis here:
https://github.com/opstrace/opstrace/issues/1003#issuecomment-887923961
https://github.com/opstrace/opstrace/issues/1003#issuecomment-889165653

**Comment by jgehrcke** [comment]
what seems to happen: 
```
[2021-07-29T12:51:20Z]   pw:api waiting for selector "css=button[type=submit]" +1ms
[2021-07-29T12:51:20Z]   pw:api   selector resolved to visible <button name="submit" type="submit" aria-label="Log In" …>…</button> +2ms
[2021-07-29T12:51:20Z]   pw:api attempting click action +1ms
[2021-07-29T12:51:20Z]   pw:api   waiting for element to be visible, enabled and stable +0ms
[2021-07-29T12:51:20Z]   pw:api   element is visible, enabled and stable +20ms
[2021-07-29T12:51:20Z]   pw:api   scrolling into view if needed +0ms
[2021-07-29T12:51:20Z]   pw:api   done scrolling +1ms
[2021-07-29T12:51:20Z]   pw:api   checking that element receives pointer events at (640,551.48) +0ms
[2021-07-29T12:51:20Z]   pw:api   element does receive pointer events +3ms
[2021-07-29T12:51:20Z]   pw:api   performing click action +0ms
[2021-07-29T12:51:20Z]   pw:api   click action done +11ms
[2021-07-29T12:51:20Z]   pw:api   waiting for scheduled navigations to finish +0ms
[2021-07-29T12:51:20Z]   pw:api   navigations have finished +0ms
[2021-07-29T12:51:20Z]   pw:api <= page.click succeeded +1ms
[2021-07-29T12:51:20Z]   pw:api => page.waitForSelector started +0ms
[2021-07-29T12:51:20Z]   pw:api waiting for selector "text=Getting Started" to be visible +0ms
[2021-07-29T12:51:21Z]   pw:api   navigated to "https://pr-upgr-bk-2757-f72-g.opstrace.io/login?code=slrWXo1NzS-WJ8dJ&state=NVphYi5XeEYyLk8xWUpmSGdEVU5pYi1GX3VMaVRKWVdLUDY5TXZ%2BLjQwTg%3D%3D" +1s
[2021-07-29T12:51:21Z]   pw:api   "domcontentloaded" event fired +179ms
[2021-07-29T12:51:21Z]   pw:api   "load" event fired +11ms
[2021-07-29T12:51:23Z]   pw:api   "networkidle" event fired +2s
[2021-07-29T12:52:20Z]   pw:api <= page.waitForSelector failed +57s
[2021-07-29T12:52:20Z] 2021-07-29T12:52:20.409Z info: page.screenshot() because of what seems to be a playwright err: TimeoutError: page.waitForSelector: Timeout 60000ms exceeded.
```
the next retry actually does not show the login button anymore, but moves right away to `getting started` which the routine is not prepared for.

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2774#8428e1a2-3f89-4a82-9df5-660cad39e325/5816-6139

```
[2021-08-01T08:58:20Z]   1) test_ui_api
[2021-08-01T08:58:20Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-08-01T08:58:20Z]      Error: Login did not succeed within 300 s
[2021-08-01T08:58:20Z]       at performLoginFlowWithRetry (test_ui_api.ts:198:13)
[2021-08-01T08:58:20Z]       at Context.<anonymous> (test_ui_api.ts:266:5)
```

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2776#7f8b3cfd-080f-4f53-aebf-3313d2642d2b/4852-5144

```
[2021-08-01T16:49:22Z]   1) test_ui_api
[2021-08-01T16:49:22Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-08-01T16:49:22Z]      Error: Login did not succeed within 300 s
[2021-08-01T16:49:22Z]       at performLoginFlowWithRetry (test_ui_api.ts:198:13)
[2021-08-01T16:49:22Z]       at Context.<anonymous> (test_ui_api.ts:266:5)
```

**Comment by jgehrcke** [comment]
another occurrence: https://github.com/opstrace/opstrace/issues/1003#issuecomment-891025842

**Comment by jgehrcke** [comment]
another occurrence: https://github.com/opstrace/opstrace/issues/1003#issuecomment-889165653

**Comment by jgehrcke** [comment]
A little bit of debugging based on scheduled build 2776.

`tmp/opstrace-bk-2776-a903c6c-1-gcp/bk-artifacts/uishot-login-err-attempt-1.png` shows

![image](https://user-images.githubusercontent.com/265630/127875688-e77ca50b-f501-4cdb-907e-0bcac4a46ad5.png).

This is highly interesting, and probably a wrong and misleading error message, because subsequently we see that the login actually _did_ succeed:

`tmp/opstrace-bk-2776-a903c6c-1-gcp/bk-artifacts/uishot-login-err-attempt-3.png`:

![image](https://user-images.githubusercontent.com/265630/127875914-1b13ba3a-4f2d-41e9-af32-708fd991f547.png)

**Comment by jgehrcke** [comment]
Do we translate a rate limiting error seen in the backend (relying party) into an 'unauthorized' error shown in the UI? That would be an error handling bug of the mean kind.

**Comment by jgehrcke** [comment]
This is a gold mine.

I query for `{opstrace_cluster_name="schedul-bk-2776-a90-g", k8s_container_name="opstrace-application"}`.

The `submit` action of course triggers a complex flow through Auth0. By the end of that flow, JS code by Auth0 emits a POST request to our express app. With the help of timestamp precision I found the 'access log line' emitted while processing this request:

![Screenshot from 2021-08-02 16-33-43](https://user-images.githubusercontent.com/265630/127878354-5359ee7c-6334-453a-908a-572abaf65656.png)

So, that POST request whose main responsibility it is to present the _access_ token freshly obtained from Auth0 to the express app was responded to with a 500 HTTP response, indicating an internal server error. That is what a web application framework does when _during request processing_ an error that is not handled by application code bubbles up to the web framework layer.

Now. What exactly happened during processing said POST request?

For access token verification, the app needs to have hands on a public key. It needs to fetch that public key from Auth0 (through HTTPS). Ideally, it already fetches it _upon app startup_, and then caches it. The next-better version is to fetch the public key during processing the first login request that needs it (which seems to be what happens here).

And as always, a remote HTTP interaction may fail. One of the common failures is that instead of getting the expected HTTP response to the JWKS request, a 5xx response may be returned. Which is what happens here:

![Screenshot from 2021-08-02 16-35-11](https://user-images.githubusercontent.com/265630/127878497-3be6603f-7298-400f-a650-f65e71efdc7d.png)

Interestingly, we see that Auth0 exposes its JWSK endpoints through Cloudflare, and of course Cloudflare may every now and then emit all those 5xx HTTP responses that a proxy may meaningfully emit. In this case, that's a 502 Bad Gateway.

**Comment by jgehrcke** [comment]
So. There's two definite bugs in our system:

* Error handling bug in the backend: the access token verification may fail with an error thrown by `jwks-rsa`. We have to expect and handle such errors. Some of them are retryable in which case we want to retry before giving up.
* Error handling bug in the frontend: when the backend emits a 500 response, do _not_ display `Unauthorized`; this is super misleading.

`jwks-rsa/lib/wrappers/request.` should of course be prepared for 5xx responses, and already do a bit of retrying under the hood. Well. Quality of libraries and such.

**Comment by jgehrcke** [comment]
Another pretty significant problem I have found while looking into the express logs is this:

![Screenshot from 2021-08-02 16-50-23](https://user-images.githubusercontent.com/265630/127880813-43606bab-5b43-4903-9f56-32f7d9bb4d85.png)

Borderline shocking:
- an HTTP request was made with Axios.
- It's unclear which request that was, and the stack trace does not go deep enough to understand that (gna!)
- It failed with a 502 response (which always needs to be expected).
- That 502 response was not expected here though, and the corresponding thrown error was not handled
- that unhandled error _crashed the HTTP server_ which had to then restart. :fire:

**Comment by jgehrcke** [comment]
```
[2021-08-02T16:39:21Z]   0 passing (6m)
[2021-08-02T16:39:21Z]   1 failing
[2021-08-02T16:39:21Z]
[2021-08-02T16:39:21Z]   1) test_ui_api
[2021-08-02T16:39:21Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-08-02T16:39:21Z]      Error: Login did not succeed within 300 s
[2021-08-02T16:39:21Z]       at performLoginFlowWithRetry (test_ui_api.ts:198:13)
[2021-08-02T16:39:21Z]       at Context.<anonymous> (test_ui_api.ts:266:5)
```
https://buildkite.com/opstrace/prs/builds/5286#0f68a032-87aa-44e2-ae79-cceb5430486b/6168-6489

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/5287#5aebaa76-567b-4b3e-9a8f-27684d498e92/1106-1387

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/prs/builds/5304#5b528b78-0574-4fda-bf92-b1e5fbefa11f/8246-8556

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2794#6f2aa7d1-dc21-4862-b620-d7b3f3a22881/5721-6032

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2794#e816e655-3fcb-466d-8d9b-b038f3aa37fb/6652-6975

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2798#41970a86-95c5-4005-8667-5ea8aad217f8/7041-7363

```
[2021-08-05T08:52:12Z]   1) test_ui_api
[2021-08-05T08:52:12Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-08-05T08:52:12Z]      Error: Login did not succeed within 300 s
[2021-08-05T08:52:12Z]       at performLoginFlowWithRetry (test_ui_api.ts:198:13)
[2021-08-05T08:52:12Z]       at Context.<anonymous> (test_ui_api.ts:266:5)
```

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/upgrade-tests/builds/1145#b6c3eaf6-f019-4ab0-ad25-a7731f60c8a0/4452-4762

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/5456#f30ad8f9-7e6b-40d1-99d8-b00e7e64677d/5652-6019
sadly, here we cannot get to the system logs. also see https://github.com/opstrace/opstrace/issues/1240.

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2835#370ce404-f22b-40bd-9508-56bdf38077db

```
[2021-08-11T09:05:12Z]   1) test_ui_api
[2021-08-11T09:05:12Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-08-11T09:05:12Z]      Error: Login did not succeed within 300 s
[2021-08-11T09:05:12Z]       at performLoginFlowWithRetry (test_ui_api.ts:198:13)
[2021-08-11T09:05:12Z]       at Context.<anonymous> (test_ui_api.ts:266:5)
```

**Comment by jgehrcke** [comment]
```
[2021-08-11T09:18:03Z]   0 passing (6m)
[2021-08-11T09:18:03Z]   1 failing
[2021-08-11T09:18:03Z]
[2021-08-11T09:18:03Z]   1) test_ui_api
[2021-08-11T09:18:03Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-08-11T09:18:03Z]      Error: Login did not succeed within 300 s
[2021-08-11T09:18:03Z]       at performLoginFlowWithRetry (test_ui_api.ts:198:13)
[2021-08-11T09:18:03Z]       at Context.<anonymous> (test_ui_api.ts:266:5)
```
https://buildkite.com/opstrace/prs/builds/5478#fcfbed08-c610-4d99-8e30-a897ad0455be/1473-1790

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2837#bf8b8f52-467f-473f-ae1c-b6ec6f3b0e10/5579-5917

Seeing this in the logs a few times:

https://buildkite.com/opstrace/scheduled-main-builds/builds/2837#bf8b8f52-467f-473f-ae1c-b6ec6f3b0e10/5579-5788

```
[2021-08-11T16:43:35Z] 2021-08-11T16:43:35.312Z info: page.screenshot() because of what seems to be a playwright err: TimeoutError: page.waitForSelector: Timeout 60000ms exceeded.
--
  | [2021-08-11T16:43:35Z] =========================== logs ===========================
  | [2021-08-11T16:43:35Z] waiting for selector "text=Getting Started" to be visible
  | [2021-08-11T16:43:35Z] ============================================================
```

And also:

https://buildkite.com/opstrace/scheduled-main-builds/builds/2837#bf8b8f52-467f-473f-ae1c-b6ec6f3b0e10/5579-5697


```
[2021-08-11T16:42:22Z]   pw:api <= page.waitForSelector failed +59s
--
  | [2021-08-11T16:42:22Z] 2021-08-11T16:42:22.033Z info: page.screenshot() because of what seems to be a playwright err: TimeoutError: page.waitForSelector: Timeout 60000ms exceeded.
  | [2021-08-11T16:42:22Z] =========================== logs ===========================
  | [2021-08-11T16:42:22Z] waiting for selector "text=Don't remember your password?" to be visible
  | [2021-08-11T16:42:22Z] ============================================================
  | [2021-08-11T16:42:22Z]   pw:api => page.screenshot started +1ms
  | [2021-08-11T16:42:22Z]   pw:api <= page.screenshot succeeded +95ms
```

**Comment by triclambert** [comment]
```
[2021-08-13T21:39:44Z]   0 passing (6m)
[2021-08-13T21:39:44Z]   1 failing
[2021-08-13T21:39:44Z]
[2021-08-13T21:39:44Z]   1) test_ui_api
[2021-08-13T21:39:44Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-08-13T21:39:44Z]      Error: Login did not succeed within 300 s
[2021-08-13T21:39:44Z]       at performLoginFlowWithRetry (test_ui_api.ts:198:13)
[2021-08-13T21:39:44Z]       at Context.<anonymous> (test_ui_api.ts:266:5)
```

```
[2021-08-13T21:39:34Z]   pw:api <= page.waitForSelector failed +59s
[2021-08-13T21:39:34Z] 2021-08-13T21:39:34.349Z info: page.screenshot() because of what seems to be a playwright err: TimeoutError: page.waitForSelector: Timeout 60000ms exceeded.
[2021-08-13T21:39:34Z] =========================== logs ===========================
[2021-08-13T21:39:34Z] waiting for selector "text=Don't remember your password?" to be visible
[2021-08-13T21:39:34Z] ============================================================
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2856#51aa21b6-bdad-442f-9609-5b4aa4e28743/4442-4785

**Comment by triclambert** [comment]
```
[2021-08-13T21:46:47Z]   0 passing (6m)
[2021-08-13T21:46:47Z]   1 failing
[2021-08-13T21:46:47Z]
[2021-08-13T21:46:47Z]   1) test_ui_api
[2021-08-13T21:46:47Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-08-13T21:46:47Z]      Error: Login did not succeed within 300 s
[2021-08-13T21:46:47Z]       at performLoginFlowWithRetry (test_ui_api.ts:198:13)
[2021-08-13T21:46:47Z]       at Context.<anonymous> (test_ui_api.ts:266:5)
```

```
[2021-08-13T21:46:37Z]   pw:api <= page.click failed +59s
[2021-08-13T21:46:37Z] 2021-08-13T21:46:37.676Z info: page.screenshot() because of what seems to be a playwright err: TimeoutError: page.click: Timeout 60000ms exceeded.
[2021-08-13T21:46:37Z] =========================== logs ===========================
[2021-08-13T21:46:37Z] waiting for selector "text=Log in"
[2021-08-13T21:46:37Z] ============================================================
```

https://buildkite.com/opstrace/upgrade-tests/builds/1193#a04f3f01-cc12-437a-bca9-28771cd96a74/1962-2283

**Comment by triclambert** [comment]
```
[2021-08-13T18:35:14Z]   0 passing (6m)
[2021-08-13T18:35:14Z]   1 failing
[2021-08-13T18:35:14Z]
[2021-08-13T18:35:14Z]   1) test_ui_api
[2021-08-13T18:35:14Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-08-13T18:35:14Z]      Error: Login did not succeed within 300 s
[2021-08-13T18:35:14Z]       at performLoginFlowWithRetry (test_ui_api.ts:198:13)
[2021-08-13T18:35:14Z]       at Context.<anonymous> (test_ui_api.ts:266:5)
```

```
[2021-08-13T18:35:04Z]   pw:api <= page.waitForSelector failed +59s
[2021-08-13T18:35:04Z] 2021-08-13T18:35:04.111Z info: page.screenshot() because of what seems to be a playwright err: TimeoutError: page.waitForSelector: Timeout 60000ms exceeded.
[2021-08-13T18:35:04Z] =========================== logs ===========================
[2021-08-13T18:35:04Z] waiting for selector "text=Don't remember your password?" to be visible
[2021-08-13T18:35:04Z] ============================================================
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2855#00f0c3ba-6184-4f1a-aa39-d7b20d23c41a/4356-4699

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2858#67447610-be1a-4abb-be50-956e8f2e3963/4423-4755

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2857#9074839f-8b88-436f-a8e5-91be3fcb585c/4416-4748

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2859#354449a4-f73b-4bf0-9fc2-a0fa3212d9f0/4351-4683

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2861#d86db46c-e8f3-476c-baca-4b906bc6833b/4452-4784

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2863#a0aa539e-a819-4fbc-b52c-293faa9f6a65/4359-4691

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2865#12d55340-2ea0-4d57-a723-f0edd08e92c8/4397-4728

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2866#6044e0a5-e9de-42bb-8ed2-5dd5c862fdbd/4415-4747

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2867#78327f97-e931-4833-b2bb-65fbf2de5002/4383-4714

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2868#d4d3e9c3-dd8a-4a73-b99f-c5a342cb1750/4458-4807

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2869#48443296-e32c-4d47-81de-fb4f336a60d0/4416-4748

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2873#908f0c9c-b7d4-4ba6-862d-0080cf4fe903/2371-2697 on AWS rather than GCP/upgrade for this one

**Comment by sreis** [comment]
```
[2021-08-18T09:45:09Z]   1) test_ui_api
[2021-08-18T09:45:09Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-08-18T09:45:09Z]      Error: Login did not succeed within 200 s
[2021-08-18T09:45:09Z]       at performLoginFlowWithRetry (test_ui_api.ts:211:13)
[2021-08-18T09:45:09Z]       at Context.<anonymous> (test_ui_api.ts:289:5)
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2893#4c1625fa-09a8-4752-8cc0-a177615a53bc/6521-6795

**Comment by jgehrcke** [comment]
```
[2021-08-18T09:41:06Z]   pw:api attempting click action +1ms
```
and then in web app:
```
	
2021-08-18T09:41:07.878546396Z stdout F {"meta":{"req":{"url":"/login?code=FxcLKmjsNOa3kek0&state=blBCY0lOdU1hNjBNTGxaaWgwS1ZONmJrck5qZkhNM1pJSWlyTktWSFdZcg%3D%3D","headers":{"host":"schedul-bk-2893-606-ug.opstrace.io","x-request-id":"730c6686d18040970ecbb8452cabd087","x-real-ip":"192.168.0.3","x-forwarded-for":"192.168.0.3","x-forwarded-host":"schedul-bk-2893-606-ug.opstrace.io","x-forwarded-port":"443","x-forwarded-proto":"https","x-scheme":"https","cache-control":"max-age=0","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/94.0.4595.0 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"cross-site","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","accept-encoding":"gzip, deflate, br"},"method":"GET","httpVersion":"1.1","originalUrl":"/login?code=FxcLKmjsNOa3kek0&state=blBCY0lOdU1hNjBNTGxaaWgwS1ZONmJrck5qZkhNM1pJSWlyTktWSFdZcg%3D%3D","query":{"code":"FxcLKmjsNOa3kek0","state":"blBCY0lOdU1hNjBNTGxaaWgwS1ZONmJrck5qZkhNM1pJSWlyTktWSFdZcg=="}},"res":{"statusCode":200},"responseTime":0},"level":"info","message":"HTTP GET /login?code=FxcLKmjsNOa3kek0&state=blBCY0lOdU1hNjBNTGxaaWgwS1ZONmJrck5qZkhNM1pJSWlyTktWSFdZcg%3D%3D"}
```

that is, the authorization code flow handed over to doing the 'fetch access token' logic in the browser. 

That is, we probably did not get past this: https://github.com/opstrace/opstrace/blob/606fa4810cdec52ff6c1314b7c7ff4151144214b/packages/app/src/client/components/withSession/index.tsx#L297

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2894#17b0b84d-9b37-40b5-a356-97fbf148ea35/2452-2725

**Comment by jgehrcke** [comment]
> My electron app is randomly redirecting to chrome-error://chromewebdata, and I've no idea why. There's no errors in the console, etc.

https://stackoverflow.com/questions/55715384/why-might-chrome-inside-electron-suddenly-redirect-to-chrome-error-chromeweb

> For some reason, your code is trying to navigate to an invalid (non-existing) URL, which then results in window.location.href being chrome-error://chromewebdata.

Huh!

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/3007#cf0ee97e-2f66-4ad9-8632-0cbf06c344f8/6147-6420

```
[2021-09-01T12:40:07Z]   pw:api waiting for selector "text=Getting Started" to be visible +1ms
[2021-09-01T12:40:08Z]   pw:api   navigated to "chrome-error://chromewebdata/" +1s
[2021-09-01T12:40:08Z]   pw:api   "load" event fired +1ms
```

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/3092#7ce98cbe-e452-40e0-8dd1-f3bd74a3fbae/4848-5121

**Comment by jgehrcke** [comment]
(something like) that happened here again: https://buildkite.com/opstrace/scheduled-main-builds/builds/3627#610ad5c1-27ff-4eb3-95e4-68818fa20a77/5662-5931

important insight: https://github.com/opstrace/opstrace/issues/1266#issuecomment-929114816 

> button never appears when first login attempt was actually successful, but cloaked as of an underlying transient issue -- need do adjust code to account for that
