### ISSUE TITLE
test_ui_api: view_ring_health: page.waitForSelector: Timeout / waiting for selector "text=less than a minute ago"

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1167]
```
[2021-08-03T08:44:12Z]   6 passing (5m)
[2021-08-03T08:44:12Z]   1 failing
[2021-08-03T08:44:12Z]
[2021-08-03T08:44:12Z]   1) test_ui_api
[2021-08-03T08:44:12Z]        view_ring_health:
[2021-08-03T08:44:12Z]      page.waitForSelector: Timeout 30000ms exceeded.
[2021-08-03T08:44:12Z] =========================== logs ===========================
[2021-08-03T08:44:12Z] waiting for selector "text=less than a minute ago" to be visible
[2021-08-03T08:44:12Z] ============================================================
[2021-08-03T08:44:12Z]       at Context.<anonymous> (test_ui_api.ts:610:20)
[2021-08-03T08:44:12Z] 
[2021-08-03T08:44:12Z]
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2786#4656c9de-944d-48ce-80a9-53e3720934be/5413-6100

**Comment by jgehrcke** [comment]
```
[2021-08-04T05:17:14Z]   6 passing (18m)
[2021-08-04T05:17:14Z]   1 failing
[2021-08-04T05:17:14Z]
[2021-08-04T05:17:14Z]   1) test_ui_api
[2021-08-04T05:17:14Z]        view_ring_health:
[2021-08-04T05:17:14Z]      page.waitForSelector: Timeout 30000ms exceeded.
[2021-08-04T05:17:14Z] =========================== logs ===========================
[2021-08-04T05:17:14Z] waiting for selector "text=less than a minute ago" to be visible
[2021-08-04T05:17:14Z] ============================================================
[2021-08-04T05:17:14Z]       at Context.<anonymous> (test_ui_api.ts:610:20)
[2021-08-04T05:17:14Z] 
```

**Comment by nickbp** [comment]
Only had two samples a day apart from each other, guessing it was a weird flake or maybe something changed
