### ISSUE TITLE
ui api: emits 500 resp instead of 401 when seeing a login request with bad authorization header

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1191]
```
2021-08-05T15:01:41.499Z error: Format is Authorization: Bearer [token]: UnauthorizedError: Format is Authorization: Bearer [token]
    at middleware (/home/jp/dev/opstrace/packages/app/home/jp/dev/opstrace/node_modules/express-jwt/lib/index.js:73:1)
    at Layer.handle [as handle_request] (/home/jp/dev/opstrace/packages/app/home/jp/dev/opstrace/node_modules/express/lib/router/layer.js:95:1)
    at next (/home/jp/dev/opstrace/packages/app/home/jp/dev/opstrace/node_modules/express/lib/router/route.js:137:1)
    at Route.dispatch (/home/jp/dev/opstrace/packages/app/home/jp/dev/opstrace/node_modules/express/lib/router/route.js:112:1)
    at Layer.handle [as handle_request] (/home/jp/dev/opstrace/packages/app/home/jp/dev/opstrace/node_modules/express/lib/router/layer.js:95:1)
    at /home/jp/dev/opstrace/packages/app/home/jp/dev/opstrace/node_modules/express/lib/router/index.js:281:1
    at Function.process_params (/home/jp/dev/opstrace/packages/app/home/jp/dev/opstrace/node_modules/express/lib/router/index.js:335:1)
    at next (/home/jp/dev/opstrace/packages/app/home/jp/dev/opstrace/node_modules/express/lib/router/index.js:275:1)
    at Function.handle (/home/jp/dev/opstrace/packages/app/home/jp/dev/opstrace/node_modules/express/lib/router/index.js:174:1)
    at router (/home/jp/dev/opstrace/packages/app/home/jp/dev/opstrace/node_modules/express/lib/router/index.js:47:1)
{"meta":{"req":{"url":"/_/auth/session","headers":{"host":"localhost:3001","user-agent":"curl/7.76.1","accept":"*/*","authorization":"eyJhbGciO-snip-uY29tL3VzZXJpbmZvIl0sImlhdCI6MTYyODE3NTUzNywiZXhwIjoxNjI4MjYxOTM3LCJhenAiOiJ2czZiZ1R1bmJWSzRkdmRMUmowMkRwdFdqT21BVldWTSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.qLIksd53PpzuMJM2XcCRX5ZMB0aaoZJETMTs30q502tmXP-mYn-LHmb7AHjsA1ROY6IclP6kf96aPDm5EcJmQBEZ61_LMQdMHj1MAu3cfE5dBbDvXQjp46C5Kuey3S8lgDhLptiQ1LyICgOD-_XmZSWz2oWwWrHHzIiZqjpDn91karz4XGKCclnltZD32w15hie0Va66JMulrGzFlrqRDiJU2bwePQYj9WbseYbTdyw5R_7yftO14FZUpwljKhqeKCaaGopIwrLqM9-N57sXRU8U7KY6cEi938tyjtMIxqVqnJxkU09L7xS5NzEe4__7ULRuq76jE6QwL7pzYqH66w"},"method":"POST","httpVersion":"1.1","originalUrl":"/_/auth/session","query":{}},"res":{"statusCode":500},"responseTime":3},"level":"info","message":"HTTP POST /_/auth/session"}
```

**Comment by jgehrcke** [comment]
the `,"res":{"statusCode":500}` in the above's excerpt is critical here
