### ISSUE TITLE
ci-instability: Chromium|Firefox|WebKit: cluster health all Cortext Ring Health tabs should render

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1235]
**Describe the bug**

Three tests failed in both the AWS and GCP builds.

```
[2021-08-10T05:57:33Z]   3 failed
[2021-08-10T05:57:33Z]     [Chromium] › tests/N9mQo_clusterHealth.spec.ts:27:3 › cluster health all Cortext Ring Health tabs should render 
[2021-08-10T05:57:33Z]     [Firefox] › tests/N9mQo_clusterHealth.spec.ts:27:3 › cluster health all Cortext Ring Health tabs should render 
[2021-08-10T05:57:33Z]     [WebKit] › tests/N9mQo_clusterHealth.spec.ts:27:3 › cluster health all Cortext Ring Health tabs should render 
```

Error stack traces include one occurrence of the following which I'm not sure if it's related to #990 or not. 

```
[2021-08-10T05:57:33Z]     Pending operations:
[2021-08-10T05:57:33Z]       - page.waitForSelector at utils/authentication.ts:54:16
[2021-08-10T05:57:33Z]
[2021-08-10T05:57:33Z]     page.waitForSelector: Protocol error (Runtime.callFunctionOn): Target closed.
[2021-08-10T05:57:33Z]     =========================== logs ===========================
[2021-08-10T05:57:33Z]     waiting for selector "[data-test=getting-started]" to be visible
[2021-08-10T05:57:33Z]     ============================================================
[2021-08-10T05:57:33Z]
[2021-08-10T05:57:33Z]         at restoreLogin (/build/test/browser/utils/authentication.ts:54:16)
[2021-08-10T05:57:33Z]         at WorkerRunner._runHooks (/build/test/browser/node_modules/@playwright/test/lib/test/workerRunner.js:439:9)
[2021-08-10T05:57:33Z]         at WorkerRunner._runTestWithBeforeHooks (/build/test/browser/node_modules/@playwright/test/lib/test/workerRunner.js:375:7)
```

The following error stack trace appears in all the test failures, this seems to be a new symptom.

```
[2021-08-10T05:57:33Z]     Pending operations:
[2021-08-10T05:57:33Z]       - page.click at tests/N9mQo_clusterHealth.spec.ts:40:18
[2021-08-10T05:57:33Z]
[2021-08-10T05:57:33Z]     page.click: Protocol error (Runtime.callFunctionOn): The page has been closed.
[2021-08-10T05:57:33Z]     =========================== logs ===========================
[2021-08-10T05:57:33Z]     waiting for selector "[data-test='ringHealth/tab/Ingester']"
[2021-08-10T05:57:33Z]     ============================================================
```

https://buildkite.com/opstrace/upgrade-tests/builds/1167

**Comment by nickbp** [comment]
Only seen one instance in mid-August, may have been fixed in the UI?
