### ISSUE TITLE
ci-instability: test_grafana_datasource_proxy_loki_get_rules failed: status: 400: NoSuchBucket: The specified bucket does not exist

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1244]
**Describe the bug**

https://buildkite.com/opstrace/upgrade-tests/builds/1169#302ab596-69dc-4784-a10b-dfe1e1ff8edd

```
[2021-08-10T14:20:28Z]   1) test_ui_api
[2021-08-10T14:20:28Z]        test_grafana_datasource_proxy_loki_get_rules:
[2021-08-10T14:20:28Z]      Error: Expectation not fulfilled within 2100 s
[2021-08-10T14:20:28Z]       at waitForResp (test_ui_api.ts:157:13)
[2021-08-10T14:20:28Z]       at Context.<anonymous> (test_ui_api.ts:352:18)
```

```
[2021-08-10T14:13:51Z] 2021-08-10T14:13:51.133Z [32minfo[39m: HTTP resp to GET(https://system.upgrade-bk-1169-d5a-a.opstrace.io/grafana/api/datasources/proxy/2/loki/api/v1/rules):
[2021-08-10T14:13:51Z]   status: 400
[2021-08-10T14:13:51Z]   body[:500]: NoSuchBucket: The specified bucket does not exist
[2021-08-10T14:13:51Z] 	status code: 404, request id: YRZ4JWHJPZJY3W4Z, host id: KQv+C9fMyCxFq8w1hAvWVYswqX8N0Ad06yumBEb1gec59dR4FfsyMv+D4+w30Up/B74Yt5UAKOA=
[2021-08-10T14:13:51Z] 
[2021-08-10T14:13:51Z]   headers: {"date":"Tue, 10 Aug 2021 14:13:51 GMT","content-type":"text/plain; charset=utf-8","content-length":"185","connection":"close","x-content-type-options":"nosniff","x-xss-protection":"1; mode=block","strict-transport-security":"max-age=15724800; includeSubDomains","access-control-allow-origin":"https://upgrade-bk-1169-d5a-a.opstrace.io","access-control-allow-credentials":"true"}
[2021-08-10T14:13:51Z]   totalTime: 0.088 s
[2021-08-10T14:13:51Z]   dnsDone->TCPconnectDone: 0.002 s
[2021-08-10T14:13:51Z]   connectDone->reqSent 0 s
[2021-08-10T14:13:51Z]   reqSent->firstResponseByte: 0.085 s
[2021-08-10T14:13:51Z]   
[2021-08-10T14:13:51Z] 2021-08-10T14:13:51.133Z [32minfo[39m: outer retry: try again in 10 s
[2021-08-10T14:14:01Z] 2021-08-10T14:14:01.255Z [32minfo[39m: HTTP resp to GET(https://system.upgrade-bk-1169-d5a-a.opstrace.io/grafana/api/datasources/proxy/2/loki/api/v1/rules):
[2021-08-10T14:14:01Z]   status: 400
[2021-08-10T14:14:01Z]   body[:500]: NoSuchBucket: The specified bucket does not exist
[2021-08-10T14:14:01Z] 	status code: 404, request id: 39CCPV0ETZ325JKH, host id: KxiYJlWDrOVOCrO56UnSLSWxLCU+FXxzPMzrfX+sM+M2bGWqMT7fHz4OSrYTSEq93VULeYhskmA=
[2021-08-10T14:14:01Z] 
[2021-08-10T14:14:01Z]   headers: {"date":"Tue, 10 Aug 2021 14:14:01 GMT","content-type":"text/plain; charset=utf-8","content-length":"185","connection":"close","x-content-type-options":"nosniff","x-xss-protection":"1; mode=block","strict-transport-security":"max-age=15724800; includeSubDomains","access-control-allow-origin":"https://upgrade-bk-1169-d5a-a.opstrace.io","access-control-allow-credentials":"true"}
[2021-08-10T14:14:01Z]   totalTime: 0.12 s
[2021-08-10T14:14:11Z]   [31m  1) test_grafana_datasource_proxy_loki_get_rules[0m

```

**Comment by nickbp** [comment]
This looks like a duplicate of #1231. Will post updates into that ticket since there's some analysis from the prior failure there already.
