### ISSUE TITLE
ci instability: looker fails with reason: 'entry out of order'

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1263]
```
2021-08-12T12:50:17.313Z [32minfo[39m: cycle 4: entering write phase
2021-08-12T12:50:17.313Z [32minfo[39m: mark all streams to keep track of validation info: no --skip-read, and no --read-n-streams-only
2021-08-12T12:50:17.313Z [32minfo[39m: re-labeling series for validation info collection took 0.00 s
2021-08-12T12:50:17.313Z [32minfo[39m: create 3 pushrequestProducerAndPOSTer()
2021-08-12T12:51:22.342Z [31mwarning[39m: POST PushRequest(md5=84016addf762d53bfc6e258a93c53574): attempt 1: transient problem: Timeout awaiting 'request' for 60000ms
2021-08-12T12:51:22.343Z [32minfo[39m: POST PushRequest(md5=84016addf762d53bfc6e258a93c53574): schedule to perform attempt 2 in 1.60 s
2021-08-12T12:51:24.318Z [32minfo[39m: HTTP resp to POST(https://loki.default.schedul-bk-2842-84d-g.opstracegcp.com/loki/api/v1/push (PushRequest(md5=84016addf762d53bfc6e258a93c53574))):
    status: 400
    body[:500]: entry with timestamp 2021-08-12 12:49:43.120025 +0000 UTC ignored, reason: 'entry out of order' for stream: {looker_uniquename="looker-VeQalwMYe5-4-3"},
entry with timestamp 2021-08-12 12:49:43.120025001 +0000 UTC ignored, reason: 'entry out of order' for stream: {looker_uniquename="looker-VeQalwMYe5-4-3"},
entry with timestamp 2021-08-12 12:49:43.120025002 +0000 UTC ignored, reason: 'entry out of order' for stream: {looker_uniquename="looker-VeQalwMYe5-4-3"},
entry with timestamp 2021-08-12 12:
    headers: {"date":"Thu, 12 Aug 2021 12:51:24 GMT","content-type":"text/plain; charset=utf-8","transfer-encoding":"chunked","connection":"close","x-content-type-options":"nosniff","strict-transport-security":"max-age=15724800; includeSubDomains"}
    totalTime: 0.374 s
    dnsDone->TCPconnectDone: 0.031 s
    connectDone->reqSent 0.063 s
    reqSent->firstResponseByte: 0.04 s
    
2021-08-12T12:51:24.320Z [31mcrit[39m: consider critical: Error: POST PushRequest(md5=84016addf762d53bfc6e258a93c53574): Bad HTTP request (see log above)
    at customPostWithRetryOrError (/build/_tscbuild/index.js:750:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _genAndPost (/build/_tscbuild/index.js:557:13)
    at async _produceAndPOSTpushrequest (/build/_tscbuild/index.js:586:9)
    at async pushrequestProducerAndPOSTer (/build/_tscbuild/index.js:616:9)
    at async Promise.all (index 2)
    at async generateAndPostFragments (/build/_tscbuild/index.js:448:5)
    at async writePhase (/build/_tscbuild/index.js:275:5)
    at async performWriteReadCycle (/build/_tscbuild/index.js:206:24)
```
from 
https://buildkite.com/opstrace/scheduled-main-builds/builds/2842
`tmp/builddir-schedul-bk-2842-84d-g/bk-artifacts/looker-20210812-124906.log`

Typical case of first attempt succeded w/o receiving success response, second attempt failed with out-of-order.

Need more of this strategy: https://github.com/opstrace/opstrace/blob/84dcc34ce92bb8d35172d19d8b9090e107e7c36f/test/test-remote/looker/src/index.ts#L961

not just upon 5xx responses but also upon request/response timeout as seen here.

**Comment by nickbp** [comment]
Per above #1328 it sounds like this has been fixed in looker
