### ISSUE TITLE
ci instability: test-browser: _authentication.spec.ts: timeout during waiting for selector "css=button" to be visible

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1266]
```
[2021-08-12T14:33:45Z] Running 1 test using 1 worker
[2021-08-12T14:34:47Z] ×F
[2021-08-12T14:34:47Z]
[2021-08-12T14:34:47Z]   1) [Chromium] › tests/gSdb5_authentication.spec.ts:27:3 › after auth0 authentication user should see homepage, also OPSTRACE_PLAYWRIGHT_REUSE_STATE 
[2021-08-12T14:34:47Z]
[2021-08-12T14:34:47Z]     page.waitForSelector: Timeout 30000ms exceeded.
[2021-08-12T14:34:47Z]     =========================== logs ===========================
[2021-08-12T14:34:47Z]     waiting for selector "css=button" to be visible
[2021-08-12T14:34:47Z]     ============================================================
[2021-08-12T14:34:47Z]
[2021-08-12T14:34:47Z]         at performLogin (/build/test/browser/utils/authentication.ts:24:14)
[2021-08-12T14:34:47Z]         at Object.test.extend.authCookies.scope [as fn] (/build/test/browser/fixtures/authenticated.ts:44:13)
[2021-08-12T14:34:47Z]
[2021-08-12T14:34:47Z]     Retry #1 --------------------------------------------------------------------------------------
[2021-08-12T14:34:47Z]
[2021-08-12T14:34:47Z]     page.waitForSelector: Timeout 30000ms exceeded.
[2021-08-12T14:34:47Z]     =========================== logs ===========================
[2021-08-12T14:34:47Z]     waiting for selector "css=button" to be visible
[2021-08-12T14:34:47Z]     ============================================================
[2021-08-12T14:34:47Z]
[2021-08-12T14:34:47Z]         at performLogin (/build/test/browser/utils/authentication.ts:24:14)
[2021-08-12T14:34:47Z]         at Object.test.extend.authCookies.scope [as fn] (/build/test/browser/fixtures/authenticated.ts:44:13)
[2021-08-12T14:34:47Z]
[2021-08-12T14:34:47Z]   Slow test: [Chromium] › tests/gSdb5_authentication.spec.ts (1m)
[2021-08-12T14:34:47Z]
[2021-08-12T14:34:47Z]   1 failed
[2021-08-12T14:34:47Z]     [Chromium] › tests/gSdb5_authentication.spec.ts:27:3 › after auth0 authentication user should see homepage, also OPSTRACE_PLAYWRIGHT_REUSE_STATE 
```

https://buildkite.com/opstrace/prs/builds/5524#75ae40d5-7036-473e-84d6-495511aab7ca/6297-6317

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2873#04cd3845-b186-4d66-b1f4-ee061dabaae0/6150-6170

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2869#48443296-e32c-4d47-81de-fb4f336a60d0/4799-4819

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2868#d4d3e9c3-dd8a-4a73-b99f-c5a342cb1750/4859-4879

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2867#78327f97-e931-4833-b2bb-65fbf2de5002/4765-4785

**Comment by jgehrcke** [comment]
> meanwhile these tests (possibly among others) have both this failure as well as #1137:

coarse-grained view: all CI failures of last weekend in an upgrade test that have to do with login are extremely likely as of  https://github.com/opstrace/opstrace/issues/1274 -- a misconfiguration of the auth0 parameters.

In all the build logs you have linked here I think I saw `waiting for selector "text=Don't remember your password?" to be visible` which corresponds to said misconfig.

I have a close look at login failures in non-upgrade tests.

**Comment by jgehrcke** [comment]
Capturing this here:
```
[2021-08-16T21:54:49Z]   1) [Chromium] › tests/7LB5X_authentication.spec.ts:27:3 › after auth0 authentication user should see homepage, also OPSTRACE_PLAYWRIGHT_REUSE_STATE 
[2021-08-16T21:54:49Z]
[2021-08-16T21:54:49Z]     page.waitForSelector: Timeout 30000ms exceeded.
[2021-08-16T21:54:49Z]     =========================== logs ===========================
[2021-08-16T21:54:49Z]     waiting for selector "text=Don't remember your password?" to be visible
[2021-08-16T21:54:49Z]     ============================================================
[2021-08-16T21:54:49Z]
[2021-08-16T21:54:49Z]         at performLogin (/build/test/browser/utils/authentication.ts:29:14)
[2021-08-16T21:54:49Z]         at Object.test.extend.authCookies.scope [as fn] (/build/test/browser/fixtures/authenticated.ts:44:13)
[2021-08-16T21:54:49Z]
[2021-08-16T21:54:49Z]     Retry #1 --------------------------------------------------------------------------------------
[2021-08-16T21:54:49Z]
[2021-08-16T21:54:49Z]     page.waitForSelector: Timeout 30000ms exceeded.
[2021-08-16T21:54:49Z]     =========================== logs ===========================
[2021-08-16T21:54:49Z]     waiting for selector "css=button" to be visible
[2021-08-16T21:54:49Z]     ============================================================
[2021-08-16T21:54:49Z]
[2021-08-16T21:54:49Z]         at performLogin (/build/test/browser/utils/authentication.ts:24:14)
[2021-08-16T21:54:49Z]         at Object.test.extend.authCookies.scope [as fn] (/build/test/browser/fixtures/authenticated.ts:44:13)
[2021-08-16T21:54:49Z]
[2021-08-16T21:54:49Z]   Slow test: [Chromium] › tests/7LB5X_authentication.spec.ts (1m)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2881#749d767c-7df2-4368-87e8-a0b39a18e7ba/6790-6830

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2897#bd0fffa9-c702-4f16-a00c-8390d26f7602/6313-6333

**Comment by jgehrcke** [comment]
```
[2021-09-14T06:46:54Z]     Retry #1 --------------------------------------------------------------------------------------
[2021-09-14T06:46:54Z]
[2021-09-14T06:46:54Z]     page.waitForSelector: Timeout 30000ms exceeded.
[2021-09-14T06:46:54Z]     =========================== logs ===========================
[2021-09-14T06:46:54Z]     waiting for selector "text=Don't remember your password?" to be visible
[2021-09-14T06:46:54Z]     ============================================================
[2021-09-14T06:46:54Z]
[2021-09-14T06:46:54Z]         at performLogin (/build/test/browser/utils/authentication.ts:29:14)
[2021-09-14T06:46:54Z]         at Object.test.extend.authCookies.scope [as fn] (/build/test/browser/fixtures/authenticated.ts:44:13)
[2021-09-14T06:46:54Z]
[2021-09-14T06:46:54Z]   Slow test: [Chromium] › tests/bvftC_authentication.spec.ts (1m)
[2021-09-14T06:46:54Z]
[2021-09-14T06:46:54Z]   1 failed
[2021-09-14T06:46:54Z]     [Chromium] › tests/bvftC_authentication.spec.ts:27:3 › after auth0 authentication user should see homepage, also OPSTRACE_PLAYWRIGHT_REUSE_STATE 
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/3109#3531b43d-a627-4566-aca1-68211d162940/2816-2846

**Comment by jgehrcke** [comment]
```
[2021-09-14T21:38:15Z]   1) [Chromium] › tests/vPI69_authentication.spec.ts:27:3 › after auth0 authentication user should see homepage, also OPSTRACE_PLAYWRIGHT_REUSE_STATE 
[2021-09-14T21:38:15Z]
[2021-09-14T21:38:15Z]     page.waitForSelector: Timeout 30000ms exceeded.
[2021-09-14T21:38:15Z]     =========================== logs ===========================
[2021-09-14T21:38:15Z]     waiting for selector "text=Don't remember your password?" to be visible
[2021-09-14T21:38:15Z]     ============================================================
[2021-09-14T21:38:15Z]
[2021-09-14T21:38:15Z]         at performLogin (/build/test/browser/utils/authentication.ts:29:14)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/3114#8e11748e-d617-4ad3-94fd-20c6cedd295e/5473-5493

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/3210#b84cafdb-ac41-4448-a086-68a46415cf12/6082-6102

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/3222#e5dcaae1-fa30-42d6-bf8a-4d416b15bf09/6257-6277
