### ISSUE TITLE
ci instability: End-to-end alert tests: Expectation not fulfilled within 90 s

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1277]
```
[2021-08-14T09:53:26Z]   21 passing (8m)
[2021-08-14T09:53:26Z]   4 pending
[2021-08-14T09:53:26Z]   1 failing
[2021-08-14T09:53:26Z]
[2021-08-14T09:53:26Z]   1) End-to-end alert tests
[2021-08-14T09:53:26Z]        End-to-end alerts for default and system tenants:
[2021-08-14T09:53:26Z]      Error: Expectation not fulfilled within 90 s
[2021-08-14T09:53:26Z]       at Object.waitForQueryResult (testutils/index.ts:934:9)
[2021-08-14T09:53:26Z]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-08-14T09:53:26Z]       at getE2EAlertCountMetric (test_alerts.ts:301:23)
[2021-08-14T09:53:26Z]       at waitForE2EAlertFiring (test_alerts.ts:376:19)
[2021-08-14T09:53:26Z]       at Context.<anonymous> (test_alerts.ts:449:5)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2860#7f351f2a-1d18-4caf-99e6-8cd60e7750bc/6-1765

```
[2021-08-14T09:48:30Z] 2021-08-14T09:48:30.198Z info: Cortex query parameter (object):
[2021-08-14T09:48:30Z] {
[2021-08-14T09:48:30Z]   "query": "e2ealerting_webhook_receiver_evaluations_total{job=\"testalerts-system-o2dl0-job\"}"
[2021-08-14T09:48:30Z] }
[2021-08-14T09:48:30Z] 2021-08-14T09:48:30.199Z info: Waiting for query to return a match, deadline in 90s
[2021-08-14T09:48:40Z] 2021-08-14T09:48:40.289Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'response' for 10000ms -- ignore, proceed with next iteration
[2021-08-14T09:48:50Z] 2021-08-14T09:48:50.301Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'response' for 10000ms -- ignore, proceed with next iteration
[2021-08-14T09:49:00Z] 2021-08-14T09:49:00.314Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'response' for 10000ms -- ignore, proceed with next iteration
[2021-08-14T09:49:10Z] 2021-08-14T09:49:10.326Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'response' for 10000ms -- ignore, proceed with next iteration
[2021-08-14T09:49:20Z] 2021-08-14T09:49:20.336Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'response' for 10000ms -- ignore, proceed with next iteration
[2021-08-14T09:49:30Z] 2021-08-14T09:49:30.349Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'response' for 10000ms -- ignore, proceed with next iteration
[2021-08-14T09:49:40Z] 2021-08-14T09:49:40.452Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'response' for 10000ms -- ignore, proceed with next iteration
[2021-08-14T09:49:50Z] 2021-08-14T09:49:50.464Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'response' for 10000ms -- ignore, proceed with next iteration
[2021-08-14T09:50:00Z] 2021-08-14T09:50:00.474Z info: waitForQueryResult() loop: http request failed: Timeout awaiting 'response' for 10000ms -- ignore, proceed with next iteration
[2021-08-14T09:50:00Z] 2021-08-14T09:50:00.474Z error: Reached 90 s deadline, giving up
[2021-08-14T09:50:00Z]     1) End-to-end alerts for default and system tenants
```

**Comment by nickbp** [comment]
Something odd with the failure is that things worked fine for the `default` tenant but then timed out for the `system` tenant.

I checked cortex pod logs for the 09:48-09:50 time range and didn't see anything interesting there...

**Comment by sreis** [comment]
```
[2021-08-24T09:46:52Z]   1) End-to-end alert tests
[2021-08-24T09:46:52Z]        End-to-end alerts for default and system tenants:
[2021-08-24T09:46:52Z]      Error: Expectation not fulfilled within 90 s
[2021-08-24T09:46:52Z]       at Object.waitForQueryResult (testutils/index.ts:934:9)
[2021-08-24T09:46:52Z]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-08-24T09:46:52Z]       at async getE2EAlertCountMetric (test_alerts.ts:336:23)
[2021-08-24T09:46:52Z]       at async waitForE2EAlertFiring (test_alerts.ts:405:19)
[2021-08-24T09:46:52Z]       at async Context.<anonymous> (test_alerts.ts:495:5)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2941#e855ed2e-4bcb-4095-a93b-f03d957b91ef/6-1647

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/3076#3a5c6664-6eca-40f8-bd40-c371048eb2fd/3040-4829

```
[2021-09-10T03:40:38Z]   1) End-to-end alert tests
[2021-09-10T03:40:38Z]        End-to-end alerts for default and system tenants:
[2021-09-10T03:40:38Z]      Error: Expectation not fulfilled within 90 s
[2021-09-10T03:40:38Z]       at waitForQueryResult (testutils/index.ts:934:9)
[2021-09-10T03:40:38Z]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-09-10T03:40:38Z]       at async getE2EAlertCountMetric (test_alerts.ts:336:23)
[2021-09-10T03:40:38Z]       at async waitForE2EAlertFiring (test_alerts.ts:405:19)
[2021-09-10T03:40:38Z]       at async Context.<anonymous> (test_alerts.ts:500:5)
```
