### ISSUE TITLE
ci-instability: dd_api_run_agent_container_query_sysuptime: Expectation not fulfilled within 90 s

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1284]
```
[2021-08-16T15:52:07Z]   1) DD API test suite
[2021-08-16T15:52:07Z]        dd_api_run_agent_container_query_sysuptime:
[2021-08-16T15:52:07Z]      Error: Expectation not fulfilled within 90 s
[2021-08-16T15:52:07Z]       at Object.waitForQueryResult (testutils/index.ts:934:9)
[2021-08-16T15:52:07Z]       at Context.<anonymous> (test_dd.ts:350:25)
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2879#d956ba45-68f8-4553-811e-4506daf602c6/3639-5403

```
[2021-08-16T15:48:31Z] 2021-08-16T15:48:31.637Z info: Cortex query parameter (object):
[2021-08-16T15:48:31Z] {
[2021-08-16T15:48:31Z]   "end": "1629129451",
[2021-08-16T15:48:31Z]   "query": "system_uptime{job=\"ddagent\", type=\"gauge\"}",
[2021-08-16T15:48:31Z]   "start": "1629126151",
[2021-08-16T15:48:31Z]   "step": "60s"
[2021-08-16T15:48:31Z] }
[2021-08-16T15:48:31Z] 2021-08-16T15:48:31.637Z info: Waiting for query to return a match, deadline in 90s
[2021-08-16T15:48:31Z] 2021-08-16T15:48:31.874Z info: query response data not yet as expected, retry query in 8 s
[2021-08-16T15:48:39Z] 2021-08-16T15:48:39.987Z info: query response data not yet as expected, retry query in 8 s
[2021-08-16T15:48:48Z] 2021-08-16T15:48:48.098Z info: query response data not yet as expected, retry query in 8 s
[2021-08-16T15:48:56Z] 2021-08-16T15:48:56.221Z info: query response data not yet as expected, retry query in 8 s
[2021-08-16T15:49:04Z] 2021-08-16T15:49:04.453Z info: query response data not yet as expected, retry query in 8 s
[2021-08-16T15:49:12Z] 2021-08-16T15:49:12.559Z info: query response data not yet as expected, retry query in 8 s
[2021-08-16T15:49:20Z] 2021-08-16T15:49:20.672Z info: query response data not yet as expected, retry query in 8 s
[2021-08-16T15:49:28Z] 2021-08-16T15:49:28.793Z info: query response data not yet as expected, retry query in 8 s
[2021-08-16T15:49:37Z] 2021-08-16T15:49:37.027Z info: query response data not yet as expected, retry query in 8 s
[2021-08-16T15:49:45Z] 2021-08-16T15:49:45.136Z info: query response data not yet as expected, retry query in 8 s
[2021-08-16T15:49:53Z] 2021-08-16T15:49:53.254Z info: query response data not yet as expected, retry query in 8 s
[2021-08-16T15:50:01Z] 2021-08-16T15:50:01.460Z info: query response data not yet as expected, retry query in 8 s
[2021-08-16T15:50:09Z] 2021-08-16T15:50:09.461Z error: Reached 90 s deadline, giving up
```

**Comment by nickbp** [comment]
Only seen once in mid-August, going to close as inactive for now
