### ISSUE TITLE
destroy: gcp: hangs in `Destroying Subnet`, no progress report

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1289]
```
2021-08-17T09:52:24.947Z info: Destroying CloudNat and Router
2021-08-17T09:52:25.383Z info: Destroying Subnet
...
```
Also no debug log.

**Comment by jgehrcke** [comment]
Added more log statements to find the problem:
```
2021-08-17T10:08:10.347Z debug: emit DELETE api call for subnetwork jpaug17
2021-08-17T10:08:10.596Z warning: error during subnetwork deletion: ApiError: The resource 'projects/vast-pad-240918/regions/us-west2/subnetworks/jpaug17' was not found
    at new ApiError (/home/jp/dev/opstrace/node_modules/@google-cloud/common/build/src/util.js:59:15)
    at Util.parseHttpRespBody (/home/jp/dev/opstrace/node_modules/@google-cloud/common/build/src/util.js:194:38)
    at Util.handleResp (/home/jp/dev/opstrace/node_modules/@google-cloud/common/build/src/util.js:135:117)
    at /home/jp/dev/opstrace/node_modules/@google-cloud/common/build/src/util.js:434:22
    at onResponse (/home/jp/dev/opstrace/node_modules/retry-request/index.js:214:7)
    at /home/jp/dev/opstrace/node_modules/teeny-request/src/index.ts:325:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 404,
  errors: [Array],
  response: [Gunzip]
}
```

This triggered an infinite loop. Actual bug is here, in this error handler
https://github.com/opstrace/opstrace/blob/699300069ab6979fcb69e221779c9c07a4dad049/lib/gcp/src/subnetworks.ts#L212

```
    } catch (e) {
      if (e instanceof GCPApiError) {
        log.info(
          "test for JP: e instanceof GCPApiError: %s",
          JSON.stringify(e, null, 2)
        );
      }
      if (!e.code || (e.code && e.code !== 404)) {
        throw e;
      }
    }
```

- Over-generalized error handler with missing re-throw fallthrough.
- `(e instanceof GCPApiError)` does not work

**Comment by jgehrcke** [comment]
help is here: https://github.com/opstrace/opstrace/pull/1291
