### ISSUE TITLE
ci instability: loki query GET: fails with TCP connect() timeout

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#130]
Five loki tests failed during query:
```
[2020-12-06T15:37:28Z]
[2020-12-06T15:37:28Z]   13 passing (1m)
[2020-12-06T15:37:28Z]   5 failing
[2020-12-06T15:37:28Z]
[2020-12-06T15:37:28Z]   1) Loki API test suite
```
https://buildkite.com/opstrace/prs/builds/3165#6357df46-61ad-4aa0-bda7-881c7c8b0b14/2261-4061

Five times:
```
RequestError: Timeout awaiting 'connect' for 10000ms
```

Previous occurrences from https://github.com/opstrace/opstrace-prelaunch/issues/1863:

```
[2020-11-19T04:35:59Z]   11 passing (1m)
[2020-11-19T04:35:59Z]   6 failing
[2020-11-19T04:35:59Z]
[2020-11-19T04:35:59Z]   1) Loki API test suite
[2020-11-19T04:35:59Z]        insert w/ cntnrzd FluentD(loki plugin), then query:
[2020-11-19T04:35:59Z]      RequestError: Timeout awaiting 'connect' for 10000ms
[2020-11-19T04:35:59Z]       at ClientRequest.<anonymous> (node_modules/got/dist/source/
```

```
[2020-11-09T04:46:12Z]   16 passing (37s)
[2020-11-09T04:46:12Z]   1 failing
[2020-11-09T04:46:12Z]
[2020-11-09T04:46:12Z]   1) Loki API test suite
[2020-11-09T04:46:12Z]        POST JSON to /loki/api/v1/push, then query:
[2020-11-09T04:46:12Z]      RequestError: Timeout awaiting 'connect' for 10000ms
[2020-11-09T04:46:12Z]       at ClientRequest.<anonymous> (node_modules/got/dist/source/core/index.js:954:25)
[2020-11-09T04:46:12Z]       at ClientRequest.origin.emit (node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
[2020-11-09T04:46:12Z]       at TLSSocket.socketErrorListener (_http_client.js:469:9)
```

```
[2020-11-19T05:16:20Z]   16 passing (37s)
[2020-11-19T05:16:20Z]   1 failing
[2020-11-19T05:16:20Z]
[2020-11-19T05:16:20Z]   1) Loki API test suite
[2020-11-19T05:16:20Z]        long dummystream insert, validate via query:
[2020-11-19T05:16:20Z]      RequestError: Timeout awaiting 'connect' for 10000ms
```

**Comment by sreis** [comment]
Another instance of the 10s timeout

https://buildkite.com/opstrace/scheduled-main-builds/builds/1344#00e5545b-07a2-492f-be17-def6296114e3/2266-4262

```
[2020-12-11T00:41:22Z]   1) Loki API test suite
[2020-12-11T00:41:22Z]        POST JSON to /loki/api/v1/push, then query:
[2020-12-11T00:41:22Z]      RequestError: Timeout awaiting 'connect' for 10000ms
```

The 10s should come from the [DefaultTransport](https://golang.org/pkg/net/http/#RoundTripper) but we'll need to dig a bit deeper. Also, I haven't been to repro this locally.

**Comment by jgehrcke** [comment]
> The 10s should come from

It's the connect() timeout configured for the HTTP client in test-remote: https://github.com/opstrace/opstrace/blob/d14ec9f39dd1fffa37ab5390a6577ce7cbc89c0a/test/test-remote/testutils/index.ts#L765

**Comment by sreis** [comment]
> It's the connect() timeout configured for the HTTP client in test-remote

I can't find anything in the logs for the failed builds, so I'm inclined to start pointing the finger at client-side network hiccup on this one. It either fails one test or in the case of the 4 failed ones (in the issue description), it then runs the looker tests without any problems.

Should we add a retry if it's a connect timeout error?

**Comment by sreis** [comment]
> Should we add a retry if it's a connect timeout error?

Apparently, it already retries twice by default (`limit=2`) https://github.com/sindresorhus/got#retry .

**Comment by jgehrcke** [comment]
> Should we add a retry if it's a connect timeout error?

Well, often we want to learn about these fluctuations / problems when they happen from an HTTP client's point of view.

At least that's a focus I'd like us to have in test-remote. I've therefore consciously disabled retrying in `got` in test-remote in certain places, such as when querying loki:

https://github.com/opstrace/opstrace/blob/f3e15eae693639c0bea80b45bc813d58dd44e6aa/test/test-remote/testutils/logs.ts#L69

```
  const options = {
    retry: 0,
    throwHttpErrors: false,
    searchParams: queryParams,
    timeout: httpTimeoutSettings,
    headers: headers,
    https: { rejectUnauthorized: LOKI_API_TLS_VERIFY } // https://github.com/sindresorhus/got/issues/1191
  };
```

> so I'm inclined to start pointing the finger at client-side network hiccup on this one

That's interesting.. :) would love to find out!

I can tell that we had many more connect() TCP timeouts to the data API in the past, i.e. I think we know that on some occasions, the 'problem'/instability was actually in the Opstrace cluster.

**Comment by sreis** [comment]
> That is, for now, I'd love to expose these fluctuations instead of hiding them behind retries. 

I'm on the fence on this one since the client (fluentd, promtail) will attempt a retry (when configured properly ofc).

> I can tell that we had many more connect() TCP timeouts to the data API in the past, i.e. I think we know that on some occasions, the 'problem'/instability was actually in the Opstrace cluster.

If it was instability on the cluster I would expect all the tests to fail. 

> I've therefore consciously disabled retrying in got in test-remote in certain places, such as when querying loki:

That probably explains why the [POST](https://github.com/opstrace/opstrace/blob/main/test/test-remote/test_loki_log_ingest_api.ts#L125-L131) succeeds but the GET fails. Right?

**Comment by jgehrcke** [comment]
Three food items for thought :cheese: :cut_of_meat: :broccoli:: 

* Doing silent HTTP request retries in test-remote can be looked at as not just hiding client-side network instabilities, but _also_ hiding certain API quality of service fluctuations (as long as there is no other method to try to capture those).
* Thought experiment: assuming that the client network connectivity is _ideal_, not doing retries in the test suite is a pragmatic and highly efficient way to measure aspects about API quality of service.
* An interesting question is: how far from the ideal state is the network connectivity up to the to-be-tested system?

> That probably explains why the POST succeeds but the GET fails. Right?

Huh -- that's actually an oversight. Well. Good question. But we cannot know for certain. :) I wouldn't even say "probably", just "maybe" :).

A general, systematic perspective: when _not_ doing HTTP request retries what we see (expose) with the test outcome is a superposition of instabilities from two categories:
* client-side (including the last mile leading up to the to-be-tested system) 
* in the to-be-tested system.

This superposition cannot be untangled based on the individual test result alone (the test result does not say which part contributed what). It only says: one of both was responsible -- or both were responsible at the same time.

_That_ in itself is valuable information.

That is, not doing silent HTTP request retries in test-remote can be looked at as way to measure (expose/detect) API quality of service fluctuations. Bad: it does not _only_ expose those. Good: but _also_ those.

Now: we can pragmatically tell those two scenarios apart, over time, statistically. By monitoring the rate at which certain symptoms happen. We can assume that the rate at which client-side (including the last mile leading up to the to-be-tested system) contributes is more or less constant, whereas the rate at which the to-be-tested system contributes is probably subject to systematic changes (improvements, regressions).

At a rather low rate of occurrence a ticket like this here can pretty much safely be ignored, it doesn't quite need to create work or attention. But when the rate of occurrence changes then we usually learn something. Something valuable. That's why I'd love for us to pragmatically track the occurrences, i.e. the rate, and also how the rate evolves over time.

**Comment by sreis** [comment]
https://buildkite.com/opstrace/upgrade-tests/builds/55#c5c86610-2e2f-4c37-a477-a431bbe16fbb/2936-5366

**Comment by sreis** [comment]
https://buildkite.com/opstrace/upgrade-tests/builds/61#092208e7-55c0-4cb1-b61e-9a44f9504940/3240-5620

```
[2021-02-16T17:20:05Z]   1) Loki API test suite
[2021-02-16T17:20:05Z]        long dummystream insert, validate via query:
[2021-02-16T17:20:05Z]      RequestError: Timeout awaiting 'connect' for 10000ms
```

**Comment by jgehrcke** [comment]
```
[2021-03-23T16:49:40Z] 2021-03-23T16:49:40.072Z info: validated 20000 entries (inspected every Nth entry: 0 (0: all))
[2021-03-23T16:49:40Z] 2021-03-23T16:49:40.072Z info: stream test-remote-ldi-7UoAtZ-0003: validation took 2.8 s overall
[2021-03-23T16:49:49Z]     1) long dummystream insert, validate via query
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/1971#b03c723f-e42d-47ef-979c-f3f48281b77c/1313-2998
with logging regression!

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2815#c14ea596-32ca-4dbd-9c6d-674f381f4290/348-2183

```
[2021-08-08T05:08:01Z]   1) Loki API test suite
--
  | [2021-08-08T05:08:01Z]        insert w/ cntnrzd FluentD(loki plugin), then query:
  | [2021-08-08T05:08:01Z]      Error: Expectation not fulfilled within 30 s
  | [2021-08-08T05:08:01Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:265:9)
  | [2021-08-08T05:08:01Z]       at runMicrotasks (<anonymous>)
  | [2021-08-08T05:08:01Z]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
  | [2021-08-08T05:08:01Z]       at Context.<anonymous> (test_loki_log_ingest_api.ts:198:5)
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2815#c14ea596-32ca-4dbd-9c6d-674f381f4290/348-1272

```
[2021-08-08T05:04:55Z] 2021-08-08 05:04:47 +0000 [debug]: #0 calling terminate on output plugin type=:loki plugin_id="object:3f934cbd2800"
--
  | [2021-08-08T05:04:55Z] Z2021-08-08 05:04:47 +0000 [info]: fluent/log.rb:329:info: Worker 0 finished with status 0
  | [2021-08-08T05:04:55Z]
  | [2021-08-08T05:04:55Z] 2021-08-08T05:04:55.807Z info: Enter Loki query loop, wait for expected result, deadline 30 s.
  | [2021-08-08T05:04:55Z] Query parameters: {
  | [2021-08-08T05:04:55Z]   "direction": "BACKWARD",
  | [2021-08-08T05:04:55Z]   "end": "1628402695806000000",
  | [2021-08-08T05:04:55Z]   "limit": "1000",
  | [2021-08-08T05:04:55Z]   "query": "{indexfieldname=\"LFFNl\"}",
  | [2021-08-08T05:04:55Z]   "start": "1628395495806000000"
  | [2021-08-08T05:04:55Z] }
  | [2021-08-08T05:05:13Z] 2021-08-08T05:05:13.915Z info: waitForLokiQueryResult() loop: http request failed: Timeout awaiting 'request' for 5000ms -- ignore, proceed with next iteration
  | [2021-08-08T05:05:32Z] 2021-08-08T05:05:32.006Z info: waitForLokiQueryResult() loop: http request failed: Timeout awaiting 'request' for 5000ms -- ignore, proceed with next iteration
  | [2021-08-08T05:05:32Z] 2021-08-08T05:05:32.006Z error: query deadline hit
  | [2021-08-08T05:05:32Z]     1) insert w/ cntnrzd FluentD(loki plugin), then query
  | [2021-08-08T05:05:32Z] 2021-08-08T05:05:32.030Z info: log file content (fluentbit tail input):
  | [2021-08-08T05:05:32Z] aaaaaaa
  | [2021-08-08T05:05:32Z] bbbbbb
  | [2021-08-08T05:05:32Z] cccccccc
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2815#c14ea596-32ca-4dbd-9c6d-674f381f4290/348-926

```
[2021-08-08T05:04:42Z] 82021-08-08 05:04:12 UTC \| CORE \| ERROR \| (pkg/forwarder/transaction/transaction.go:338 in internalProcess) \| Error code "404 Not Found" received while sending transaction to "https://dd.default.schedul-bk-2815-83d-a.opstrace.io/intake/?api_key=***************************DcifQ.eyJpYXQiOjE2MjgzOTY2NTQsImV4cCI6MTk0Mzk3MjY1NCwiYXVkIjoib3BzdHJhY2UtY2x1c3Rlci1zY2hlZHVsLWJrLTI4MTUtODNkLWEiLCJpc3MiOiJvcHN0cmFjZS1jbGkiLCJzdWIiOiJ0ZW5hbnQtZGVmYXVsdCJ9.ViwK6Jm1DCfD5PqMeGo5yXR-QOZOGftAwIBqiuSOwjzlaJ0UE_ElpA2NkERv11WuufrB961mCgLFAcrj1QNRAG2l9kTbaSrhY8_wFyuPlAIiqnaBDHJV6PloJ1slboHsx0IqHkwYwCTBPZPQwlY8lDo0qW4VL_FD74pudWHw9O5Y0Y6XzYFPftRMtehTYwHKAEtVWPLluM_4LANZ8GZ7rwXhTgQjGXZyIcDwsEPYYbYHlw317JpckyYvgljGUd36UDMRtEUsaF1K9oUsnJshbTYIlWn8ThovOUmE76bCZUMiKujdxHhbII9RI3byEyjbPHQ2RZvNAbmG41_vOtIKwg": 404 page not found
--
  | [2021-08-08T05:04:42Z] , dropping it
```

**Comment by jgehrcke** [comment]
this ticket here focuses on connect() timeout.

> https://buildkite.com/opstrace/scheduled-main-builds/builds/2815#c14ea596-32ca-4dbd-9c6d-674f381f4290/348-2183

@terrcin there we did not see a connect() timeout. That specific symptom much better fits https://github.com/opstrace/opstrace/issues/1226.

> [2021-08-08T05:04:42Z] ��82021-08-08 05:04:12 UTC \| CORE \| ERROR \| (pkg/

this is a red herring, not a problem.

**Comment by jgehrcke** [comment]
have not seen this here in a long time, closing for now
