### ISSUE TITLE
ci-instability: Subnet does not exist: The resource 'projects/ci-shard-bbb/global/networks/schedul-bk-XXXX-XX-X' was not found

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1317]
**Describe the bug**

```
[2021-08-24T03:13:38Z] 2021-08-24T03:13:38.608Z info: Ensuring Subnet exists
[2021-08-24T03:13:39Z] 2021-08-24T03:13:39.132Z error: error during cluster creation (attempt 2):
[2021-08-24T03:13:39Z] ApiError: The resource 'projects/ci-shard-bbb/global/networks/schedul-bk-2939-3b3-ug' was not found
[2021-08-24T03:13:39Z]     at new ApiError (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:59:15)
[2021-08-24T03:13:39Z]     at Util.parseHttpRespBody (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:194:38)
[2021-08-24T03:13:39Z]     at Util.handleResp (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:135:117)
[2021-08-24T03:13:39Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/util.js:434:22
[2021-08-24T03:13:39Z]     at onResponse (/snapshot/build/node_modules/retry-request/index.js:214:7)
[2021-08-24T03:13:39Z]     at /snapshot/build/node_modules/teeny-request/src/index.ts:325:11
[2021-08-24T03:13:39Z]     at runMicrotasks (<anonymous>)
[2021-08-24T03:13:39Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2021-08-24T03:13:39Z]   code: 404,
[2021-08-24T03:13:39Z]   errors: [Array],
[2021-08-24T03:13:39Z]   response: [Gunzip]
[2021-08-24T03:13:39Z] }
[2021-08-24T03:13:39Z] 2021-08-24T03:13:39.132Z debug: `err?.stack`: Error: The resource 'projects/ci-shard-bbb/global/networks/schedul-bk-2939-3b3-ug' was not found
[2021-08-24T03:13:39Z]     at new ApiError (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:59:15)
[2021-08-24T03:13:39Z]     at Util.parseHttpRespBody (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:194:38)
[2021-08-24T03:13:39Z]     at Util.handleResp (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:135:117)
[2021-08-24T03:13:39Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/util.js:434:22
[2021-08-24T03:13:39Z]     at onResponse (/snapshot/build/node_modules/retry-request/index.js:214:7)
[2021-08-24T03:13:39Z]     at /snapshot/build/node_modules/teeny-request/src/index.ts:325:11
[2021-08-24T03:13:39Z]     at runMicrotasks (<anonymous>)
[2021-08-24T03:13:39Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-08-24T03:13:39Z] 2021-08-24T03:13:39.132Z error: JSON representation of err: {
[2021-08-24T03:13:39Z]   "code": 404,
[2021-08-24T03:13:39Z]   "errors": [
[2021-08-24T03:13:39Z]     {
[2021-08-24T03:13:39Z]       "message": "The resource 'projects/ci-shard-bbb/global/networks/schedul-bk-2939-3b3-ug' was not found",
[2021-08-24T03:13:39Z]       "domain": "global",
[2021-08-24T03:13:39Z]       "reason": "notFound"
[2021-08-24T03:13:39Z]     }
[2021-08-24T03:13:39Z]   ],
[2021-08-24T03:13:39Z]   "response": {
[2021-08-24T03:13:39Z]     "headers": {
[2021-08-24T03:13:39Z]       "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"",
[2021-08-24T03:13:39Z]       "cache-control": "private",
[2021-08-24T03:13:39Z]       "content-encoding": "gzip",
[2021-08-24T03:13:39Z]       "content-type": "application/json; charset=UTF-8",
[2021-08-24T03:13:39Z]       "date": "Tue, 24 Aug 2021 03:13:39 GMT",
[2021-08-24T03:13:39Z]       "server": "ESF",
[2021-08-24T03:13:39Z]       "transfer-encoding": "chunked",
[2021-08-24T03:13:39Z]       "vary": "Origin, X-Origin, Referer",
[2021-08-24T03:13:39Z]       "x-content-type-options": "nosniff",
[2021-08-24T03:13:39Z]       "x-frame-options": "SAMEORIGIN",
[2021-08-24T03:13:39Z]       "x-xss-protection": "0"
[2021-08-24T03:13:39Z]     }
[2021-08-24T03:13:39Z]   },
[2021-08-24T03:13:39Z]   "message": "The resource 'projects/ci-shard-bbb/global/networks/schedul-bk-2939-3b3-ug' was not found"
[2021-08-24T03:13:39Z] }
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2939#1b419a87-e943-44c1-bd28-6c75580c392b/319-611

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2940#15bf3571-4dee-4cdd-a8b0-329d6d1f14e5/319-866

**Comment by sreis** [comment]
Looks like we hit a quota issue in the `ci-shard-bbb` project:

![Screenshot from 2021-08-24 08-42-57](https://user-images.githubusercontent.com/495294/130586116-0cc24389-3333-407b-8ca7-94f12f2a1fa0.png)
