### ISSUE TITLE
dns service client: 4xx errors may not be handled (all of them, always?) -- regression around `e instanceof got.RequestError`

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#1323]
https://buildkite.com/opstrace/upgrade-tests/builds/1259#de149bfb-607a-4fb0-80a7-77acdd3a7740/8243-9523

```
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.367Z [32minfo[39m: DNS service teardown: NS record query attempt 1: NS record set exists for upgrade-bk-1259-cb7-g.opstrace.io on the *.opstrace.io DNS zone.
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.367Z [34mdebug[39m: do DNS service client:DELETE
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.443Z [31merror[39m: error during cluster teardown (attempt 5):
[2021-08-24T21:48:06Z] HTTPError: Response code 404 (Not Found)
[2021-08-24T21:48:06Z]     at Request.<anonymous> (/snapshot/build/lib/utils/node_modules/got/dist/source/as-promise/index.js:117:42)
[2021-08-24T21:48:06Z]     at runMicrotasks (<anonymous>)
[2021-08-24T21:48:06Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2021-08-24T21:48:06Z]   code: undefined,
[2021-08-24T21:48:06Z]   timings: [Object]
[2021-08-24T21:48:06Z] }
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.443Z [34mdebug[39m: `err?.stack`: HTTPError: Response code 404 (Not Found)
[2021-08-24T21:48:06Z]     at Request.<anonymous> (/snapshot/build/lib/utils/node_modules/got/dist/source/as-promise/index.js:117:42)
[2021-08-24T21:48:06Z]     at runMicrotasks (<anonymous>)
[2021-08-24T21:48:06Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.443Z [31merror[39m: JSON representation of err: {
[2021-08-24T21:48:06Z]   "name": "HTTPError",
[2021-08-24T21:48:06Z]   "timings": {
[2021-08-24T21:48:06Z]     "start": 1629841686368,
[2021-08-24T21:48:06Z]     "socket": 1629841686368,
[2021-08-24T21:48:06Z]     "lookup": 1629841686368,
[2021-08-24T21:48:06Z]     "connect": 1629841686376,
[2021-08-24T21:48:06Z]     "secureConnect": 1629841686389,
[2021-08-24T21:48:06Z]     "upload": 1629841686389,
[2021-08-24T21:48:06Z]     "response": 1629841686443,
[2021-08-24T21:48:06Z]     "end": 1629841686443,
[2021-08-24T21:48:06Z]     "phases": {
[2021-08-24T21:48:06Z]       "wait": 0,
[2021-08-24T21:48:06Z]       "dns": 0,
[2021-08-24T21:48:06Z]       "tcp": 8,
[2021-08-24T21:48:06Z]       "tls": 13,
[2021-08-24T21:48:06Z]       "request": 0,
[2021-08-24T21:48:06Z]       "firstByte": 54,
[2021-08-24T21:48:06Z]       "download": 0,
[2021-08-24T21:48:06Z]       "total": 75
[2021-08-24T21:48:06Z]     }
[2021-08-24T21:48:06Z]   }
[2021-08-24T21:48:06Z] }
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.444Z [31merror[39m: 5 attempt(s) failed. Stop retrying. Exit.
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.444Z [34mdebug[39m: shut down logger, then exit with code 1
[2021-08-24T21:48:06Z] make[1]: *** [Makefile:760: testupgrade-teardown] Error 1
[2021-08-24T21:48:06Z] make[1]: Leaving directory '/build'
```

**Comment by jgehrcke** [comment]
This is highly confusing.
This log message is there:
https://github.com/opstrace/opstrace/blob/f6989cd681e874844837fe7cda06a7d81957f7b9/lib/dns/src/opstrace.ts#L314

This log message is not: https://github.com/opstrace/opstrace/blob/f6989cd681e874844837fe7cda06a7d81957f7b9/lib/dns/src/opstrace.ts#L341

This log message is also not there: https://github.com/opstrace/opstrace/blob/f6989cd681e874844837fe7cda06a7d81957f7b9/lib/dns/src/opstrace.ts#L362

It looks like this `throw e` might have rethrown the error: https://github.com/opstrace/opstrace/blob/f6989cd681e874844837fe7cda06a7d81957f7b9/lib/dns/src/opstrace.ts#L393
but we cannot tell as of the incomplete and rather useless stack trace (grrr.. also see https://github.com/opstrace/opstrace/issues/236)

Given the structure of this `HTTPError` it looks like this is thrown by `got`. OK.

`if (e instanceof got.RequestError) {` is supposed to capture exactly hat, _all_ errors thrown in the context of got HTTP request processing/emission. 

That error hierarchy is documented here: https://github.com/sindresorhus/got/blob/a885dac6a06e28825132780a7af50299f0b4a845/documentation/8-errors.md

`RequestError`:

> All the errors below inherit this one.

And then the docs also say that

```
All Got errors contain various metadata, such as:

code - A string like ERR_NON_2XX_3XX_RESPONSE,
options - An instance of Options,
request - An instance of Got Stream,
response (optional) - An instance of Got Response,
timings (optional) - Points to response.timings.
```

But this `HTTPError` only contains `timings`. Huh. And there's `code: undefined,`.

The other universe of confusion here is... sometimes a 404 response is actually handled by that error handler... otherwise this code section would not work:

https://github.com/opstrace/opstrace/blob/f6989cd681e874844837fe7cda06a7d81957f7b9/lib/dns/src/opstrace.ts#L348

**Comment by jgehrcke** [comment]
OK `request` and `response` are non-enumerable, also see https://github.com/sindresorhus/got/issues/1126#issuecomment-778768885

**Comment by jgehrcke** [comment]
It's crazy that all this corresponds to such recent discussions here:
https://github.com/sindresorhus/got/issues/1736#issuecomment-855297175
https://github.com/sindresorhus/got/issues/1126#issuecomment-881908912
https://github.com/sindresorhus/got/issues/1077#issuecomment-903165844

**Comment by szmarczak** [comment]
The docs are for Got 12 beta

**Comment by szmarczak** [comment]
Also we expose `error.options` since Got 12

**Comment by jgehrcke** [comment]
> The docs are for Got 12 beta

https://github.com/sindresorhus/got/tree/v11.8.2#gotrequesterror

> All the errors below inherit this one.

Still unclear why the `if (e instanceof got.RequestError)` handler didn't catch this one here! :) And thanks for dropping by @szmarczak

**Comment by szmarczak** [comment]
I think it should catch it https://github.com/sindresorhus/got/blob/f896aa52abc41fe40d4942da94a0408477358f14/source/core/index.ts#L1255-L1268

**Comment by szmarczak** [comment]
These might be a different instances (fresh import). Try comparing the error name instead.

**Comment by jgehrcke** [comment]
> These might be a different instances (fresh import). Try comparing the error name instead.

@szmarczak I really do appreciate that you did spend a few minutes in here! Thank you! If that was the specific problem here then I am additionally super thankful for you to have found that.

But I also have to say that if that is the problem then I don't yet fully understand it and I have found just one more argument to say "I really really really don't know how to do proper error handling in this ecosystem". And with that I mean generally the wider JavaScript ecosystem. It is brutally hard to figure out and this is why this ecosystem is IMO not pleasant for writing production code for long-running services. Yet, might take a few years to mature.

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/3021#4c2bf560-6bf3-4ad7-a661-a51ac4a414a3/8382-9006

**Comment by jgehrcke** [comment]
We have found that also 401 error responses can get past the current error handler:
```
2021-09-24T13:35:08.574Z error: error during cluster creation (attempt 1):
HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/snapshot/build/lib/utils/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: undefined,
  timings: [Object]
}
2021-09-24T13:35:08.575Z debug: `err?.stack`: HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/snapshot/build/lib/utils/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-09-24T13:35:08.575Z error: JSON representation of err: {
  "name": "HTTPError",
  "timings": {
    "start": 1632490508520,
    "socket": 1632490508521,
    "lookup": 1632490508522,
    "connect": 1632490508530,
    "secureConnect": 1632490508547,
    "upload": 1632490508547,
    "response": 1632490508568,
    "end": 1632490508569,
    "phases": {
      "wait": 1,
      "dns": 1,
      "tcp": 8,
      "tls": 17,
      "request": 0,
      "firstByte": 21,
      "download": 1,
      "total": 49
    }
  }
}```

**Comment by szmarczak** [comment]
Have you tried comparing error name?

**Comment by jgehrcke** [comment]
> Have you tried comparing error name?

YEs @szmarczak -- doing that here: https://github.com/opstrace/opstrace/pull/1421/files#diff-4de5735e449eb5a1edb7d05e850c9eeeb1f0c5df66693235687aabb8417c9ad2R343 :)
