### ISSUE TITLE
ci-instability: Creating SQLInstance failed, retrying: GaxiosError: 502

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1343]
**Describe the bug**

```
[2021-08-31T09:34:03Z] 2021-08-31T09:34:03.299Z debug: Creating SQLInstance failed, retrying: GaxiosError: <!DOCTYPE html>
[2021-08-31T09:34:03Z] <html lang=en>
[2021-08-31T09:34:03Z]   <meta charset=utf-8>
[2021-08-31T09:34:03Z]   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
[2021-08-31T09:34:03Z]   <title>Error 502 (Server Error)!!1</title>
[2021-08-31T09:34:03Z]   <style>
[2021-08-31T09:34:03Z]     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
[2021-08-31T09:34:03Z]   </style>
[2021-08-31T09:34:03Z]   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
[2021-08-31T09:34:03Z]   <p><b>502.</b> <ins>That’s an error.</ins>
[2021-08-31T09:34:03Z]   <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>
[2021-08-31T09:34:03Z]
[2021-08-31T09:34:03Z]     at Gaxios._request (/snapshot/build/node_modules/gaxios/src/gaxios.ts:140:15)
[2021-08-31T09:34:03Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-08-31T09:34:03Z]     at JWT.requestAsync (/snapshot/build/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18)
[2021-08-31T09:34:03Z]     at getSQLDatabase (/snapshot/build/lib/gcp/build/cloudSQLDatabase.js) {
[2021-08-31T09:34:03Z]   response: [Object],
[2021-08-31T09:34:03Z]   config: [Object],
[2021-08-31T09:34:03Z]   code: '502'
[2021-08-31T09:34:03Z] }
```

https://buildkite.com/opstrace/prs/builds/5663#023e0ef6-3049-4cd1-8b3a-38bcac8bc6c2/339-1713

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/3002#07871d3a-78e3-4b04-9c76-dd2def365f03/260-1292

and

https://buildkite.com/opstrace/scheduled-main-builds/builds/3003#3a1c0f6e-0b2c-4435-897d-9acd2d2fc7b4/260-1300

**Comment by sreis** [comment]
Those last two failures are in project ci-shard-iii, which was created yesterday. Things are running fine in project ci-shard-ggg, which was also created yesterday. 

I'll take ci-shard-iii out of rotation and sync with @triclambert.

**Comment by jgehrcke** [comment]
Interesting:
```
[2021-09-01T00:33:30Z] 2021-09-01T00:33:30.519Z info: Ensure SQLDatabase exists
...
[2021-09-01T00:49:33Z] 2021-09-01T00:49:33.499Z debug: Creating SQLInstance failed, retrying: GaxiosError: <!DOCTYPE html>
```

There are 16 minutes between these log statements.

What happened inbetween? Either this hang in a single HTTP call with ridiculous timeout settings, or many calls were made and we have insufficient logging to see that immediately.
