### ISSUE TITLE
Unable to run OpsTrace Quickstart in Fedora 36 (Rawhide)

### ISSUE THREAD

**Issue by spstarr** [opstrace/opstrace#1491]
**Describe the bug**
When performing the QuickStart steps I am unable to create an AWS cluster

**To Reproduce**
```./opstrace create aws my-cluster-name -c opstrace-config.yaml```

```
2022-01-04T20:50:21.585Z info: logging to file: opstrace_cli_create_20220104-205021Z.log
2022-01-04T20:50:21.586Z info: Discovered AWS credentials. Access key: ASIA...SICT
2022-01-04T20:50:21.590Z info: infra config: `aws` not set: populate with defaults
2022-01-04T20:50:21.591Z info: generate new RSA keypair. Modulus length (bits): 2048
Error: error:25066067:DSO support routines:dlfcn_load:could not load the shared library
    at Sign.sign (node:internal/crypto/sig:131:29)
    at Object.sign (/snapshot/build/node_modules/jsonwebtoken/node_modules/jwa/index.js:152:45)
    at Object.jwsSign [as sign] (/snapshot/build/node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:32:24)
    at Object.sign (/snapshot/build/node_modules/jsonwebtoken/sign.js:204:16)
    at generateJWTforTenantAPIfromKeyPair (/snapshot/build/packages/cli/src/crypto.ts:89:29)
    at Object.generateJWTforTenantAPI (/snapshot/build/packages/cli/src/crypto.ts:53:10)
    at genCryptoMaterialForAPIAuth (/snapshot/build/packages/cli/src/create.ts:207:22)
    at Object.create (/snapshot/build/packages/cli/src/create.ts:93:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:65:3)
    at Function.runMain (pkg/prelude/bootstrap.js:1805:13)
    at node:internal/main/run_main_module:17:47
    at main (/snapshot/build/packages/cli/src/index.ts:93:7)
    at mainWrapper (/snapshot/build/packages/cli/src/index.ts:579:5)
```
**Expected behavior**
The cluster is created and ready

I'm not sure whats missing which DSO/shared library.

I have both openssl-3.0.0-1.fc36.x86_64 and openssl1.1-1.1.1l-1.fc36.x86_64 here.

I don't see any explicit linkage to openssl DSO

```
$ ldd opstrace
        linux-vdso.so.1 (0x00007fffe43c2000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fbbd5bc4000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fbbd59a5000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fbbd58c5000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fbbd58aa000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fbbd58a5000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fbbd56a7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbbd5bda000)
```

**Comment by spstarr** [comment]
Move to GitLab
