### ISSUE TITLE
ci instability: Cannot kill container // cntnrzd FluentD(loki plugin)

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#188]
https://buildkite.com/opstrace/prs/builds/3311#94ab04b0-22b4-441a-80ee-94b6effa5ac3/3065-5060
```
[2020-12-17T13:59:57Z]   17 passing (1m)
[2020-12-17T13:59:57Z]   1 failing
[2020-12-17T13:59:57Z]
[2020-12-17T13:59:57Z]   1) Loki API test suite
[2020-12-17T13:59:57Z]        insert w/ cntnrzd FluentD(loki plugin), then query:
[2020-12-17T13:59:57Z]      Error: (HTTP code 409) unexpected - Cannot kill container: eb7212ed10c57e225cc7ebe32063f05cba3783903e7c31c739a185407740426f: Container eb7212ed10c57e225cc7ebe32063f05cba3783903e7c31c739a185407740426f is not running 
[2020-12-17T13:59:57Z]       at /test/node_modules/docker-modem/lib/modem.js:301:17
```
A simple race condition where the container is gone before we terminate it. The POST worked:
```
[2020-12-17T13:58:54Z] 2020-12-17T13:58:54.186Z info: attach file-backed stream
[2020-12-17T13:58:54Z] 2020-12-17T13:58:54.187Z info: container start()
[2020-12-17T13:58:54Z] 2020-12-17T13:58:54.341Z info: Waiting for needle to appear in container log, deadline in 15 s. Needle: POST request was responded to with status code 204
[2020-12-17T13:59:09Z] 2020-12-17T13:59:09.434Z info: deadline hit
[2020-12-17T13:59:09Z] 2020-12-17T13:59:09.434Z info: terminate container
```
(the subsequent query then wasn't executed)

**Comment by jgehrcke** [comment]
```
[2021-06-24T21:06:00Z] [92m [0m[32m 21 passing[0m[90m (19m)[0m
[2021-06-24T21:06:00Z] [36m [0m[36m 4 pending[0m
[2021-06-24T21:06:00Z] [31m  1 failing[0m
[2021-06-24T21:06:00Z] 
[2021-06-24T21:06:00Z] [0m  1) Loki API test suite
[2021-06-24T21:06:00Z]        insert w/ cntnrzd FluentD(loki plugin), then query:
[2021-06-24T21:06:00Z] [0m[31m     Error: (HTTP code 409) unexpected - Cannot kill container: a2e40b336e27357484a068bc9ede6c27c2d6b4f1397b749820ed4d0c6ead3e9a: Container a2e40b336e27357484a068bc9ede6c27c2d6b4f1397b749820ed4d0c6ead3e9a is not running [0m[90m
[2021-06-24T21:06:00Z]       at /build/node_modules/docker-modem/lib/modem.js:315:17
[2021-06-24T21:06:00Z]       at getCause (/build/node_modules/docker-modem/lib/modem.js:345:7)
[2021-06-24T21:06:00Z]       at Modem.buildPayload (/build/node_modules/docker-modem/lib/modem.js:314:5)
[2021-06-24T21:06:00Z]       at IncomingMessage.<anonymous> (/build/node_modules/docker-modem/lib/modem.js:286:14)
[2021-06-24T21:06:00Z]       at IncomingMessage.emit (domain.js:470:12)
[2021-06-24T21:06:00Z]       at endReadableNT (internal/streams/readable.js:1317:12)
[2021-06-24T21:06:00Z]       at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2545 (AWS)

**Comment by terrcin** [comment]
not sure if this is the same thing or a new/different problem.

https://buildkite.com/opstrace/prs/builds/5308#1592821d-d24e-4e9e-af57-dc5f53504061/5859-6759

```
[2021-08-03T07:16:27Z] 2021-08-03 07:16:18 +0000 [info]: #0 shutting down filter plugin type=:record_transformer plugin_id="object:3f8254185414"
--
  | [2021-08-03T07:16:27Z] r2021-08-03 07:16:18 +0000 [debug]: #0 preparing shutdown output plugin type=:loki plugin_id="object:3f8254b3a6bc"
  | [2021-08-03T07:16:27Z] l2021-08-03 07:16:18 +0000 [info]: #0 shutting down output plugin type=:loki plugin_id="object:3f8254b3a6bc"
  | [2021-08-03T07:16:27Z] x2021-08-03 07:16:18 +0000 [debug]: #0 calling after_shutdown on input plugin type=:tail plugin_id="object:3f82541baefc"
  | [2021-08-03T07:16:27Z] 2021-08-03 07:16:18 +0000 [debug]: #0 calling after_shutdown on filter plugin type=:record_transformer plugin_id="object:3f8254185414"
  | [2021-08-03T07:16:27Z] 2021-08-03 07:16:18 +0000 [debug]: #0 calling after_shutdown on output plugin type=:loki plugin_id="object:3f8254b3a6bc"
  | [2021-08-03T07:16:27Z] f2021-08-03 07:16:18 +0000 [debug]: #0 closing input plugin type=:tail plugin_id="object:3f82541baefc"
  | [2021-08-03T07:16:27Z] u2021-08-03 07:16:18 +0000 [debug]: #0 closing filter plugin type=:record_transformer plugin_id="object:3f8254185414"
  | [2021-08-03T07:16:27Z] g2021-08-03 07:16:18 +0000 [debug]: #0 closing output plugin type=:loki plugin_id="object:3f8254b3a6bc"
  | [2021-08-03T07:16:27Z] �2021-08-03 07:16:18 +0000 [debug]: #0 closing buffer instance=69828994591020
  | [2021-08-03T07:16:27Z] 2021-08-03 07:16:18 +0000 [debug]: #0 calling terminate on input plugin type=:tail plugin_id="object:3f82541baefc"
  | [2021-08-03T07:16:27Z] �2021-08-03 07:16:18 +0000 [debug]: #0 calling terminate on filter plugin type=:record_transformer plugin_id="object:3f8254185414"
  | [2021-08-03T07:16:27Z] 2021-08-03 07:16:18 +0000 [debug]: #0 calling terminate on output plugin type=:loki plugin_id="object:3f8254b3a6bc"
  | [2021-08-03T07:16:27Z] Z2021-08-03 07:16:18 +0000 [info]: fluent/log.rb:329:info: Worker 0 finished with status 0
  | [2021-08-03T07:16:27Z]
  | [2021-08-03T07:16:27Z] 2021-08-03T07:16:27.519Z info: Enter Loki query loop, wait for expected result, deadline 30 s.
  | [2021-08-03T07:16:27Z] Query parameters: {
  | [2021-08-03T07:16:27Z]   "direction": "BACKWARD",
  | [2021-08-03T07:16:27Z]   "end": "1627978587518000000",
  | [2021-08-03T07:16:27Z]   "limit": "1000",
  | [2021-08-03T07:16:27Z]   "query": "{indexfieldname=\"MRtzq\"}",
  | [2021-08-03T07:16:27Z]   "start": "1627971387518000000"
  | [2021-08-03T07:16:27Z] }
  | [2021-08-03T07:16:45Z] 2021-08-03T07:16:45.595Z info: waitForLokiQueryResult() loop: http request failed: Timeout awaiting 'request' for 5000ms -- ignore, proceed with next iteration
  | [2021-08-03T07:17:03Z] 2021-08-03T07:17:03.673Z info: waitForLokiQueryResult() loop: http request failed: Timeout awaiting 'request' for 5000ms -- ignore, proceed with next iteration
  | [2021-08-03T07:17:03Z] 2021-08-03T07:17:03.673Z error: query deadline hit
  | [2021-08-03T07:17:03Z]     1) insert w/ cntnrzd FluentD(loki plugin), then query
  | [2021-08-03T07:17:03Z] 2021-08-03T07:17:03.698Z info: log file content (fluentbit tail input):
  | [2021-08-03T07:17:03Z] aaaaaaa
  | [2021-08-03T07:17:03Z] bbbbbb
  | [2021-08-03T07:17:03Z] cccccccc
```

**Comment by nickbp** [comment]
It looks like this happened once in June and not again since. The August sample looks like it might be something else - not a delete error.
