### ISSUE TITLE
GCP CI run failed with Received 504 `Unable to generate access token; IAM returned`

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#191]
**Describe the bug**

https://buildkite.com/opstrace/scheduled-main-builds/builds/1387#306166aa-291c-4b5c-b131-15c57c73924e/2219-4226
```
[2020-12-18T00:37:11Z]   16 passing (43s)
[2020-12-18T00:37:11Z]   2 failing
[2020-12-18T00:37:11Z]
[2020-12-18T00:37:11Z]   1) Loki API test suite
[2020-12-18T00:37:11Z]        short dummystream insert, validate via query:
[2020-12-18T00:37:11Z]      SyntaxError: Unexpected token G in JSON at position 0
[2020-12-18T00:37:11Z]       at JSON.parse (<anonymous>)
[2020-12-18T00:37:11Z]       at queryLoki (testutils/logs.ts:84:15)
[2020-12-18T00:37:11Z]       at runMicrotasks (<anonymous>)
[2020-12-18T00:37:11Z]       at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2020-12-18T00:37:11Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:134:20)
[2020-12-18T00:37:11Z]       at DummyStream.fetchAndValidate (loki-node-client-tools/dummystream.ts:440:18)
[2020-12-18T00:37:11Z]       at Context.<anonymous> (test_loki_log_ingest_api.ts:544:5)
[2020-12-18T00:37:11Z] 
[2020-12-18T00:37:11Z]   2) Loki API test suite
[2020-12-18T00:37:11Z]        long dummystream insert, validate via query:
[2020-12-18T00:37:11Z]      SyntaxError: Unexpected token G in JSON at position 0
[2020-12-18T00:37:11Z]       at JSON.parse (<anonymous>)
[2020-12-18T00:37:11Z]       at queryLoki (testutils/logs.ts:84:15)
[2020-12-18T00:37:11Z]       at runMicrotasks (<anonymous>)
[2020-12-18T00:37:11Z]       at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2020-12-18T00:37:11Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:134:20)
[2020-12-18T00:37:11Z]       at DummyStream.fetchAndValidate (loki-node-client-tools/dummystream.ts:440:18)
[2020-12-18T00:37:11Z]       at async Promise.all (index 1)
[2020-12-18T00:37:11Z]       at Context.<anonymous> (test_loki_log_ingest_api.ts:618:5)
```

Both tests failed with this message

```
[2020-12-18T00:36:35Z] 2020-12-18T00:36:35.197Z info: HTTP resp to GET(https://loki.default.bk-1387-f66-g.opstrace.io/loki/api/v1/query_range?query=%7Bdummystream%3D%22test-remote-qukcU%22%7D&direction=FORWARD&limit=20000&start=1608251794682000000&end=1608251794682020000):
[2020-12-18T00:36:35Z]   status: 500
[2020-12-18T00:36:35Z]   body[:500]: Get "https://storage.googleapis.com/storage/v1/b/bk-1387-f66-g-loki/o?alt=json&delimiter=%2F&pageToken=&prefix=index%2Fbk-1387-f66-g_loki_index_18614%2F&prettyPrint=false&projection=full&versions=false": compute: Received 504 `Unable to generate access token; IAM returned
[2020-12-18T00:36:35Z]
```

**Comment by sreis** [comment]
This seems to be a GCP issue:

https://cloud.google.com/storage/docs/json_api/v1/status-codes#504_Gateway_Timeout

```
This error is generated when there was difficulty reaching an internal service. It is not formatted with a JSON document. Please try again using truncated exponential backoff.
```

**Comment by sreis** [comment]
Another one https://buildkite.com/opstrace/scheduled-main-builds/builds/1390#a83a8a6a-288b-4e2b-8e31-f0097d31dd26/2250-2878

**Comment by jgehrcke** [comment]
Another one here: https://buildkite.com/opstrace/prs/builds/3319#54b80106-e554-42c4-9079-63d849484d10/2310-2940
Affected PR https://github.com/opstrace/opstrace/pull/182

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1401#2c25f6ca-5399-4793-9cf8-1263a68d7ce1/2206-4249

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1400#3816314a-433d-4bb0-aced-a117115bbf5a/2206-2839

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1398#1e377f10-bf64-4788-b997-ec82ce742a1b/2205-2838

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/3328#9d3b89de-f549-49ae-9975-29c3fc1da471/2268-4315

notably:
```
compute: Received 504 `Gateway Timeout
```
instead of
```
Received 504 `Unable to generate access token; IAM returned
```

**Comment by sreis** [comment]
IAM error again
```
[2020-12-22T12:23:55Z]   status: 500
[2020-12-22T12:23:55Z]   body[:500]: Get "https://storage.googleapis.com/storage/v1/b/bk-1414-48c-g-loki/o?alt=json&delimiter=%2F&pageToken=&prefix=index%2Fbk-1414-48c-g_loki_index_18618%2F&prettyPrint=false&projection=full&versions=false": compute: Received 504 `Unable to generate access token; IAM returned
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/1414#3a46f7fc-f603-451b-94c4-d08ee16d7b58/2231-2864

**Comment by sreis** [comment]
```
[2020-12-23T08:37:37Z] 2020-12-23T08:37:37.368Z info: HTTP resp to GET(https://loki.default.bk-1419-48c-g.opstrace.io/loki/api/v1/query_range?query=%7Bdummystream%3D%22test-remote-0_aXt%22%7D&direction=FORWARD&limit=20000&start=1608712656836000000&end=1608712656836020000):
[2020-12-23T08:37:37Z]   status: 500
[2020-12-23T08:37:37Z]   body[:500]: Get "https://storage.googleapis.com/storage/v1/b/bk-1419-48c-g-loki/o?alt=json&delimiter=%2F&pageToken=&prefix=index%2Fbk-1419-48c-g_loki_index_18619%2F&prettyPrint=false&projection=full&versions=false": compute: Received 504 `Unable to generate access token; IAM returned
[2020-12-23T08:37:37Z] `
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/1419#97c9d20a-52d3-49e7-9704-17b49600a6fe/2193-2827

**Comment by sreis** [comment]
```
[2020-12-24T12:38:02Z] 2020-12-24T12:38:02.498Z info: HTTP resp to GET(https://loki.default.bk-1426-017-g.opstrace.io/loki/api/v1/query_range?query=%7Bdummystream%3D%22test-remote-aGPrb%22%7D&direction=FORWARD&limit=20000&start=1608813481984000000&end=1608813481984020000):
[2020-12-24T12:38:02Z]   status: 500
[2020-12-24T12:38:02Z]   body[:500]: Get "https://storage.googleapis.com/storage/v1/b/bk-1426-017-g-loki/o?alt=json&delimiter=%2F&pageToken=&prefix=index%2Fbk-1426-017-g_loki_index_18620%2F&prettyPrint=false&projection=full&versions=false": compute: Received 504 `Unable to generate access token; IAM returned
[2020-12-24T12:38:02Z] `
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/1426#b451b05b-3292-4d5e-add5-0b2da765494a/2269-2903

**Comment by sreis** [comment]
```
[2020-12-26T20:36:36Z] 2020-12-26T20:36:36.230Z info: read token from /tmp/opstrace-bk-1440-0173481-1-gcp/tenant-api-token-default for url https://loki.default.bk-1440-017-g.opstrace.io/loki/api/v1/query_range
[2020-12-26T20:36:36Z] 2020-12-26T20:36:36.550Z info: HTTP resp to GET(https://loki.default.bk-1440-017-g.opstrace.io/loki/api/v1/query_range?query=%7Bdummystream%3D%22test-remote-3nkbr%22%7D&direction=FORWARD&limit=20000&start=1609014996022000000&end=1609014996022020000):
[2020-12-26T20:36:36Z]   status: 500
[2020-12-26T20:36:36Z]   body[:500]: Get "https://storage.googleapis.com/storage/v1/b/bk-1440-017-g-loki/o?alt=json&delimiter=%2F&pageToken=&prefix=index%2Fbk-1440-017-g_loki_index_18622%2F&prettyPrint=false&projection=full&versions=false": compute: Received 504 `Unable to generate access token; IAM returned
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/1440#256f663f-5132-4ced-9414-9501fb1e124c/2219-2853

**Comment by sreis** [comment]
```
[2020-12-26T20:36:36Z] 2020-12-26T20:36:36.230Z info: read token from /tmp/opstrace-bk-1440-0173481-1-gcp/tenant-api-token-default for url https://loki.default.bk-1440-017-g.opstrace.io/loki/api/v1/query_range
[2020-12-26T20:36:36Z] 2020-12-26T20:36:36.550Z info: HTTP resp to GET(https://loki.default.bk-1440-017-g.opstrace.io/loki/api/v1/query_range?query=%7Bdummystream%3D%22test-remote-3nkbr%22%7D&direction=FORWARD&limit=20000&start=1609014996022000000&end=1609014996022020000):
[2020-12-26T20:36:36Z]   status: 500
[2020-12-26T20:36:36Z]   body[:500]: Get "https://storage.googleapis.com/storage/v1/b/bk-1440-017-g-loki/o?alt=json&delimiter=%2F&pageToken=&prefix=index%2Fbk-1440-017-g_loki_index_18622%2F&prettyPrint=false&projection=full&versions=false": compute: Received 504 `Unable to generate access token; IAM returned
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/1440#256f663f-5132-4ced-9414-9501fb1e124c/2219-2853

**Comment by sreis** [comment]
```
[2020-12-29T12:35:53Z]   status: 500
[2020-12-29T12:35:53Z]   body[:500]: Get "https://storage.googleapis.com/storage/v1/b/bk-1456-189-g-loki/o?alt=json&delimiter=%2F&pageToken=&prefix=index%2Fbk-1456-189-g_loki_index_18625%2F&prettyPrint=false&projection=full&versions=false": compute: Received 504 `Unable to generate access token; IAM returned
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/1456#db420474-ef98-40f9-9be7-21085d35c8d0/2193-2827

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1490#dff26dce-5b9f-486d-ae8a-9905bff6cbc5/2218-4301

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1506#8f999eaf-26df-4d73-8b76-3f0d9537dff0/2302-4384

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1551#d7e7d00e-cc9b-4f96-9590-c0081db7619f/2693-4737

```
[2021-01-14T04:44:11Z]   status: 500
[2021-01-14T04:44:11Z]   body[:500]: Get "https://storage.googleapis.com/storage/v1/b/bk-1551-3f4-g-loki/o?alt=json&delimiter=%2F&pageToken=&prefix=index%2Fbk-1551-3f4-g_loki_index_18640%2F&prettyPrint=false&projection=full&versions=false": compute: Received 504 `Unable to generate access token; IAM returned
[2021-01-14T04:44:11Z] `
```
