### ISSUE TITLE
ci instability: loki query: Timeout awaiting 'request' for 60000ms

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#196]
```
[2020-12-20T12:48:45Z]   17 passing (1m)
[2020-12-20T12:48:45Z]   1 failing
[2020-12-20T12:48:45Z]
[2020-12-20T12:48:45Z]   1) Loki API test suite
[2020-12-20T12:48:45Z]        short dummystream insert, validate via query:
[2020-12-20T12:48:45Z]      RequestError: Timeout awaiting 'request' for 60000ms
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/1402#0de7d3fe-da0f-4226-a317-bfc5bf2d5421/2801-4864

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1456#a2ba52c3-41b3-45f8-8e81-aee08a209782/1965-4034

```
[2020-12-29T12:52:08Z]   1) Loki API test suite
[2020-12-29T12:52:08Z]        short dummystream insert, validate via query:
[2020-12-29T12:52:08Z]      RequestError: Timeout awaiting 'request' for 60000ms
```

**Comment by sreis** [comment]
https://buildkite.com/opstrace/prs/builds/3385#8f175cff-7d2e-4610-8ec1-28c61c644e9e/1744-3817

```
[2021-01-12T14:13:28Z]   1) system logs test suite
[2021-01-12T14:13:28Z]        check loki ingester logs:
[2021-01-12T14:13:28Z]      RequestError: Timeout awaiting 'request' for 60000ms
```

**Comment by triclambert** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1636#6a374349-e251-43b0-aa08-885d199f873c/3453-5510

```
[2021-01-27T12:49:14Z]   18 passing (1m)
[2021-01-27T12:49:14Z]   1 failing
[2021-01-27T12:49:14Z]
[2021-01-27T12:49:14Z]   1) Loki API test suite
[2021-01-27T12:49:14Z]        short dummystream insert, validate via query:
[2021-01-27T12:49:14Z]      RequestError: Timeout awaiting 'request' for 60000ms
```

**Comment by jgehrcke** [comment]
```
[2021-02-06T00:41:13Z]   18 passing (2m)
[2021-02-06T00:41:13Z]   1 failing
[2021-02-06T00:41:13Z]
[2021-02-06T00:41:13Z]   1) Loki API test suite
[2021-02-06T00:41:13Z]        short dummystream insert, validate via query:
[2021-02-06T00:41:13Z]      RequestError: Timeout awaiting 'request' for 60000ms
[2021-02-06T00:41:13Z]       at ClientRequest.<anonymous> (/build/node_modules/got/dist/source/core/index.js:953:65)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/1694#0cd50066-223a-475c-be60-1b78b5d8d8cc/3210-5338

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2068#f9d25e6a-9e59-481a-8352-170c8fd2f8df/1403-3069

```
[2021-04-08T12:50:22Z]   1) Loki API test suite
[2021-04-08T12:50:22Z]        short dummystream insert, validate via query:
[2021-04-08T12:50:22Z]      RequestError: Timeout awaiting 'request' for 60000ms
```

**Comment by sreis** [comment]
```
[2021-07-20T13:11:14Z] [92m [0m[32m 22 passing[0m[90m (20m)[0m
[2021-07-20T13:11:14Z] [36m [0m[36m 4 pending[0m
[2021-07-20T13:11:14Z] [31m  1 failing[0m
[2021-07-20T13:11:14Z] 
[2021-07-20T13:11:14Z] [0m  1) system logs test suite
[2021-07-20T13:11:14Z]        check loki ingester logs:
[2021-07-20T13:11:14Z] [0m[31m     Error: Expectation not fulfilled within 30 s[0m[90m
[2021-07-20T13:11:14Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:265:9)
[2021-07-20T13:11:14Z]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-07-20T13:11:14Z]       at query (test_systemlogs.ts:52:20)
[2021-07-20T13:11:14Z]       at Context.<anonymous> (test_systemlogs.ts:66:5)
[2021-07-20T13:11:14Z] [0m
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2700 (buildkite logs are truncated)

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/upgrade-tests/builds/1199#44c6e03d-5ff2-4ab1-b33e-d10f5ea8cbf6/628-2464

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/upgrade-tests/builds/1200#540a7598-fe56-4711-a0de-0f4dae1ec0d5/2324-4179
