### ISSUE TITLE
debuggability issue: TS-based line numbers missing in stack traces (x.js:0 instead)

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#236]
Example from today:
```
[2021-01-05T13:36:02Z] 2021-01-05T13:36:02.322Z error: error during cluster teardown (attempt 5):
[2021-01-05T13:36:02Z] Error: fork: argument of type [context, fn] has undefined or null `fn`
[2021-01-05T13:36:02Z]     at check (/snapshot/build/node_modules/@redux-saga/core/dist/io-1d6eccda.js:37:11)
[2021-01-05T13:36:02Z]     at validateFnDescriptor (/snapshot/build/node_modules/@redux-saga/core/dist/io-1d6eccda.js:471:5)
[2021-01-05T13:36:02Z]     at Object.fork (/snapshot/build/node_modules/@redux-saga/core/dist/io-1d6eccda.js:559:5)
[2021-01-05T13:36:02Z]     at destroyAWSInfra (/snapshot/build/node_modules/@opstrace/uninstaller/build/aws.js:0)
[2021-01-05T13:36:02Z]     at destroyAWSInfra.next (<anonymous>)
[2021-01-05T13:36:02Z]     at next (/snapshot/build/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
```

The specific problem in this stack trace is the `build/aws.js:0`.

We have previously tracked this internally here: https://github.com/opstrace/opstrace-prelaunch/issues/1186

One question that arose during the past year was whether or not we use `source-map-support` correctly.

Here is one particular approach that I did try (quote from Sept 2020)

I tried with the following diff:
```
$ git diff
diff --git a/lib/aws/src/index.ts b/lib/aws/src/index.ts
index 4067d024..ff56e6f2 100644
--- a/lib/aws/src/index.ts
+++ b/lib/aws/src/index.ts
@@ -14,6 +14,8 @@
  * limitations under the License.
  */
 
+import "source-map-support/register";
+
 export * from "./address";
 export * from "./autoScalingGroup";
 export * from "./bucket";
diff --git a/packages/installer/src/aws.ts b/packages/installer/src/aws.ts
index 24ce118e..ee3eea2e 100644
--- a/packages/installer/src/aws.ts
+++ b/packages/installer/src/aws.ts
@@ -14,6 +14,8 @@
  * limitations under the License.
  */
 
+import "source-map-support/register";
+
 import AWS from "aws-sdk";
 import { call, fork, join } from "redux-saga/effects";
 import {
diff --git a/packages/installer/src/index.ts b/packages/installer/src/index.ts
index 02dc32fb..d0d0cd34 100644
--- a/packages/installer/src/index.ts
+++ b/packages/installer/src/index.ts
@@ -14,6 +14,8 @@
  * limitations under the License.
  */
 
+import "source-map-support/register";
+
 import got, { Response as GotResponse } from "got";
 
 import { fork, call, race, delay, cancel } from "redux-saga/effects";
```

folllowed by from-scratch tsc build and pkg binary build (`make dependencies`) and still got (dummy bug introduced just for this)
```
2020-09-29T17:33:11.371Z error: error during cluster creation (attempt 1):
TypeError: Cannot read property 'VpcId' of undefined
    at ensureAWSInfraExists (/snapshot/opstrace/node_modules/@opstrace/installer/build/aws.js:0)
    at ensureAWSInfraExists.next (<anonymous>)
```

Involved are the cli package, the installer package, and the aws lib. With the above's patch, `import "source-map-support/register"` was part of the `index.ts` of these three npm packages.

I even put one additional import statement into the offending file (where the code blows up: `packages/installer/src/aws.ts`)

:man_shrugging:

**Comment by jgehrcke** [comment]
An important insight from previous investigations was that the pkg-based single binary CLI build _adds_ to the problem Quoting from Oct 14 2020 from internal issue 1186:

Without pkg build:
```
2020-10-14T10:15:36.932Z error: error during cluster creation (attempt 1):
Error: TS LINE NUMBER PLEASE
    at ensureAWSInfraExists (/home/jp/dev/opstrace/packages/installer/src/aws.ts:88:11)
    at ensureAWSInfraExists.next (<anonymous>)
...
```

With pkg build:
```
2020-10-14T10:20:08.694Z error: error during cluster creation (attempt 1):
Error: TS LINE NUMBER PLEASE
    at ensureAWSInfraExists (/snapshot/opstrace/node_modules/@opstrace/installer/build/aws.js:0)
    at ensureAWSInfraExists.next (<anonymous>)
...
```

That is, the pkg build adds complication.

**Comment by jgehrcke** [comment]
We left a comment on this thread: https://github.com/vercel/pkg/issues/596

**Comment by jgehrcke** [comment]
~Quoting myself from earlier the year, still behind these statements:

Notes:
- I don't quite like how `node-source-map` appears to be a niche product (especially w.r.t. its documentation) but there are options for it we can try: https://github.com/evanw/node-source-map-support#options
- `ts-node` tries to first-class and address the problem of retaining source line information properly internally: https://www.npmjs.com/package/ts-node (seems to work well within the test runner where we use for test-remote, i.e. `ts-node+mochajs` seem to play well together).
- It's genuinely disappointing how this topic is underground. It's buried in GitHub issues all over the place, lacking a simple, centrally maintained solution: https://github.com/NativeScript/nativescript-cli/issues/2417, https://github.com/whitecolor/ts-node-dev/issues/44, ...

How are others dealing with this challenge?

I found https://www.techatbloomberg.com/blog/10-insights-adopting-typescript-at-scale/ quite interesting in November.

> In addition to scale, something that makes this integration of TypeScript unique is that we have our own JavaScript runtime environment. This means that, in addition to well-known JavaScript host environments, such as browsers and Node, we also embed the V8 engine and Chromium directly to create our own JavaScript platform. The upside of this situation is that we can offer a simple developer experience in which TypeScript is supported directly by our platform and package ecosystem

So, they have their own runtime. And then, here we go (emphasis mine):

>  It also means that engineers can focus on writing code rather than needing to figure out how to make TypeScript play nicely with a bundler or test framework. **DevTools and error stacks use sourcemaps correctly. Tests can be written in TypeScript and code coverage is accurately expressed in terms of the original TypeScript code. It just works.**

I want that, too.
