### ISSUE TITLE
ci instability: yarn package install fails on playwright setup, with  Error: unexpected end of file (at Zlib.zlibOnError)

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#275]
preamble failed during `make lint-codebase` at execution of `yarn --frozen-lockfile`:

```
[5/5] Building fresh packages...
 
 
error /build/node_modules/playwright: Command failed.
[2021-01-20T12:17:18Z] Exit code: 1
[2021-01-20T12:17:18Z] Command: node install.js
[2021-01-20T12:17:18Z] Arguments:
[2021-01-20T12:17:18Z] Directory: /build/node_modules/playwright
[2021-01-20T12:17:18Z] Output:
[2021-01-20T12:17:18Z] chromium v833159 downloaded to /build/.cache/ms-playwright/chromium-833159
[2021-01-20T12:17:18Z]
[2021-01-20T12:17:18Z] firefox v1221 downloaded to /build/.cache/ms-playwright/firefox-1221
[2021-01-20T12:17:18Z]
[2021-01-20T12:17:18Z] (node:1704) UnhandledPromiseRejectionWarning: Error: unexpected end of file
[2021-01-20T12:17:18Z]     at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
 ```

This is sad because playwright is only needed in test-remote.

https://buildkite.com/opstrace/prs/builds/3428#65f25e5e-6684-485d-a030-2f43816f198a/776-815

**Comment by jgehrcke** [comment]
Might have to do with https://github.com/microsoft/playwright/issues/5056

**Comment by jgehrcke** [comment]
Might affect all builds right now. Investigating.

**Comment by jgehrcke** [comment]
seems to have been fixed by https://github.com/opstrace/opstrace/pull/276.

**Comment by jgehrcke** [comment]
reported by @sreis via https://github.com/opstrace/opstrace/issues/694

```
[2021-05-06T08:07:52Z] Command: node install.js
[2021-05-06T08:07:52Z] Arguments:
[2021-05-06T08:07:52Z] Directory: /build/node_modules/playwright
[2021-05-06T08:07:52Z] Output:
[2021-05-06T08:07:52Z] (node:1965) UnhandledPromiseRejectionWarning: Error: Failed to download chromium, caused by
[2021-05-06T08:07:52Z] Error: unexpected end of file
[2021-05-06T08:07:52Z]     at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
[2021-05-06T08:07:52Z]     at /build/node_modules/playwright/lib/install/installer.js:130:19
[2021-05-06T08:07:52Z]     at async validateCache (/build/node_modules/playwright/lib/install/installer.js:129:9)
[2021-05-06T08:07:52Z]     at async installBrowsersWithProgressBar (/build/node_modules/playwright/lib/install/installer.js:80:9)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2235#84a7cb41-c757-410d-b2e1-0420a0fe47b5/1709-1758

**Comment by jgehrcke** [comment]
error is thrown here: https://github.com/microsoft/playwright/blob/9cd89ae0525b327ce435ae3e4aadcba035621ee9/src/install/installer.ts#L111

**Comment by jgehrcke** [comment]
I opened this issue here in january: https://github.com/microsoft/playwright/issues/5066

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/4109#df9513c7-8cca-4777-b8e8-607d8c742fe5/3073-3121

**Comment by jgehrcke** [comment]
related to https://github.com/opstrace/opstrace/issues/696

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2357#66b86dc1-9d7c-452d-a80c-fe554a8c5c5f/3042-3083
```
[2021-05-25T12:25:28Z] (node:4648) UnhandledPromiseRejectionWarning: Error: Failed to download chromium, caused by
[2021-05-25T12:25:28Z] Error: unexpected end of file
[2021-05-25T12:25:28Z]     at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
[2021-05-25T12:25:28Z]     at /build/node_modules/playwright/lib/install/installer.js:130:19
[2021-05-25T12:25:28Z]     at async validateCache (/build/node_modules/playwright/lib/install/installer.js:129:9)
[2021-05-25T12:25:28Z]     at async installBrowsersWithProgressBar (/build/node_modules/playwright/lib/install/installer.js:80:9)
[2021-05-25T12:25:28Z] (Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by jgehrcke** [comment]
```
[2021-06-14T12:03:44Z] Playwright build of chromium v888113 downloaded to /build/.cache/ms-playwright/chromium-888113
[2021-06-14T12:03:44Z] (node:4818) UnhandledPromiseRejectionWarning: Error: Failed to download firefox, caused by
[2021-06-14T12:03:44Z] Error: unexpected end of file
[2021-06-14T12:03:44Z]     at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
```
https://buildkite.com/opstrace/prs/builds/4628#16a54a65-ef9d-4111-b87c-a294a081c446/3122-3170

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2498#3c69e7ca-29eb-499c-b811-8b56be5f9318/3224-3273

**Comment by nickbp** [comment]
Had several instances in May/June and nothing since, so may have been resolved in the meantime
