### ISSUE TITLE
make test-remote-ui:  libxshmfence.so.1 is missing

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#280]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1599#b407cc9d-57d5-4794-a8e7-56a69a4aded5/4309-4443
```
[2021-01-21T08:36:02Z] 2021-01-21T08:36:02.561Z info: chromium.launch()
[2021-01-21T08:36:02Z]   pw:api => browserType.launch started +0ms
[2021-01-21T08:36:02Z]   pw:api <= browserType.launch failed +134ms
[2021-01-21T08:36:02Z]     1) "before all" hook for "playwright"
[2021-01-21T08:36:02Z] 2021-01-21T08:36:02.697Z info: suite teardown
[2021-01-21T08:36:02Z] 2021-01-21T08:36:02.697Z info: browser.close()
[2021-01-21T08:36:02Z]     2) "after all" hook for "playwright"
[2021-01-21T08:36:02Z]
[2021-01-21T08:36:02Z]
[2021-01-21T08:36:02Z]   0 passing (143ms)
[2021-01-21T08:36:02Z]   2 failing
[2021-01-21T08:36:02Z]
[2021-01-21T08:36:02Z]   1) test_ui_with_headless_browser
[2021-01-21T08:36:02Z]        "before all" hook for "playwright":
[2021-01-21T08:36:02Z]      browserType.launch: Host system is missing dependencies!
[2021-01-21T08:36:02Z] 
[2021-01-21T08:36:02Z]   Missing libraries are:
[2021-01-21T08:36:02Z]       libxshmfence.so.1
[2021-01-21T08:36:02Z] 
[2021-01-21T08:36:02Z] Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
[2021-01-21T08:36:02Z]    
[2021-01-21T08:36:02Z]       at Connection.sendMessageToServer (node_modules/playwright/lib/client/connection.js:69:15)
[2021-01-21T08:36:02Z]       at Proxy.<anonymous> (node_modules/playwright/lib/client/channelOwner.js:44:61)
[2021-01-21T08:36:02Z]       at /test/node_modules/playwright/lib/client/browserType.js:61:73
[2021-01-21T08:36:02Z]       at BrowserType._wrapApiCall (node_modules/playwright/lib/client/channelOwner.js:72:34)
[2021-01-21T08:36:02Z]       at BrowserType.launch (node_modules/playwright/lib/client/browserType.js:52:21)
[2021-01-21T08:36:02Z]       at Context.<anonymous> (test_ui.ts:46:30)
[2021-01-21T08:36:02Z]       at processImmediate (internal/timers.js:461:21)
[2021-01-21T08:36:02Z] 
[2021-01-21T08:36:02Z]   2) test_ui_with_headless_browser
[2021-01-21T08:36:02Z]        "after all" hook for "playwright":
[2021-01-21T08:36:02Z]      TypeError: Cannot read property 'close' of undefined
[2021-01-21T08:36:02Z]       at Context.<anonymous> (test_ui.ts:61:19)
[2021-01-21T08:36:02Z]       at processImmediate (internal/timers.js:461:21)
[2021-01-21T08:36:02Z] 
[2021-01-21T08:36:02Z]
[2021-01-21T08:36:02Z]
```

**Comment by jgehrcke** [comment]
A fix is on https://github.com/opstrace/opstrace/pull/281.
