### ISSUE TITLE
ci instability: test-remote-ui : page.goto: net::ERR_NETWORK_CHANGED at https://<clustername>.opstrace.io

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#340]
```
[2021-02-09T08:46:39Z] 2021-02-09T08:46:39.005Z info: chromium.launch()
[2021-02-09T08:46:39Z]   pw:api => browserType.launch started +0ms
[2021-02-09T08:46:39Z]   pw:api <= browserType.launch succeeded +223ms
[2021-02-09T08:46:39Z] 2021-02-09T08:46:39.228Z info: suite setup done
[2021-02-09T08:46:39Z] 2021-02-09T08:46:39.229Z info: browser.newContext()
[2021-02-09T08:46:39Z]   pw:api => browser.newContext started +1ms
[2021-02-09T08:46:39Z]   pw:api <= browser.newContext succeeded +4ms
[2021-02-09T08:46:39Z] 2021-02-09T08:46:39.233Z info: context.newPage()
[2021-02-09T08:46:39Z]   pw:api => browserContext.newPage started +0ms
[2021-02-09T08:46:39Z]   pw:api <= browserContext.newPage succeeded +35ms
[2021-02-09T08:46:39Z] 2021-02-09T08:46:39.268Z info: page.goto(https://bk-1714-ba8-g.opstrace.io)
[2021-02-09T08:46:39Z]   pw:api => page.goto started +0ms
[2021-02-09T08:46:39Z]   pw:api navigating to "https://bk-1714-ba8-g.opstrace.io", waiting until "load" +2ms
[2021-02-09T08:46:39Z]   pw:api <= page.goto failed +195ms
[2021-02-09T08:46:39Z]     1) playwright
[2021-02-09T08:46:39Z] 2021-02-09T08:46:39.466Z info: suite teardown
[2021-02-09T08:46:39Z] 2021-02-09T08:46:39.466Z info: browser.close()
[2021-02-09T08:46:39Z]   pw:api => browser.close started +2ms
[2021-02-09T08:46:39Z]   pw:api <= browser.close succeeded +27ms
[2021-02-09T08:46:39Z] 2021-02-09T08:46:39.494Z info: suite teardown done
[2021-02-09T08:46:39Z]
[2021-02-09T08:46:39Z]
[2021-02-09T08:46:39Z]   0 passing (496ms)
[2021-02-09T08:46:39Z]   1 failing
[2021-02-09T08:46:39Z]
[2021-02-09T08:46:39Z]   1) test_ui_with_headless_browser
[2021-02-09T08:46:39Z]        playwright:
[2021-02-09T08:46:39Z]      page.goto: net::ERR_NETWORK_CHANGED at https://bk-1714-ba8-g.opstrace.io
[2021-02-09T08:46:39Z] =========================== logs ===========================
[2021-02-09T08:46:39Z] navigating to "https://bk-1714-ba8-g.opstrace.io", waiting until "load"
[2021-02-09T08:46:39Z] ============================================================
[2021-02-09T08:46:39Z] Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
[2021-02-09T08:46:39Z]    
[2021-02-09T08:46:39Z]       at Connection.sendMessageToServer (/build/node_modules/playwright/lib/client/connection.js:69:15)
[2021-02-09T08:46:39Z]       at Proxy.<anonymous> (/build/node_modules/playwright/lib/client/channelOwner.js:44:61)
[2021-02-09T08:46:39Z]       at /build/node_modules/playwright/lib/client/frame.js:80:71
[2021-02-09T08:46:39Z]       at Frame._wrapApiCall (/build/node_modules/playwright/lib/client/channelOwner.js:72:34)
[2021-02-09T08:46:39Z]       at Frame.goto (/build/node_modules/playwright/lib/client/frame.js:78:21)
[2021-02-09T08:46:39Z]       at /build/node_modules/playwright/lib/client/page.js:270:60
[2021-02-09T08:46:39Z]       at Page._attributeToPage (/build/node_modules/playwright/lib/client/page.js:205:20)
[2021-02-09T08:46:39Z]       at Page.goto (/build/node_modules/playwright/lib/client/page.js:270:21)
[2021-02-09T08:46:39Z]       at Context.<anonymous> (test_ui.ts:72:16)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/1714#0050814c-71f4-4c11-9ff3-d66d32b25599/5432-5501

**Comment by jgehrcke** [comment]
ERR_NETWORK_CHANGED in the context of Chromium: https://superuser.com/a/1302316/178217

**Comment by jgehrcke** [comment]
```
[2021-06-28T17:32:03Z]   pw:api <= browser.close succeeded +109ms
[2021-06-28T17:32:03Z] 2021-06-28T17:32:03.273Z info: suite teardown done
[2021-06-28T17:32:03Z]
[2021-06-28T17:32:03Z]
[2021-06-28T17:32:03Z]   0 passing (4s)
[2021-06-28T17:32:03Z]   1 failing
[2021-06-28T17:32:03Z]
[2021-06-28T17:32:03Z]   1) test_ui_api
[2021-06-28T17:32:03Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-06-28T17:32:03Z]      page.goto: net::ERR_NETWORK_CHANGED at https://schedul-bk-2568-620-g.opstrace.io
[2021-06-28T17:32:03Z] =========================== logs ===========================
[2021-06-28T17:32:03Z] navigating to "https://schedul-bk-2568-620-g.opstrace.io", waiting until "load"
[2021-06-28T17:32:03Z] ============================================================
[2021-06-28T17:32:03Z] Note: use DEBUG=pw:api environment variable to capture Playwright logs.
[2021-06-28T17:32:03Z]   Error: 
[2021-06-28T17:32:03Z]       at Object.captureStackTrace 
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2568#783a7e37-e36d-45b6-ab0c-8f848d1ca93f/6342-6420

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2637#b094d2d3-64ff-4c06-9941-90628b54b5aa/1347-1440

```
[2021-07-10T01:14:56Z]   1) test_ui_api
[2021-07-10T01:14:56Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-10T01:14:56Z]      page.goto: net::ERR_NETWORK_CHANGED at https://schedul-bk-2637-48f-a.opstrace.io
[2021-07-10T01:14:56Z] =========================== logs ===========================
[2021-07-10T01:14:56Z] navigating to "https://schedul-bk-2637-48f-a.opstrace.io", waiting until "load"
[2021-07-10T01:14:56Z] ============================================================
[2021-07-10T01:14:56Z] Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2672#2209a4f8-7a92-4f20-af2c-7bcc6e3c3bf9/7352-7445

```
[2021-07-15T21:03:38Z]   1) test_ui_api
[2021-07-15T21:03:38Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-15T21:03:38Z]      page.goto: net::ERR_NETWORK_CHANGED at https://schedul-bk-2672-696-g.opstracegcp.com
[2021-07-15T21:03:38Z] =========================== logs ===========================
[2021-07-15T21:03:38Z] navigating to "https://schedul-bk-2672-696-g.opstracegcp.com", waiting until "load"
[2021-07-15T21:03:38Z] ============================================================
[2021-07-15T21:03:38Z] Note: use DEBUG=pw:api environment variable to capture Playwright logs.
[2021-07-15T21:03:38Z]   Error: 
```

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2715#c6d95335-b7a3-4390-8c46-3213543c09d6/7534-7626

```
[2021-07-23T00:44:37Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-23T00:44:37Z]      page.goto: net::ERR_NETWORK_CHANGED at https://schedul-bk-2715-2d8-g.opstracegcp.com/
[2021-07-23T00:44:37Z] =========================== logs ===========================
[2021-07-23T00:44:37Z] navigating to "https://schedul-bk-2715-2d8-g.opstracegcp.com/", waiting until "load"
[2021-07-23T00:44:37Z] ============================================================
[2021-07-23T00:44:37Z]       at performLoginFlow (test_ui_api.ts:95:14)
[2021-07-23T00:44:37Z]       at Context.<anonymous> (test_ui_api.ts:222:5)
```

**Comment by jgehrcke** [comment]
in test-browser:
```
[2021-07-25T01:24:53Z] [31m  1) tests/5J8m3_tenant.spec.ts:35:3 › [Pixel-4] after auth0 authentication user can create a new Tenant [39m
[2021-07-25T01:24:53Z] 
[2021-07-25T01:24:53Z]     Pending operations:
[2021-07-25T01:24:53Z]       - page.hover at tests/5J8m3_tenant.spec.ts:30:16
[2021-07-25T01:24:53Z] 
[2021-07-25T01:24:53Z]     page.goto: net::ERR_NETWORK_CHANGED at https://pr-upgr-bk-2727-a0f-g.opstrace.io
[2021-07-25T01:24:53Z]     =========================== logs ===========================
[2021-07-25T01:24:53Z]     navigating to "https://pr-upgr-bk-2727-a0f-g.opstrace.io", waiting until "load"
[2021-07-25T01:24:53Z]     ============================================================
[2021-07-25T01:24:53Z]     Note: use DEBUG=pw:api environment variable to capture Playwright logs.
[2021-07-25T01:24:53Z] 
[2021-07-25T01:24:53Z]     [0m [90m 1 |[39m [90m/**[39m[0m
[2021-07-25T01:24:53Z]     [0m [90m 2 |[39m [90m * Copyright 2021 Opstrace, Inc.[39m[0m
[2021-07-25T01:24:53Z]     [0m [90m 3 |[39m [90m *[39m[0m
[2021-07-25T01:24:53Z] 
```

**Comment by jgehrcke** [comment]
```
[2021-07-27T05:50:42Z]   0 passing (2s)
[2021-07-27T05:50:42Z]   1 failing
[2021-07-27T05:50:42Z]
[2021-07-27T05:50:42Z]   1) test_ui_api
[2021-07-27T05:50:42Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-27T05:50:42Z]      page.goto: net::ERR_NETWORK_CHANGED at https://pr-upgr-bk-5204-6f6-g.opstrace.io/
[2021-07-27T05:50:42Z] =========================== logs ===========================
[2021-07-27T05:50:42Z] navigating to "https://pr-upgr-bk-5204-6f6-g.opstrace.io/", waiting until "load"
[2021-07-27T05:50:42Z] ============================================================
[2021-07-27T05:50:42Z]       at performLoginFlow (test_ui_api.ts:95:14)
[2021-07-27T05:50:42Z]       at Context.<anonymous> (test_ui_api.ts:222:5)
```

**Comment by jgehrcke** [comment]
Let's make this ticket specific to test_ui_api

**Comment by nickbp** [comment]
Lots of instances in July and then nothing since, smells like something was fixed/changed
