### ISSUE TITLE
test-remote: dd_api_run_agent_container_query_sysuptime -- log needle not found within deadline ("ack race")

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#405]
```
[2021-02-22T12:36:38Z]   19 passing (3m)
[2021-02-22T12:36:38Z]   1 failing
[2021-02-22T12:36:38Z]
[2021-02-22T12:36:38Z]   1) DD API test suite
[2021-02-22T12:36:38Z]        dd_api_run_agent_container_query_sysuptime:
[2021-02-22T12:36:38Z]      Error: DD agent container setup failed: deadline hit waiting for log needle
[2021-02-22T12:36:38Z]       at startDDagentContainer (test_dd.ts:215:13)
[2021-02-22T12:36:38Z]       at runMicrotasks (<anonymous>)
[2021-02-22T12:36:38Z]       at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-02-22T12:36:38Z]       at Context.<anonymous> (test_dd.ts:324:32)
[2021-02-22T12:36:38Z] 
[2021-02-22T12:36:38Z]
```

deadline hit while waiting for expected log output:

```
[2021-02-22T12:34:08Z] 2021-02-22T12:34:08.622Z info: Waiting for needle to appear in container log, deadline in 120 s. Needle: Successfully posted payload to "https://dd.default.bk-1795-18b-g.opstrace.io/api/v1/series
[2021-02-22T12:36:08Z] 2021-02-22T12:36:08.680Z info: deadline hit
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/1795#b5b0422c-ed53-48d1-8858-f057c5904a65/2194-4638

**Comment by jgehrcke** [comment]
another one here:

https://buildkite.com/opstrace/scheduled-main-builds/builds/1795#ad913db6-48df-450d-b40a-bd202c2257cf/1783-4227


```
[2021-02-22T12:49:34Z] W2021-02-22 12:49:02 UTC | CORE | ERROR | (pkg/forwarder/worker.go:178 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://dd.default.bk-1795-18b-a.opstrace.io/api/v1/series?api_key=*************************XVCJ9.eyJpYXQiOjE2MTM5OTY0MDQsImV4cCI6MTkyOTU3MjQwNCwiYXVkIjoib3BzdHJhY2UtY2x1c3Rlci1iay0xNzk1LTE4Yi1hIiwiaXNzIjoib3BzdHJhY2UtY2xpIiwic3ViIjoidGVuYW50LWRlZmF1bHQifQ.O8yIa47xD0kWLF_wwTYtzS-QrcF42BJZCtgXI8LKQxZf17k71lCPuKicMk13RL4BW0rYVKFxhnkQXk2d9AxUbO0jLP5R5OIscHxzb0s0x0Ju_pB6_baQ8KvARXCGdEfa0go09s2OqmgsLYu2MvU0I2eRsODa-IODtOqSydxIt6Yt82L9ap51Jq09HrCNeGlya9WhofodJtIpTZKB1nUYXDE5Nz0jaLfxx8zhkikSUvR2WK1LISyi8oEyP3G9oN8qafhbL0dQad9flN6_AbnSyHEMtWJufyVxmP1CxzHGRYpqt-0PCMEIq0mnE8RdmtPRzsEU6A8hstujj1Ljlhfljg": read tcp 172.17.0.3:58242->44.239.47.219:443: read: connection reset by peer
```

**Comment by jgehrcke** [comment]
Read the DD agent log carefully in both cases. Seems like in both cases there is this log pattern:

```
Successfully posted payload to "https://dd.default.bk-1795-18b-a.opstrace.io/api/v1/check_run?
...
the agent will only log transaction success every 500 transactions
```

A plausible explanation for this new problem to pop up is that the "the agent will only log transaction success every 500 transactions" message might hold true across all endpoints. That would mean that depending on the exact order of events around agent startup it's either a POST to /series or a POST to /check_run which is acked via this log message. 

That is, I assume that the needle is too specific (looking for the POST to /series confirmation. Fix upcoming.

**Comment by jgehrcke** [comment]
Another occurrence:
```
[2021-02-20T15:20:36Z] [... ]Successfully posted payload to "https://dd.default.bk-3617-6b3-g.opstrace.io/api/v1/check_run
[... ]"
the agent will only log transaction success every 500 transactions
```
https://buildkite.com/opstrace/prs/builds/3617#91290cb2-2753-48c8-bb1e-00f39d62b59d/2509-3696

**Comment by jgehrcke** [comment]
another one: https://buildkite.com/opstrace/prs/builds/3617#dfb33f0e-8f20-4b13-9d9c-20f30bf69777/798-1984
```
[2021-02-20T15:33:22Z] [...]
Successfully posted payload to "https://dd.default.bk-3617-6b3-a.opstrace.io/api/v1/check_run?api_key=***[...],
the agent will only log transaction success every 500 transactions
```

**Comment by jgehrcke** [comment]
another one: https://buildkite.com/opstrace/scheduled-main-builds/builds/1793#4b2fc348-00d3-4952-ace5-0b99ddd98a7c/265-1449
```
[2021-02-22T04:54:31Z] [...]
Successfully posted payload to "https://dd.default.bk-1793-18b-a.opstrace.io/api/v1/check_run[...]
the agent will only log transaction success every 500 transactions
```

**Comment by jgehrcke** [comment]
This has been taken care of in #406.
