### ISSUE TITLE
GKE: system log collection broken

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#407]
system logs test suite failed: 
```
[2021-02-22T14:37:02Z]   17 passing (3m)
[2021-02-22T14:37:02Z]   3 failing
[2021-02-22T14:37:02Z]
[2021-02-22T14:37:02Z]   1) system logs test suite
[2021-02-22T14:37:02Z]        check loki ingester logs:
[2021-02-22T14:37:02Z]      Error: Expectation not fulfilled within 30 s
[2021-02-22T14:37:02Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:257:9)
[2021-02-22T14:37:02Z]       at query (test_systemlogs.ts:52:20)
[2021-02-22T14:37:02Z]       at Context.<anonymous> (test_systemlogs.ts:66:5)
[2021-02-22T14:37:02Z] 
[2021-02-22T14:37:02Z]   2) system logs test suite
[2021-02-22T14:37:02Z]        check cortex distributor logs:
[2021-02-22T14:37:02Z]      Error: Expectation not fulfilled within 30 s
[2021-02-22T14:37:02Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:257:9)
[2021-02-22T14:37:02Z]       at query (test_systemlogs.ts:52:20)
[2021-02-22T14:37:02Z]       at Context.<anonymous> (test_systemlogs.ts:72:5)
[2021-02-22T14:37:02Z] 
[2021-02-22T14:37:02Z]   3) system logs test suite
[2021-02-22T14:37:02Z]        check systemlog Fluentd instance logs:
[2021-02-22T14:37:02Z]      Error: Expectation not fulfilled within 30 s
[2021-02-22T14:37:02Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:257:9)
[2021-02-22T14:37:02Z]       at query (test_systemlogs.ts:52:20)
```

https://buildkite.com/opstrace/prs/builds/3629#31ecc82a-5893-4d6f-8ce9-bde73cf57904/2250-4821

failed on gcp, not aws

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1796#a6762327-cb06-488f-903b-0434986cbc81/2434-5011

**Comment by jgehrcke** [comment]
failed on gcp here, too:
https://buildkite.com/opstrace/scheduled-main-builds/builds/1800#8be36bb1-05d9-4292-ba3a-8ac312b4bcdb/2257-4826

not on aws

**Comment by jgehrcke** [comment]
So, Initial investigation showed something real important: seems to always fail on main-test-gcp, but not main-test-aws. I didn't find a recent change w.r.t. system log collection. Initial conclusion: something in our gcp env changed underneath us and broke system log collection / information flow.

**Comment by jgehrcke** [comment]
When system log collection fails we obviously have a blind spot and can't even have a look into the logs for fluentd which collects the system logs.

Created https://github.com/opstrace/opstrace/pull/410 for debugging this -- upcoming builds will use `kubectl` to fetch fluentd logs, and upload them as BK build artifacts.

**Comment by jgehrcke** [comment]
Feb 17 changes for GKE

- Version 1.18.12-gke.1206 is now available in the Regular channel. This version is now the default.
- Version 1.19.7-gke.1302 is now available in the Rapid channel. This version is now the default.

**Comment by jgehrcke** [comment]
Still no exact explanation for what broke system log collection. But here are some more pointers. I assume that the 1.19 k8s on GKE came with the entire Docker stack removed, including the Docker JSON logging driver; instead using a CRI JSON logging driver.

Other people using the fluent ecosystem were bitten by this change in logging drivers. Found this paragraph in the fluentbit docs:

> Fluent Bit by default assumes that logs are formatted by the Docker interface standard. However, when using CRI you can run into issues with malformed JSON if you do not modify the parser used. Fluent Bit includes a CRI log parser that can be used instead.

Also found these threads/statements:
https://github.com/fluent/fluentd/issues/2407#issuecomment-747488004
https://github.com/fluent/fluentd-kubernetes-daemonset/issues/434#issuecomment-747813131

**Comment by jgehrcke** [comment]
The k8s 1.19  -> 1.18 switch fixed this in #410. For the on-disk log format change will have to do something in the future.

**Comment by jgehrcke** [comment]
We now have direct confirmation that GKE switched to using the CRI logging format underneath us. That logging format is documented here : https://github.com/kubernetes/community/blob/f0a10a6c0e00f8aa9b24dd1967ce15d6c238cba9/contributors/design-proposals/node/kubelet-cri-logging.md

Example:
```
2019-01-01T01:00:00.000000001Z stderr P some log message
```

In https://github.com/opstrace/opstrace/pull/410#issuecomment-784385831 we can see traces of that, e.g. `stdout P 2021-02-23 12:12:51`.

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1802#30140b7b-ecde-493e-98b7-8019fbc7d5d0 was affected, just for the record.
