### ISSUE TITLE
ci instability: dd_api_insert_single_ts_fragment: RequestError: Timeout awaiting 'connect' for 10000ms

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#431]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1832#d2989f3d-3735-48cf-a0cc-5dea0298a510/1302-3636
```
[2021-02-28T16:51:09Z]   19 passing (1m)
[2021-02-28T16:51:09Z]   1 failing
[2021-02-28T16:51:09Z]
[2021-02-28T16:51:09Z]   1) DD API test suite
[2021-02-28T16:51:09Z]        dd_api_insert_single_ts_fragment:
[2021-02-28T16:51:09Z]      RequestError: Timeout awaiting 'connect' for 10000ms
```

**Comment by jgehrcke** [comment]
```
[2021-03-11T20:50:41Z]
[2021-03-11T20:50:41Z]
[2021-03-11T20:50:41Z]   19 passing (1m)
[2021-03-11T20:50:41Z]   1 failing
[2021-03-11T20:50:41Z]
[2021-03-11T20:50:41Z]   1) DD API test suite
[2021-03-11T20:50:41Z]        dd_api_insert_single_ts_fragment:
[2021-03-11T20:50:41Z]      RequestError: Timeout awaiting 'connect' for 10000ms
[2021-03-11T20:50:41Z]       at ClientRequest.<anonymous> (/build/node_modules/got/dist/source/core/index.js:953:65)
[2021-03-11T20:50:41Z]       at ClientRequest.EventEmitter.emit (domain.js:467:12)
[2021-03-11T20:50:41Z]       at ClientRequest.origin.emit (/build/node_modules/@szmarczak/
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/1900#4fb4e8c6-3c62-4492-a568-43fe3791836d/948-3288
