### ISSUE TITLE
ci instability: check cortex distributor logs: query Expectation not fulfilled within 30 s

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#432]
```
[2021-02-28T00:47:00Z]   19 passing (2m)
[2021-02-28T00:47:00Z]   1 failing
[2021-02-28T00:47:00Z]
[2021-02-28T00:47:00Z]   1) system logs test suite
[2021-02-28T00:47:00Z]        check cortex distributor logs:
[2021-02-28T00:47:00Z]      Error: Expectation not fulfilled within 30 s
[2021-02-28T00:47:00Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:257:9)
[2021-02-28T00:47:00Z]       at query (test_systemlogs.ts:52:20)
[2021-02-28T00:47:00Z]       at Context.<anonymous> (test_systemlogs.ts:72:5)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/1828#945bf196-4f99-4180-9c4e-ea04531de981/609-3087

**Comment by jgehrcke** [comment]
```
[2021-02-27T04:47:04Z]   19 passing (2m)
[2021-02-27T04:47:04Z]   1 failing
[2021-02-27T04:47:04Z]
[2021-02-27T04:47:04Z]   1) system logs test suite
[2021-02-27T04:47:04Z]        check cortex distributor logs:
[2021-02-27T04:47:04Z]      Error: Expectation not fulfilled within 30 s
[2021-02-27T04:47:04Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:257:9)
[2021-02-27T04:47:04Z]       at query (test_systemlogs.ts:52:20)
[2021-02-27T04:47:04Z]       at Context.<anonymous> (test_systemlogs.t
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/1823#56eebde8-6441-48bc-8355-5811c6a13b45/2046-4526

**Comment by jgehrcke** [comment]
Another one: https://buildkite.com/opstrace/prs/builds/3685#cf3ec091-5f39-43d4-9080-58feaafad978/959-3432

So. This happend three times today so far. Always on AWS. Interesting. Should have a look at those Cortex distributor logs.

**Comment by jgehrcke** [comment]
another one on AWS: https://buildkite.com/opstrace/scheduled-main-builds/builds/1841#6dd131e9-ed6a-488e-8af2-e02cd9e6e411/714-3188

**Comment by jgehrcke** [comment]
Investigated that last case a bit.

First query: `2021-03-02T04:48:08.330Z`
Last query: `2021-03-02T04:48:38.196Z`

time window: 30 seconds.

Used this query in our CI collection cluster to get to the distributor log minus noise:
```
{opstrace_cluster_name="schedul-bk-1841-f10-a", 
  k8s_namespace_name="cortex",
  k8s_container_name="distributor"}
  !~ "POST /api/v1/push"
```

log needle (from test_systemlogs):
```
  test("check cortex distributor logs", async function () {
    await query(
      '{k8s_namespace_name="cortex", k8s_pod_name=~"distributor-.+"} |= "Starting Cortex"'
    );
  });
```

I am seeing
```
2021-03-02 05:39:26	
level=info ts=2021-03-02T04:39:26.159919533Z caller=main.go:188 msg="Starting Cortex" version="(version=1.7.0, branch=master, revision=35fbe42)"
2021-03-02 05:39:26	
level=info ts=2021-03-02T04:39:26.16041004Z caller=server.go:229 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
2021-03-02 05:39:26	
level=info ts=2021-03-02T04:39:26.16269385Z caller=module_service.go:59 msg=initialising module=server
2021-03-02 05:39:26	
level=info ts=2021-03-02T04:39:26.162886974Z caller=memberlist_client.go:380 msg="Using memberlist cluster node name" name=distributor-7655bf9ddc-lkr6x-2e67ef46
2021-03-02 05:39:26	
level=info ts=2021-03-02T04:39:26.167296996Z caller=module_service.go:59 msg=initialising module=memberlist-kv
2021-03-02 05:39:26	
level=info ts=2021-03-02T04:39:26.168764385Z caller=module_service.go:59 msg=initialising module=ring
2021-03-02 05:39:26	
level=info ts=2021-03-02T04:39:26.169053895Z caller=module_service.go:59 msg=initialising module=distributor-service
2021-03-02 05:39:26	
level=info ts=2021-03-02T04:39:26.177710507Z caller=cortex.go:407 msg="Cortex started"
2021-03-02 05:39:26	
ts=2021-03-02T04:39:26.234882349Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve loki-gossip-ring.cortex.svc.cluster.local:7946: lookup loki-gossip-ring.cortex.svc.cluster.local on 10.100.0.10:53: no such host"
```

That is, the distributor emitted the first "Starting Cortex" log line at `2021-03-02T04:39:26`, i.e. about 10 minutes before the test in question ran. Why would the Loki query not return that?

The systemlog test "check loki ingester logs" passed right before the failing test. The systemlog test "check systemlog Fluentd instance logs" passed right after the failing test.

Let's look at the details of the log line in question, all labels:

![Screenshot from 2021-03-02 10-36-43](https://user-images.githubusercontent.com/265630/109628655-48d6e400-7b43-11eb-8b27-3ce5901afef3.png)

When was the file `/var/log/pods/cortex_distributor-7655bf9ddc-lkr6x_9cab9671-517c-4159-975c-431d432bd7c5/distributor/0.log` picked up by our systemlog fluentd?

New query:
```
{opstrace_cluster_name="schedul-bk-1841-f10-a",
  k8s_namespace_name="system-tenant",
  k8s_pod_name=~"systemlog.*"} 
```

Adding the filter `|= "7655bf9ddc-lkr6x"` to the query.

Going through that I find:

```

2021-03-02 04:39:49 +0000 [info]: #0 following tail of /var/log/containers/distributor-7655bf9ddc-lkr6x_cortex_distributor-1a942e23788e593317444e64acc4c7aad688569266618968e182a8231f2bc8a6.log

2021-03-02 04:39:57 +0000 [info]: #0 following tail of /var/log/containers/distributor-7655bf9ddc-lkr6x_cortex_distributor-1a942e23788e593317444e64acc4c7aad688569266618968e182a8231f2bc8a6.log
```

This is where we see that while our fluentd config matches `path "/var/log/containers/*.log"`, the promtail config seems to match
```
/var/log/pods/*/*/0.log
```
which one is better?

Fluentd discovered three log files in total, and logged a 'following tail of ...' entry twice for each:

![Screenshot from 2021-03-02 10-53-19](https://user-images.githubusercontent.com/265630/109630757-93f1f680-7b45-11eb-9bbb-fd9bdc2ca3ae.png)

What happened between the first
```

2021-03-02 04:39:45 +0000 [info]: #0 following tail of /var/log/containers/distributor-7655bf9ddc-clssm_cortex_distributor-24291894c1b75828b20169d014be59dcde05a22631c6cd87478f7507d3d3fe78.log
```
and the second
```
2021-03-02 04:39:51 +0000 [info]: #0 following tail of /var/log/containers/distributor-7655bf9ddc-clssm_cortex_distributor-24291894c1b75828b20169d014be59dcde05a22631c6cd87478f7507d3d3fe78.log
```
?

Six seconds inbetween. Did something crash? Yes. The fluentd worker crashed and restarted:
```
2021-03-02 05:39:45	
2021-03-02 04:39:45 +0000 [error]: #0 unexpected error error_class=Errno::ENOENT error="No such file or directory @ rb_file_s_stat - /var/log/containers/ruler-7654f659c6-k6p9k_cortex_ruler-4fd5dad3936fcfcfd06754e655aa8c985c248b8141265849ad086fb8c8b60759.log"
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/in_tail.rb:409:in `stat'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/in_tail.rb:409:in `block in start_watchers'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/in_tail.rb:390:in `each_value'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/in_tail.rb:390:in `start_watchers'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/in_tail.rb:353:in `refresh_watchers'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/in_tail.rb:234:in `start'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:200:in `block in start'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:189:in `block (2 levels) in lifecycle'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:188:in `each'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:188:in `block in lifecycle'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:175:in `each'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:175:in `lifecycle'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:199:in `start'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/engine.rb:248:in `start'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/engine.rb:147:in `run'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:693:in `block in run_worker'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:943:in `main_process'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:684:in `run_worker'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/bin/fluentd:8:in `<top (required)>'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/bin/fluentd:23:in `load'
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 /usr/local/bundle/bin/fluentd:23:in `<main>'
2021-03-02 05:39:45	
2021-03-02 04:39:45 +0000 [error]: #0 unexpected error error_class=Errno::ENOENT error="No such file or directory @ rb_file_s_stat - /var/log/containers/ruler-7654f659c6-k6p9k_cortex_ruler-4fd5dad3936fcfcfd06754e655aa8c985c248b8141265849ad086fb8c8b60759.log"
2021-03-02 05:39:45	
  2021-03-02 04:39:45 +0000 [error]: #0 suppressed same stacktrace
2021-03-02 05:39:45	
2021-03-02 04:39:45 +0000 [info]: Worker 0 finished unexpectedly with status 1
2021-03-02 05:39:45	
2021-03-02 04:39:45 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2021-03-02 05:39:47	
2021-03-02 04:39:47 +0000 [info]: adding filter pattern="kubernetes.**" type="record_transformer"
2021-03-02 05:39:47	
2021-03-02 04:39:47 +0000 [info]: adding match pattern="kubernetes.**" type="loki"
2021-03-02 05:39:47	
2021-03-02 04:39:47 +0000 [info]: #0 will use Bearer token from bearer_token_file /var/run/opstrace/system_tenant_api_auth_token in Authorization header
2021-03-02 05:39:47	
2021-03-02 04:39:47 +0000 [info]: adding source type="tail"
2021-03-02 05:39:47	
2021-03-02 04:39:47 +0000 [info]: adding filter pattern="kubernetes.**" type="record_transformer"
2021-03-02 05:39:47	
2021-03-02 04:39:47 +0000 [info]: #0 starting fluentd worker pid=19 ppid=7 worker=0
```

Interesting:
```
ENOENT error="No such file or directory @ rb_file_s_stat - \

/var/log/containers/ruler-7654f659c6-k6p9k_cortex_ruler-4fd5dad3936fcfcfd06754e655aa8c985c248b8141265849ad086fb8c8b60759.log"
```

This might be a regression in Fluentd 1.12.0 -- the worker process restarts thereafter, and that crash loop persists for like 5 iterations. Does it result in data loss? I have submitted https://github.com/fluent/fluentd/issues/3274 and https://github.com/fluent/fluentd/issues/3224 is interesting.

**Comment by jgehrcke** [comment]
could revert https://github.com/opstrace/opstrace/pull/411 to get rid of it.

**Comment by jgehrcke** [comment]
should be fixed for now via https://github.com/opstrace/opstrace/pull/438
