### ISSUE TITLE
ci instability: during preramble / cli build: ENOENT: no such file or directory, open '/tmp/v2.6/fetched-v14.4.0-macos-x64'

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#439]
```
[2021-03-02T12:15:52Z] > pkg@4.4.9
[2021-03-02T12:15:52Z] > Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.4.0-macos-x64    [] 100%
[2021-03-02T12:15:54Z] > Warning Cannot find module '@types/jsonwebtoken' from '/build/packages/cli/build'
[2021-03-02T12:15:54Z]   %1: /build/packages/cli/build/index.js
[2021-03-02T12:15:56Z] > Warning Cannot include file %1 into executable.
[2021-03-02T12:15:56Z]   The file must be distributed with executable as %2.
[2021-03-02T12:15:56Z]   %1: node_modules/open/xdg-open
[2021-03-02T12:15:56Z]   %2: path-to-executable/xdg-open
[2021-03-02T12:15:56Z] > Warning Cannot include file %1 into executable.
[2021-03-02T12:15:56Z]   The file must be distributed with executable as %2.
[2021-03-02T12:15:56Z]   %1: node_modules/open/xdg-open
[2021-03-02T12:15:56Z]   %2: path-to-executable/xdg-open
[2021-03-02T12:16:15Z] > Error! Error: ENOENT: no such file or directory, open '/tmp/v2.6/fetched-v14.4.0-macos-x64'
[2021-03-02T12:16:15Z]     at Object.openSync (fs.js:476:3)
[2021-03-02T12:16:15Z]     at Object.readFileSync (fs.js:377:35)
[2021-03-02T12:16:15Z]     at /build/node_modules/pkg/lib-es5/producer.js:146:38
[2021-03-02T12:16:15Z]     at new Promise (<anonymous>)
[2021-03-02T12:16:15Z]     at _default (/build/node_modules/pkg/lib-es5/producer.js:111:10)
[2021-03-02T12:16:15Z]     at /build/node_modules/pkg/lib-es5/index.js:518:35
[2021-03-02T12:16:15Z]     at Generator.next (<anonymous>)
[2021-03-02T12:16:15Z]     at asyncGeneratorStep (/build/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[2021-03-02T12:16:15Z]     at _next (/build/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
error Command failed with exit code 2.
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/1843#59ab876a-4208-4d54-a624-0eb31465f8d0/2379-2402

**Comment by jgehrcke** [comment]
```
[2021-03-02T12:15:53Z] + yarn run pkg packages/cli/package.json --public --targets node14-macos-x64 --output build/bin/macos/opstrace --options stack-trace-limit=100
yarn run v1.22.10
$ /build/node_modules/.bin/pkg packages/cli/package.json --public --targets node14-macos-x64 --output build/bin/macos/opstrace --options stack-trace-limit=100
[2021-03-02T12:15:53Z] > pkg@4.4.9
[2021-03-02T12:15:53Z] > Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.4.0-macos-x64    [] 100%
[2021-03-02T12:15:55Z] > Error! Error: ENOENT: no such file or directory, stat '/tmp/v2.6/fetched-v14.4.0-macos-x64.downloading'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
https://buildkite.com/opstrace/prs/builds/3695#0e3bebca-dff0-478c-a331-e7a541770702/1502-1528

**Comment by jgehrcke** [comment]
```
error An unexpected error occurred: "ENOENT: no such file or directory, copyfile '/build/.cache/yarn/v6/npm-@emotion-weak-memoize-0.2.5-8eed982e2ee6f7f4e44c253e12962980791efd46-integrity/node_modules/@emotion/weak-memoize/README.md' -> '/build/node_modules/@emotion/weak-memoize/README.md'".
```
https://buildkite.com/opstrace/prs/builds/3750#9168d666-33d3-4b0f-a16a-ede6f66c15bc/80-233

**Comment by jgehrcke** [comment]
Carrying over

```
error An unexpected error occurred: "ENOENT: no such file or directory, copyfile '/build/.cache/yarn/v6/npm-@auth0-auth0-react-1.3.0-f449c0abca2cb8f0fba0d1919a25685bcc90b925-integrity/node_modules/@auth0/auth0-react/CHANGELOG.md' -> '/build/node_modules/@auth0/auth0-react/CHANGELOG.md'".
```

from https://github.com/opstrace/opstrace/issues/440.

**Comment by jgehrcke** [comment]
What changed in our CI setup around March 01 / 02 so that we get these yarn concurrency issues again?

**Comment by jgehrcke** [comment]
Interesting:
```
[2021-03-09T10:53:27Z] ++ rm -rf /tmp/opstrace-bk-3750-a5bba5b-prebuild/node_modules
[2021-03-09T10:53:27Z] rm: cannot remove ‘/tmp/opstrace-bk-3750-a5bba5b-prebuild/node_modules/@graphql-tools/delegate’: Directory not empty
```

Must be a concurrency problem. Something wrote to the directory while `rm -rf` was doing its thing.

**Comment by jgehrcke** [comment]
```
[2021-06-03T12:22:59Z] > pkg@4.4.9
[2021-06-03T12:22:59Z] > Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.4.0-macos-x64    [] 100%
[2021-06-03T12:23:03Z] > Warning Cannot include file %1 into executable.
[2021-06-03T12:23:03Z]   The file must be distributed with executable as %2.
[2021-06-03T12:23:03Z]   %1: node_modules/open/xdg-open
[2021-06-03T12:23:03Z]   %2: path-to-executable/xdg-open
[2021-06-03T12:23:03Z] > Warning Cannot include file %1 into executable.
[2021-06-03T12:23:03Z]   The file must be distributed with executable as %2.
[2021-06-03T12:23:03Z]   %1: node_modules/open/xdg-open
[2021-06-03T12:23:03Z]   %2: path-to-executable/xdg-open
[2021-06-03T12:23:28Z] > Error! Error: ENOENT: no such file or directory, open '/tmp/v2.6/fetched-v14.4.0-macos-x64'
[2021-06-03T12:23:28Z]     at Object.openSync (fs.js:476:3)
[2021-06-03T12:23:28Z]     at Object.readFileSync (fs.js:377:35)
```
https://buildkite.com/opstrace/prs/builds/4506#b9b15bd0-61f2-4dab-add8-2c15c86e1b41/2770-2793

**Comment by jgehrcke** [comment]
```
[2021-06-03T12:23:00Z] > Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.4.0-macos-x64    [] 100%
[2021-06-03T12:23:01Z] > Error! Error: ENOENT: no such file or directory, stat '/tmp/v2.6/fetched-v14.4.0-macos-x64.downloading'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2412#595f3d97-6958-4fd0-90e9-048db95ef014/2782-2806

**Comment by nickbp** [comment]
No new cases since early June
