### ISSUE TITLE
uninstaller: gcp: does not recover from network resource 'projects/vast-pad-snip/global/networks/snip is already being used by 'projects/vast-pad-snip/global/firewalls/k8s-snip-node-hc'

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#47]
Consumed all high-level retries, didn't break the dependency cycle:
```
...
2020-12-01T11:07:08.623Z info: Destroying VPC
2020-12-01T11:07:30.531Z info: VPC deletion has started with status: RUNNING
2020-12-01T11:07:37.189Z error: error during cluster teardown (attempt 5):
ApiError: The network resource 'projects/vast-pad-240918/global/networks/jpdev' is already being used by 'projects/vast-pad-<snip>/global/firewalls/k8s-3cc02042af359f14-node-hc'
    at new ApiError (/home/jp/dev/opstrace/node_modules/@google-cloud/common/build/src/util.js:59:15)
    at Util.parseHttpRespBody (/home/jp/dev/opstrace/node_modules/@google-cloud/common/build/src/util.js:194:38)
    at /home/jp/dev/opstrace/node_modules/@google-cloud/compute/src/operation.js:251:46
    at /home/jp/dev/opstrace/node_modules/@google-cloud/compute/src/operation.js:234:7
    at /home/jp/dev/opstrace/node_modules/@google-cloud/common/build/src/service-object.js:193:13
    at /home/jp/dev/opstrace/node_modules/@google-cloud/common/build/src/util.js:369:25
    at Util.handleResp (/home/jp/dev/opstrace/node_modules/@google-cloud/common/build/src/util.js:145:9)
    at /home/jp/dev/opstrace/node_modules/@google-cloud/common/build/src/util.js:434:22
    at onResponse (/home/jp/dev/opstrace/node_modules/retry-request/index.js:214:7)
    at /home/jp/dev/opstrace/node_modules/teeny-request/src/index.ts:325:11 {
  code: undefined,
  errors: [Array],
  response: undefined
}
2020-12-01T11:07:37.190Z error: JSON representation of err: {
  "errors": [
    {
      "code": "RESOURCE_IN_USE_BY_ANOTHER_RESOURCE",
      "message": "The network resource 'projects/vast-pad-240918/global/networks/jpdev' is already being used by 'projects/vast-pad-<snip>/global/firewalls/k8s-3cc02042af359f14-node-hc'"
    }
  ],
  "message": "The network resource 'projects/vast-pad-240918/global/networks/jpdev' is already being used by 'projects/vast-pad-240918/global/firewalls/k8s-3cc02042af359f14-node-hc'"
}
2020-12-01T11:07:37.191Z error: 5 attempt(s) failed. Stop retrying. Exit.
2020-12-01T11:07:37.192Z debug: shut down logger, then exit with code 1
```
(Seen locally, was trying to tear down an oldish GCP dev cluster of mine).

**Comment by jgehrcke** [comment]
seen locally just now again:
```
$ ./opstrace destroy gcp bk-3314-58c-g
2020-12-20T17:07:40.555Z info: logging to file: opstrace_cli_destroy_20201220-170740Z.log
2020-12-20T17:07:40.562Z info: About to destroy cluster bk-3314-58c-g (gcp).
...
2020-12-20T17:21:34.098Z info: Ensure SQLInstance deletion
2020-12-20T17:21:34.098Z info: SQLInstance teardown: start
2020-12-20T17:21:34.689Z info: SQLInstance is RUNNABLE
2020-12-20T17:21:36.092Z info: SQLInstance teardown: desired state reached
2020-12-20T17:21:36.092Z info: Ensure Address deletion
2020-12-20T17:21:36.644Z info: Global Address is RESERVED
2020-12-20T17:21:40.067Z info: Global Address teardown: desired state reached
2020-12-20T17:21:40.068Z info: Destroying CloudNat and Router
2020-12-20T17:22:11.715Z info: Destroying Subnet
2020-12-20T17:22:13.331Z info: Subnet deletion has started with status: RUNNING
2020-12-20T17:22:31.935Z info: Subnet deletion is: DONE with 100 progress
2020-12-20T17:22:32.785Z info: Destroying VPC
2020-12-20T17:22:53.722Z info: Destroying route: default-route-cecfb83b6c6cedfe
2020-12-20T17:23:20.756Z info: VPC deletion has started with status: RUNNING
2020-12-20T17:23:27.331Z error: error during cluster teardown (attempt 1):
ApiError: The network resource 'projects/ci-shard-aaa/global/networks/bk-3314-58c-g' is already being used by 'projects/ci-shard-aaa/global/firewalls/k8s-fw-a1c50e91a10b640eea79e01b747a2288'
    at new ApiError (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:59:15)
    at Util.parseHttpRespBody (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:194:38)
    at /snapshot/build/node_modules/@google-cloud/compute/src/operation.js:251:46
    at /snapshot/build/node_modules/@google-cloud/compute/src/operation.js:234:7
    at /snapshot/build/node_modules/@google-cloud/common/build/src/service-object.js:193:13
    at /snapshot/build/node_modules/@google-cloud/common/build/src/util.js:369:25
    at Util.handleResp (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:145:9)
    at /snapshot/build/node_modules/@google-cloud/common/build/src/util.js:434:22
    at onResponse (/snapshot/build/node_modules/retry-request/index.js:214:7)
    at /snapshot/build/node_modules/teeny-request/src/index.ts:325:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  errors: [Array],
  response: undefined
}
2020-12-20T17:23:27.332Z error: JSON representation of err: {
  "errors": [
    {
      "code": "RESOURCE_IN_USE_BY_ANOTHER_RESOURCE",
      "message": "The network resource 'projects/ci-shard-aaa/global/networks/bk-3314-58c-g' is already being used by 'projects/ci-shard-aaa/global/firewalls/k8s-fw-a1c50e91a10b640eea79e01b747a2288'"
    }
  ],
  "message": "The network resource 'projects/ci-shard-aaa/global/networks/bk-3314-58c-g' is already being used by 'projects/ci-shard-aaa/global/firewalls/k8s-fw-a1c50e91a10b640eea79e01b747a2288'"
}
2020-12-20T17:23:27.332Z info: start attempt 2 in 30 s
2020-12-20T17:23:58.396Z info: GKE cluster corresponding to Opstrace cluster 'bk-3314-58c-g' does not seem to exist.
2020-12-20T17:23:58.397Z info: Ensure cert-manager service account deletion
2020-12-20T17:23:59.438Z info: Ensure external-dns service account deletion
2020-12-20T17:24:00.313Z info: Ensure cortex service account deletion
2020-12-20T17:24:01.295Z info: Ensure loki service account deletion
2020-12-20T17:24:02.253Z info: Ensure GKE deletion
2020-12-20T17:24:02.254Z info: GKE teardown: start
2020-12-20T17:24:03.090Z info: GKE teardown: desired state reached
2020-12-20T17:24:03.091Z info: Ensure CloudSQL deletion
2020-12-20T17:24:03.091Z info: Ensure SQLDatabase deletion
2020-12-20T17:24:03.092Z info: SQLDatabase teardown: start
2020-12-20T17:24:03.956Z info: SQLDatabase teardown: desired state reached
2020-12-20T17:24:03.957Z info: Ensure SQLInstance deletion
2020-12-20T17:24:03.957Z info: SQLInstance teardown: start
2020-12-20T17:24:05.574Z info: SQLInstance teardown: desired state reached
2020-12-20T17:24:05.574Z info: Ensure Address deletion
2020-12-20T17:24:06.008Z info: Global Address teardown: desired state reached
2020-12-20T17:24:06.009Z info: Destroying CloudNat and Router
2020-12-20T17:24:06.490Z info: Destroying Subnet
2020-12-20T17:24:07.029Z info: Destroying VPC
2020-12-20T17:24:28.899Z info: VPC deletion has started with status: RUNNING
2020-12-20T17:24:38.055Z error: error during cluster teardown (attempt 2):
...
```

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2741#6d1c0c43-da3b-4768-ac4f-bccb7e87061e/7111-7621

```
[2021-07-27T09:10:08Z] 2021-07-27T09:10:08.947Z info: Subnet deletion is: DONE with 100 progress
[2021-07-27T09:10:09Z] 2021-07-27T09:10:09.078Z info: Destroying VPC
[2021-07-27T09:10:29Z] 2021-07-27T09:10:29.763Z info: Destroying route: default-route-d85e800e46a43438
[2021-07-27T09:10:56Z] 2021-07-27T09:10:56.490Z info: VPC deletion has started with status: RUNNING
[2021-07-27T09:11:00Z] 2021-07-27T09:11:00.174Z error: error during cluster teardown (attempt 1):
[2021-07-27T09:11:00Z] ApiError: The network resource 'projects/ci-shard-fff/global/networks/pr-upgr-bk-2741-f01-g' is already being used by 'projects/ci-shard-fff/global/firewalls/k8s-fw-ab49441d3215a42ccbe2d5b2037b3f18'
[2021-07-27T09:11:00Z]     at new ApiError (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:59:15)
[2021-07-27T09:11:00Z]     at Util.parseHttpRespBody (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:194:38)
[2021-07-27T09:11:00Z]     at /snapshot/build/node_modules/@google-cloud/compute/src/operation.js:251:46
[2021-07-27T09:11:00Z]     at /snapshot/build/node_modules/@google-cloud/compute/src/operation.js:234:7
[2021-07-27T09:11:00Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/service-object.js:202:13
[2021-07-27T09:11:00Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/util.js:369:25
[2021-07-27T09:11:00Z]     at Util.handleResp (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:145:9)
[2021-07-27T09:11:00Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/util.js:434:22
[2021-07-27T09:11:00Z]     at onResponse (/snapshot/build/node_modules/retry-request/index.js:214:7)
[2021-07-27T09:11:00Z]     at /snapshot/build/node_modules/teeny-request/src/index.ts:325:11
[2021-07-27T09:11:00Z]     at runMicrotasks (<anonymous>)
[2021-07-27T09:11:00Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2021-07-27T09:11:00Z]   code: undefined,
[2021-07-27T09:11:00Z]   errors: [Array],
[2021-07-27T09:11:00Z]   response: undefined
[2021-07-27T09:11:00Z] }
```

**Comment by jgehrcke** [comment]
Huh. Some things are just rare. Glad you found the ticket.

**Comment by sreis** [comment]
```
[2021-07-30T15:08:38Z] 2021-07-30T15:08:38.929Z error: error during cluster teardown (attempt 3):
[2021-07-30T15:08:38Z] ApiError: The network resource 'projects/ci-shard-fff/global/networks/pr-upgr-bk-5253-b03-g' is already being used by 'projects/ci-shard-fff/global/firewalls/k8s-fw-a8de1f6133fc7497784a50c307d28ba9'
[2021-07-30T15:08:38Z]     at new ApiError (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:59:15)
[2021-07-30T15:08:38Z]     at Util.parseHttpRespBody (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:194:38)
[2021-07-30T15:08:38Z]     at /snapshot/build/node_modules/@google-cloud/compute/src/operation.js:251:46
[2021-07-30T15:08:38Z]     at /snapshot/build/node_modules/@google-cloud/compute/src/operation.js:234:7
[2021-07-30T15:08:38Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/service-object.js:202:13
[2021-07-30T15:08:38Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/util.js:369:25
[2021-07-30T15:08:38Z]     at Util.handleResp (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:145:9)
[2021-07-30T15:08:38Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/util.js:434:22
[2021-07-30T15:08:38Z]     at onResponse (/snapshot/build/node_modules/retry-request/index.js:214:7)
[2021-07-30T15:08:38Z]     at /snapshot/build/node_modules/teeny-request/src/index.ts:325:11
[2021-07-30T15:08:38Z]     at runMicrotasks (<anonymous>)
[2021-07-30T15:08:38Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2021-07-30T15:08:38Z]   code: undefined,
[2021-07-30T15:08:38Z]   errors: [Array],
[2021-07-30T15:08:38Z]   response: undefined
[2021-07-30T15:08:38Z] }
```

https://buildkite.com/opstrace/prs/builds/5253#c4e8a529-a58c-4406-9f2d-3f3497593c5f/7505-8195

**Comment by jgehrcke** [comment]
```
[2021-08-10T02:17:26Z] 2021-08-10T02:17:26.303Z info: VPC deletion has started with status: RUNNING
[2021-08-10T02:17:28Z] 2021-08-10T02:17:28.700Z error: error during cluster teardown (attempt 5):
[2021-08-10T02:17:28Z] ApiError: The network resource 'projects/ci-shard-ccc/global/networks/pr-upgr-bk-5446-041-g' is already being used by 'projects/ci-shard-ccc/global/firewalls/k8s-6b30d87a27edee2a-node-http-hc'
[2021-08-10T02:17:28Z]     at new ApiError (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:59:15)
[2021-08-10T02:17:28Z]     at Util.parseHttpRespBody (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:194:38)
[2021-08-10T02:17:28Z]     at /snapshot/build/node_modules/@google-cloud/compute/src/operation.js:251:46
[2021-08-10T02:17:28Z]     at /snapshot/build/node_modules/@google-cloud/compute/src/operation.js:234:7
[2021-08-10T02:17:28Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/service-object.js:202:13
[2021-08-10T02:17:28Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/util.js:369:25
[2021-08-10T02:17:28Z]     at Util.handleResp (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:145:9)
[2021-08-10T02:17:28Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/util.js:434:22
[2021-08-10T02:17:28Z]     at onResponse (/snapshot/build/node_modules/retry-request/index.js:214:7)
[2021-08-10T02:17:28Z]     at /snapshot/build/node_modules/teeny-request/src/index.ts:325:11
[2021-08-10T02:17:28Z]     at runMicrotasks (<anonymous>)
[2021-08-10T02:17:28Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2021-08-10T02:17:28Z]   code: undefined,
[2021-08-10T02:17:28Z]   errors: [Array],
[2021-08-10T02:17:28Z]   response: undefined
[2021-08-10T02:17:28Z] }
[2021-08-10T02:17:28Z] 2021-08-10T02:17:28.701Z debug: `err?.stack`: Error: The network resource 'projects/ci-shard-ccc/global/networks/pr-upgr-bk-5446-041-g' is already being used by 'projects/ci-shard-ccc/global/firewalls/k8s-6b30d87a27edee2a-node-http-hc'
[2021-08-10T02:17:28Z]     at new ApiError (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:59:15)
[2021-08-10T02:17:28Z]     at Util.parseHttpRespBody (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:194:38)
[2021-08-10T02:17:28Z]     at /snapshot/build/node_modules/@google-cloud/compute/src/operation.js:251:46
[2021-08-10T02:17:28Z]     at /snapshot/build/node_modules/@google-cloud/compute/src/operation.js:234:7
[2021-08-10T02:17:28Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/service-object.js:202:13
[2021-08-10T02:17:28Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/util.js:369:25
[2021-08-10T02:17:28Z]     at Util.handleResp (/snapshot/build/node_modules/@google-cloud/common/build/src/util.js:145:9)
[2021-08-10T02:17:28Z]     at /snapshot/build/node_modules/@google-cloud/common/build/src/util.js:434:22
[2021-08-10T02:17:28Z]     at onResponse (/snapshot/build/node_modules/retry-request/index.js:214:7)
[2021-08-10T02:17:28Z]     at /snapshot/build/node_modules/teeny-request/src/index.ts:325:11
[2021-08-10T02:17:28Z]     at runMicrotasks (<anonymous>)
[2021-08-10T02:17:28Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-08-10T02:17:28Z] 2021-08-10T02:17:28.701Z error: JSON representation of err: {
[2021-08-10T02:17:28Z]   "errors": [
[2021-08-10T02:17:28Z]     {
[2021-08-10T02:17:28Z]       "code": "RESOURCE_IN_USE_BY_ANOTHER_RESOURCE",
[2021-08-10T02:17:28Z]       "message": "The network resource 'projects/ci-shard-ccc/global/networks/pr-upgr-bk-5446-041-g' is already being used by 'projects/ci-shard-ccc/global/firewalls/k8s-6b30d87a27edee2a-node-http-hc'"
[2021-08-10T02:17:28Z]     }
[2021-08-10T02:17:28Z]   ],
[2021-08-10T02:17:28Z]   "message": "The network resource 'projects/ci-shard-ccc/global/networks/pr-upgr-bk-5446-041-g' is already being used by 'projects/ci-shard-ccc/global/firewalls/k8s-6b30d87a27edee2a-node-http-hc'"
[2021-08-10T02:17:28Z] }
[2021-08-10T02:17:28Z] 2021-08-10T02:17:28.702Z error: 5 attempt(s) failed. Stop retrying. Exit.
```
https://buildkite.com/opstrace/prs/builds/5446#de3588c1-ef9d-4869-afc7-0b8b19f27dc1/7328-8213

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/3021#4c2bf560-6bf3-4ad7-a661-a51ac4a414a3/8382-8953

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/3061#31a78bae-0561-4ca0-9cd7-1cbf0b617aca/7675-8229

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/3193#55968216-e47b-48ed-8a63-9e4895775358/7693-8284

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/3212#59bd3ebd-575c-44d1-bf10-e49f8ef9c346/7020-7597

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/3271#449a9ceb-20a2-4ca9-b924-74835e62fd7f/7284-8253
