### ISSUE TITLE
cli: destroy: region detection: error not handled when retries exceeded

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#581]
```
[2021-03-26T13:08:29Z] 2021-03-26T13:08:29.308Z info: AWS API request failed (attempt 14): Socket timed out without establishing a connection (retry in 30.00 seconds)
[2021-03-26T13:08:34Z] 2021-03-26T13:08:34.240Z info: AWS API request failed (attempt 14): Socket timed out without establishing a connection (retry in 30.00 seconds)
[2021-03-26T13:09:05Z] 2021-03-26T13:09:05.334Z debug: aws sdk: [AWS eks undefined 400.837s 15 retries] listClusters({})
[2021-03-26T13:09:05Z] 2021-03-26T13:09:05.334Z debug: this does not appear to be an AWS API error
[2021-03-26T13:09:05Z]
[2021-03-26T13:09:05Z] /snapshot/build/node_modules/aws-sdk/lib/http/node.js:69
[2021-03-26T13:09:05Z]               new Error('Socket timed out without establishing a connection'),
[2021-03-26T13:09:05Z]               ^
[2021-03-26T13:09:05Z] TimeoutError: Socket timed out without establishing a connection
[2021-03-26T13:09:05Z]     at Timeout.connectTimeout [as _onTimeout] (/snapshot/build/node_modules/aws-sdk/lib/http/node.js:69:15)
[2021-03-26T13:09:05Z]     at listOnTimeout (internal/timers.js:549:17)
[2021-03-26T13:09:05Z]     at processTimers (internal/timers.js:492:7)
[2021-03-26T13:09:05Z] + EXITCODE_DESTROY=1
[2021-03-26T13:09:05Z] + echo '+++ Exit status of destroy: 1'
```

https://github.com/opstrace/opstrace/issues/511#issuecomment-808205316
https://buildkite.com/opstrace/scheduled-main-builds/builds/1988#ed0f8fd0-2025-46f3-bd9a-9c2786f0c104/7861-7988

Handle that error and generate an error message that shows the affected aws region.

**Comment by jgehrcke** [comment]
```
[2021-04-16T21:17:28Z] 2021-04-16T21:17:28.265Z info: AWS API request failed (attempt 14): Socket timed out without establishing a connection (retry in 30.00 seconds)
[2021-04-16T21:17:38Z] 2021-04-16T21:17:38.447Z info: AWS API request failed (attempt 14): Socket timed out without establishing a connection (retry in 30.00 seconds)
[2021-04-16T21:18:04Z] 2021-04-16T21:18:04.281Z debug: aws sdk: [AWS eks undefined 393.85s 15 retries] listClusters({})
[2021-04-16T21:18:04Z] 2021-04-16T21:18:04.282Z debug: this does not appear to be an AWS API error
[2021-04-16T21:18:04Z]
[2021-04-16T21:18:04Z] /snapshot/build/node_modules/aws-sdk/lib/http/node.js:69
[2021-04-16T21:18:04Z]               new Error('Socket timed out without establishing a connection'),
[2021-04-16T21:18:04Z]               ^
[2021-04-16T21:18:04Z] TimeoutError: Socket timed out without establishing a connection
[2021-04-16T21:18:04Z]     at Timeout.connectTimeout [as _onTimeout] (/snapshot/build/node_modules/aws-sdk/lib/http/node.js:69:15)
[2021-04-16T21:18:04Z]     at listOnTimeout (internal/timers.js:549:17)
[2021-04-16T21:18:04Z]     at processTimers (internal/timers.js:492:7)
[2021-04-16T21:18:04Z] + EXITCODE_DESTROY=1
```

**Comment by jgehrcke** [comment]
Addressing that via https://github.com/opstrace/opstrace/pull/607

**Comment by sreis** [comment]
https://buildkite.com/opstrace/upgrade-tests/builds/608#582320ac-07c4-4bfa-91a0-f32c4a9d12e8/5489-5620
