### ISSUE TITLE
Metric exporter tests: Azure exporter: RequestError: Timeout awaiting 'request' for 60000ms

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#611]
**Describe the bug**

```
2021-04-28T04:54:44Z] 2021-04-28T04:54:44.710Z info: Got exporter log for query={k8s_namespace_name="default-tenant",k8s_container_name="exporter",k8s_pod_name=~"exporter-testexporters-zcqxb-azure-.+"} |= "Tenant 'testtenantshouldfail' not found": 1619585681289224468,log="2021/04/28 04:54:41 Failed to get token: Did not get status code 200, got: 400 with body: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'testtenantshouldfail' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: 87c301b3-f3f9-4d64-93ec-7e91125a1101\r\nCorrelation ID: e22c0ab9-6cf6-4bd9-8534-8ffd0e61bedd\r\nTimestamp: 2021-04-28 04:54:41Z","error_codes":[90002],"timestamp":"2021-04-28 04:54:41Z","trace_id":"87c301b3-f3f9-4d64-93ec-7e91125a1101","correlation_id":"e22c0ab9-6cf6-4bd9-8534-8ffd0e61bedd","error_uri":"https://login.microsoftonline.com/error?code=90002"}
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2186#b5d02062-85da-4276-84e1-815f2da4e050/2796-6613

**Comment by nickbp** [comment]
This Azure exporter test had just recently been merged, so it looks like there's still a flake or two in there.

**Comment by nickbp** [comment]
Looks like the `default-tenant` check had succeeded while the `system-tenant` check failed a few lines down: https://buildkite.com/opstrace/scheduled-main-builds/builds/2186#b5d02062-85da-4276-84e1-815f2da4e050/2796-6699
```
[2021-04-28T04:54:45Z] 2021-04-28T04:54:45.366Z [32minfo[39m: Waiting for exporter log: {k8s_namespace_name="system-tenant",k8s_container_name="exporter",k8s_pod_name=~"exporter-testexporters-zcqxb-azure-.+"} |= "Tenant 'testtenantshouldfail' not found"
[2021-04-28T04:54:45Z] 2021-04-28T04:54:45.367Z [32minfo[39m: read token from /tmp/opstrace-bk-2186-56e85d0-1-gcp/tenant-api-token-system
[2021-04-28T04:54:45Z] 2021-04-28T04:54:45.972Z [32minfo[39m: read token from /tmp/opstrace-bk-2186-56e85d0-1-gcp/tenant-api-token-system
[2021-04-28T04:54:46Z] 2021-04-28T04:54:46.586Z [32minfo[39m: read token from /tmp/opstrace-bk-2186-56e85d0-1-gcp/tenant-api-token-system
[2021-04-28T04:54:47Z] 2021-04-28T04:54:47.192Z [32minfo[39m: read token from /tmp/opstrace-bk-2186-56e85d0-1-gcp/tenant-api-token-system
[2021-04-28T04:55:47Z]   [31m  1) Azure exporter[0m
[2021-04-28T04:55:47Z] 2021-04-28T04:55:47.201Z [32minfo[39m: suite teardown
```
Something strange above is how it froze from 04:54:47 until giving up at 04:55:47. Would've expected additional "read token" lines in that gap.

Meanwhile the failure stacktrace shows a 60s timeout:
```
[2021-04-28T04:56:39Z] [0m  1) Metric exporter tests
[2021-04-28T04:56:39Z]        Azure exporter:
[2021-04-28T04:56:39Z] [0m[31m     RequestError: Timeout awaiting 'request' for 60000ms[0m[90m
[2021-04-28T04:56:39Z]       at ClientRequest.<anonymous> (/build/node_modules/got/dist/source/core/index.js:956:65)
```

So to me it looks like one of the polls querying loki logs got wedged and timed out, and that in turn caused the test to fail. I'm thinking the fix could be:
- Reduce the query timeout to e.g. 5s or 10s
- Retry on timeout, rather than failing the test, as long as the wait duration hasn't expired

**Comment by jgehrcke** [comment]
> So to me it looks like one of the polls querying loki logs got wedged and timed out

The test runner mochajs sadly does not show the actual cause near the test failure, but only in the summary.

I was making a fuss about that here: https://github.com/mochajs/mocha/issues/4364 :shrug: 

Here is the error that failed the test:

https://buildkite.com/opstrace/scheduled-main-builds/builds/2186#b5d02062-85da-4276-84e1-815f2da4e050/2796-7966

```
[2021-04-28T04:56:39Z]   25 passing (15m)
[2021-04-28T04:56:39Z]   1 failing
[2021-04-28T04:56:39Z]
[2021-04-28T04:56:39Z]   1) Metric exporter tests
[2021-04-28T04:56:39Z]        Azure exporter:
[2021-04-28T04:56:39Z]      RequestError: Timeout awaiting 'request' for 60000ms
[2021-04-28T04:56:39Z]       at ClientRequest.<anonymous> (/build/node_modules/got/dist/source/core/index.js:956:65)
[2021-04-28T04:56:39Z]       at ClientRequest.EventEmitter.emit (domain.js:467:12)
```

So, it's indeed the `RequestError: Timeout awaiting 'request' for 60000ms`, confirming your assumption.

**Comment by jgehrcke** [comment]
> in the event of a spurious request timeout.

I want to say that as part of running a test suite many times over time, we would to know about those cases when this request wasn't responded to within 60 seconds, which is a pretty different nature compared to say 5 seconds. But well. :)

**Comment by sreis** [comment]
Closing since we haven't had a repro it in 2 months.
