### ISSUE TITLE
ci instability: * exporter: expectation not fulfilled within 300 s

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#615]
failure pattern:
```
[2021-04-29T09:03:33Z]   22 passing (25m)
[2021-04-29T09:03:33Z]   4 failing
[2021-04-29T09:03:33Z]
[2021-04-29T09:03:33Z]   1) Metric exporter tests
[2021-04-29T09:03:33Z]        Cloudwatch exporter:
[2021-04-29T09:03:33Z]      Error: Expectation not fulfilled within 300 s
[2021-04-29T09:03:33Z]       at Object.waitForQueryResult (testutils/index.ts:933:9)
[2021-04-29T09:03:33Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:82:5)
[2021-04-29T09:03:33Z]       at testExporterMetric (test_exporters.ts:181:3)
[2021-04-29T09:03:33Z]       at Context.<anonymous> (test_exporters.ts:259:5)
[2021-04-29T09:03:33Z] 
[2021-04-29T09:03:33Z]   2) Metric exporter tests
[2021-04-29T09:03:33Z]        Stackdriver exporter:
[2021-04-29T09:03:33Z]      Error: Expectation not fulfilled within 300 s
[2021-04-29T09:03:33Z]       at Object.waitForQueryResult (testutils/index.ts:933:9)
[2021-04-29T09:03:33Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:82:5)
[2021-04-29T09:03:33Z]       at testExporterMetric (test_exporters.ts:181:3)
[2021-04-29T09:03:33Z]       at Context.<anonymous> (test_exporters.ts:312:5)
[2021-04-29T09:03:33Z] 
[2021-04-29T09:03:33Z]   3) Metric exporter tests
[2021-04-29T09:03:33Z]        Blackbox exporter:
[2021-04-29T09:03:33Z]      Error: Expectation not fulfilled within 300 s
[2021-04-29T09:03:33Z]       at Object.waitForQueryResult (testutils/index.ts:933:9)
[2021-04-29T09:03:33Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:82:5)
[2021-04-29T09:03:33Z]       at testExporterMetric (test_exporters.ts:181:3)
[2021-04-29T09:03:33Z]       at Context.<anonymous> (test_exporters.ts:368:5)
[2021-04-29T09:03:33Z] 
[2021-04-29T09:03:33Z]   4) Metric exporter tests
[2021-04-29T09:03:33Z]        Azure exporter:
[2021-04-29T09:03:33Z]      Error: Expectation not fulfilled within 120 s
[2021-04-29T09:03:33Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:256:9)
[2021-04-29T09:03:33Z]       at getExporterLog (test_exporters.ts:155:19)
[2021-04-29T09:03:33Z]       at testExporterLog (test_exporters.ts:197:3)
[2021-04-29T09:03:33Z]       at Context.<anonymous> (test_exporters.ts:420:5)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2193#d643d175-3ba0-47d4-b50d-3b2d9c33c1dd/2894-7588

**Comment by jgehrcke** [comment]
```
[2021-04-29T08:45:36Z] 2021-04-29T08:45:36.710Z info: PortForward(tenant-prometheus-default): initialize
[2021-04-29T08:45:36Z] 2021-04-29T08:45:36.710Z info: PortForward(tenant-prometheus-default): exec in child: 'kubectl port-forward --namespace default-tenant statefulsets/prometheus-default-prometheus 0:9090' -- redirect output to /tmp/opstrace-test-remote/kubectl-port-forward--28-1kJj3QXnuco0-.outerr
[2021-04-29T08:45:36Z] 2021-04-29T08:45:36.725Z info: PortForward(tenant-prometheus-default): waiting for port-forward to become ready, deadline in 30s
[2021-04-29T08:45:38Z] 2021-04-29T08:45:38.130Z info: PortForward(tenant-prometheus-default): port-forward listening on port 42207
[2021-04-29T08:45:38Z] 2021-04-29T08:45:38.130Z info: Waiting for target with tenant=default job=exporter-testexporters-rs2wi-cloudwatch via port-forward: http://127.0.0.1:42207/prometheus/api/v1/targets
[2021-04-29T08:45:38Z] 2021-04-29T08:45:38.131Z info: Waiting for query to return a match, deadline in 300s
[2021-04-29T08:50:38Z] 2021-04-29T08:50:38.918Z error: Reached 300s deadline, giving up
[2021-04-29T08:50:38Z] 2021-04-29T08:50:38.918Z info: PortForward(tenant-prometheus-default): send SIGTERM to process with PID 66
[2021-04-29T08:50:38Z] 2021-04-29T08:50:38.918Z info: PortForward(tenant-prometheus-default): waiting for process to terminate
[2021-04-29T08:50:38Z] 2021-04-29T08:50:38.920Z info: PortForward(tenant-prometheus-default): 'exit' handler: process exited. Code: null, signal: SIGTERM
[2021-04-29T08:50:38Z] 2021-04-29T08:50:38.920Z info: PortForward(tenant-prometheus-default): process exited. code: null, signal: SIGTERM
[2021-04-29T08:50:38Z]     1) Cloudwatch exporter
```

**Comment by jgehrcke** [comment]
Between these two lines:
```
[2021-04-29T08:45:38Z] 2021-04-29T08:45:38.131Z info: Waiting for query to return a match, deadline in 300s
[2021-04-29T08:50:38Z] 2021-04-29T08:50:38.918Z error: Reached 300s deadline, giving up
```
we're lacking progress report.

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2221#7ea8fa87-a73e-41cc-8e18-ae7019899473/3265-7936

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/4038#0475c959-6445-4866-85ae-24fa6d35e0b0/6-2183

```
[2021-05-04T18:59:54Z]   21 passing (25m)
[2021-05-04T18:59:54Z]   5 failing
[2021-05-04T18:59:54Z]
[2021-05-04T18:59:54Z]   1) End-to-end alert tests
[2021-05-04T18:59:54Z]        End-to-end alerts for system tenant:
[2021-05-04T18:59:54Z]      Error: Expectation not fulfilled within 30 s
[2021-05-04T18:59:54Z]       at Object.waitForQueryResult (testutils/index.ts:953:9)
[2021-05-04T18:59:54Z]       at getE2EAlertCountMetric (test_alerts.ts:301:23)
[2021-05-04T18:59:54Z]       at testE2EAlertsForTenant (test_alerts.ts:365:17)
[2021-05-04T18:59:54Z]       at Context.<anonymous> (test_alerts.ts:426:5)
[2021-05-04T18:59:54Z] 
[2021-05-04T18:59:54Z]   2) DD API test suite
[2021-05-04T18:59:54Z]        dd_api_insert_single_ts_fragment:
[2021-05-04T18:59:54Z]      Error: Expectation not fulfilled within 30 s
[2021-05-04T18:59:54Z]       at Object.waitForQueryResult (testutils/index.ts:953:9)
[2021-05-04T18:59:54Z]       at Context.<anonymous> (test_dd.ts:297:25)
[2021-05-04T18:59:54Z] 
[2021-05-04T18:59:54Z]   3) Metric exporter tests
[2021-05-04T18:59:54Z]        Stackdriver exporter:
[2021-05-04T18:59:54Z]      Error: Expectation not fulfilled within 300 s
[2021-05-04T18:59:54Z]       at Object.waitForQueryResult (testutils/index.ts:953:9)
[2021-05-04T18:59:54Z]       at getExporterMetric (test_exporters.ts:130:23)
[2021-05-04T18:59:54Z]       at testExporterMetric (test_exporters.ts:182:3)
[2021-05-04T18:59:54Z]       at Context.<anonymous> (test_exporters.ts:312:5)
[2021-05-04T18:59:54Z] 
[2021-05-04T18:59:54Z]   4) Metric exporter tests
[2021-05-04T18:59:54Z]        Blackbox exporter:
[2021-05-04T18:59:54Z]      Error: Expectation not fulfilled within 300 s
[2021-05-04T18:59:54Z]       at Object.waitForQueryResult (testutils/index.ts:953:9)
[2021-05-04T18:59:54Z]       at getExporterMetric (test_exporters.ts:130:23)
[2021-05-04T18:59:54Z]       at testExporterMetric (test_exporters.ts:182:3)
[2021-05-04T18:59:54Z]       at Context.<anonymous> (test_exporters.ts:377:5)
[2021-05-04T18:59:54Z] 
[2021-05-04T18:59:54Z]   5) Metric exporter tests
[2021-05-04T18:59:54Z]        Azure exporter:
[2021-05-04T18:59:54Z]      Error: Expectation not fulfilled within 120 s
[2021-05-04T18:59:54Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:275:9)
[2021-05-04T18:59:54Z]       at getExporterLog (test_exporters.ts:155:19)
[2021-05-04T18:59:54Z]       at testExporterLog (test_exporters.ts:197:3)
[2021-05-04T18:59:54Z]       at Context.<anonymous> (test_exporters.ts:428:5)
[2021-05-04T18:59:54Z] 
```

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/4044#88b7a454-024a-429f-ac70-56eeb9ba5471/2885-7213

**Comment by nickbp** [comment]
Looked at the four listed runs. In each run it was either GCP or AWS failing (not both):

GCP builds:
- scheduled build 2227 may be unrelated, looks like was the cluster failing to come up
- scheduled build 2221 failed on gcp, controller logs show no attempt at deploying exporters
- PR build 4044 also failed on gcp and also shows no mention of deploying the exporters in controller logs

AWS build:
- PR build 4038 failed on AWS and unlike the GCP cases this has controller deploying exporters from looking at the exporter logs. The passes/failures are all over the place across tenants, with two failures to find an expected metric (stackdriver, blackbox) and one failure to find an expected log (azure):
    - cloudwatch passed for both default and system tenants
    - stackdriver failed for the default tenant (scrape target appeared, expected metric not found), and then didn't try the system tenant
    - blackbox passed for the default tenant, then failed for the system tenant (scrape target appeared, expected metric not found)
    - azure passed for the default tenant, then failed for the system tenant (scrape target appeared, expected pod log entry not found)

So in summary there appear to be two "classes" of issues across the three failures:
- GCP: Controller didn't deploy the exporters. Maybe the graphql client in the controller is flaking or failing to connect on GCP specifically? However it looked like the tenant sync worked fine and that also depends on the graphql client. *I think this is the main issue to figure out* since it does imply a bug in the controller's graphql client handling, but annoyingly one that only apparently affects GCP clusters.
- AWS: Controller deployed things and the prometheus scrape target was found by the test, but then it got stuck on waiting for metrics/logs to show up. To be honest this one just feels like a flake or bad timing or something because there isn't a clear pattern to why this specific AWS cluster was so flaky.

**Comment by nickbp** [comment]
Rechecked the logs and it looks like config-api is returning 200 to the POSTs submitting the credentials/exporters, so I wouldn't expect an issue there. But I'm thinking I may add an additional check to GET the credentials/exporters and confirm that they appear in graphql. 
Given that the failure seems to be GCP-specific, at this point I'm _assuming_ the issue is something with GCP networking causing problems with the controller graphql client, rather than anything with getting the configs submitted by the test into graphql.
That should at least narrow down if the problem is with the data getting written to graphql successfully, vs the controller seeing it.

**Comment by jgehrcke** [comment]
> Rechecked the logs and it looks like config-api is returning 200 to the POSTs submitting the credentials/exporters, so I wouldn't expect an issue there.

I ran into this topic yesterday for the first time, quoting myself from Slack:

> GraphQL: wraps errors in 200 OK responses. Oh boy. That's interesting, to say it neutrally! 


Here's what needs to be done conceptually: https://github.com/opstrace/opstrace/blob/d3e53f9650a88b8ed5c09e17fe94fd952fa7d8d9/test/test-remote/test_ui.ts#L187

```
    assert.strictEqual(response.statusCode, 200);

    // GraphQL: 200 OK response does not mean that no error happened.
    const rdata = JSON.parse(response.body);
    assert(rdata.errors === undefined);
```

**Comment by jgehrcke** [comment]
Thanks for the analysis here Nick. Perfect example for how a CI instability is the entry point to debugging actual product issues. Lovely!

**Comment by nickbp** [comment]
Good point about the graphql error behavior. I checked the [go client code](https://github.com/opstrace/opstrace/blob/main/go/pkg/graphql/access.go#L49) and it looks like we should be checking the response for errors, so in theory the data should be getting written to GraphQL okay:
```
	if len(resp.Errors) != 0 {
		return fmt.Errorf("query to %s failed: %s", req.URL.Path, resp.Error())
	}
```

Given that the "no exporters created" cases were all GCP I'm still thinking that there's some issue with the graphql exporters/credentials retrieval on the controller end of things, rather than in config-api writing the entries to graphql, but the recent PR adding logging to the test should at least confirm that down if/when it repro's again.

It looks like the exporters/credentials retrieval in the controller is the only case of the controller using a GraphQL subscription (using `dbSubscriptionClient`), meanwhile the controller's tenant sync is on a 5s poll loop (using `dbClient`). Given that the tenant sync hasn't had these problems, I'm thinking the easiest solution may be to just switch the exporter/credential retrieval to be polling-based as well. There may be something GCP-specific that leads to the subscription client not working consistently, and that feels like it'd be a bit of a pain to deal with figuring out if we can avoid it.

**Comment by sreis** [comment]
```
[2021-05-07T21:09:05Z]   1) End-to-end alert tests
[2021-05-07T21:09:05Z]        End-to-end alerts for system tenant:
[2021-05-07T21:09:05Z]      Error: Expectation not fulfilled within 30 s
[2021-05-07T21:09:05Z]       at Object.waitForQueryResult (testutils/index.ts:953:9)
[2021-05-07T21:09:05Z]       at runMicrotasks (<anonymous>)
[2021-05-07T21:09:05Z]       at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-05-07T21:09:05Z]       at getE2EAlertCountMetric (test_alerts.ts:301:23)
[2021-05-07T21:09:05Z]       at testE2EAlertsForTenant (test_alerts.ts:381:19)
[2021-05-07T21:09:05Z]       at Context.<anonymous> (test_alerts.ts:426:5)
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2244#d16d6938-056c-4ca9-a90d-3c894ca18d69/6-2403

```
[2021-05-09T05:01:41Z]   22 passing (24m)
[2021-05-09T05:01:41Z]   4 failing
[2021-05-09T05:01:41Z]
[2021-05-09T05:01:41Z]   1) Metric exporter tests
[2021-05-09T05:01:41Z]        Cloudwatch exporter:
[2021-05-09T05:01:41Z]      Error: Expectation not fulfilled within 300 s
[2021-05-09T05:01:41Z]       at Object.waitForQueryResult (testutils/index.ts:953:9)
[2021-05-09T05:01:41Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:82:5)
[2021-05-09T05:01:41Z]       at testExporterMetric (test_exporters.ts:184:3)
[2021-05-09T05:01:41Z]       at Context.<anonymous> (test_exporters.ts:262:5)
[2021-05-09T05:01:41Z] 
[2021-05-09T05:01:41Z]   2) Metric exporter tests
[2021-05-09T05:01:41Z]        Stackdriver exporter:
[2021-05-09T05:01:41Z]      Error: Expectation not fulfilled within 300 s
[2021-05-09T05:01:41Z]       at Object.waitForQueryResult (testutils/index.ts:953:9)
[2021-05-09T05:01:41Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:82:5)
[2021-05-09T05:01:41Z]       at testExporterMetric (test_exporters.ts:184:3)
[2021-05-09T05:01:41Z]       at Context.<anonymous> (test_exporters.ts:315:5)
[2021-05-09T05:01:41Z] 
[2021-05-09T05:01:41Z]   3) Metric exporter tests
[2021-05-09T05:01:41Z]        Blackbox exporter:
[2021-05-09T05:01:41Z]      Error: Expectation not fulfilled within 300 s
[2021-05-09T05:01:41Z]       at Object.waitForQueryResult (testutils/index.ts:953:9)
[2021-05-09T05:01:41Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:82:5)
[2021-05-09T05:01:41Z]       at testExporterMetric (test_exporters.ts:184:3)
[2021-05-09T05:01:41Z]       at Context.<anonymous> (test_exporters.ts:371:5)
[2021-05-09T05:01:41Z] 
[2021-05-09T05:01:41Z]   4) Metric exporter tests
[2021-05-09T05:01:41Z]        Azure exporter:
[2021-05-09T05:01:41Z]      Error: Expectation not fulfilled within 120 s
[2021-05-09T05:01:41Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:275:9)
[2021-05-09T05:01:41Z]       at getExporterLog (test_exporters.ts:158:19)
[2021-05-09T05:01:41Z]       at testExporterLog (test_exporters.ts:200:3)
[2021-05-09T05:01:41Z]       at Context.<anonymous> (test_exporters.ts:423:5)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2252#3206d69e-b2a0-4394-98ae-d4a6f4657426

**Comment by sreis** [comment]
Another one: https://buildkite.com/opstrace/scheduled-main-builds/builds/2312#d7f10370-8eec-40e5-b86b-d10a310862f7/3442-8213

```
[2021-05-19T01:07:14Z]   22 passing (27m)
[2021-05-19T01:07:14Z]   4 failing
[2021-05-19T01:07:14Z]
[2021-05-19T01:07:14Z]   1) Metric exporter tests
[2021-05-19T01:07:14Z]        Cloudwatch exporter:
[2021-05-19T01:07:14Z]      Error: Expectation not fulfilled within 300 s
[2021-05-19T01:07:14Z]       at Object.waitForQueryResult (testutils/index.ts:955:9)
[2021-05-19T01:07:14Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:82:5)
[2021-05-19T01:07:14Z]       at testExporterMetric (test_exporters.ts:184:3)
[2021-05-19T01:07:14Z]       at Context.<anonymous> (test_exporters.ts:262:5)
[2021-05-19T01:07:14Z] 
[2021-05-19T01:07:14Z]   2) Metric exporter tests
[2021-05-19T01:07:14Z]        Stackdriver exporter:
[2021-05-19T01:07:14Z]      Error: Expectation not fulfilled within 300 s
[2021-05-19T01:07:14Z]       at Object.waitForQueryResult (testutils/index.ts:955:9)
[2021-05-19T01:07:14Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:82:5)
[2021-05-19T01:07:14Z]       at testExporterMetric (test_exporters.ts:184:3)
[2021-05-19T01:07:14Z]       at Context.<anonymous> (test_exporters.ts:315:5)
[2021-05-19T01:07:14Z] 
[2021-05-19T01:07:14Z]   3) Metric exporter tests
[2021-05-19T01:07:14Z]        Blackbox exporter:
[2021-05-19T01:07:14Z]      Error: Expectation not fulfilled within 300 s
[2021-05-19T01:07:14Z]       at Object.waitForQueryResult (testutils/index.ts:955:9)
[2021-05-19T01:07:14Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:82:5)
[2021-05-19T01:07:14Z]       at testExporterMetric (test_exporters.ts:184:3)
[2021-05-19T01:07:14Z]       at Context.<anonymous> (test_exporters.ts:371:5)
[2021-05-19T01:07:14Z] 
[2021-05-19T01:07:14Z]   4) Metric exporter tests
[2021-05-19T01:07:14Z]        Azure exporter:
[2021-05-19T01:07:14Z]      Error: Expectation not fulfilled within 120 s
[2021-05-19T01:07:14Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:275:9)
[2021-05-19T01:07:14Z]       at getExporterLog (test_exporters.ts:158:19)
[2021-05-19T01:07:14Z]       at testExporterLog (test_exporters.ts:200:3)
[2021-05-19T01:07:14Z]       at Context.<anonymous> (test_exporters.ts:423:5)
[2021-05-19T01:07:14Z] 
```

**Comment by nickbp** [comment]
Checked the scheduled build history and that failure (on `70458d3`, preceding the `fd39618` fix by a few commits) looks like it was the last one. So it looks like the "fix" of just switching to polling did the trick.

**Comment by jgehrcke** [comment]
Btw @nickbp thanks for the great commit msg and for following up here.

**Comment by jgehrcke** [comment]
There are no guarantees around GraphQL subscriptions.

> Neither operation includes limitations or guarantees of nonfunctional network delivery capabilities, such as guaranteed, in-order delivery

https://medium.com/open-graphql/graphql-subscriptions-vs-live-queries-e38302c7ab8e

Old insight: always poll for correctness and simplicity, maybe add a watcher/subscription later for latency optimization. (same for consuming other systems such as ZooKeeper).
