### ISSUE TITLE
ci instability: log push load with pbuf: req timeout during POST

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#653]
```
[2021-04-30T04:55:03Z]   25 passing (16m)
[2021-04-30T04:55:03Z]   1 failing
[2021-04-30T04:55:03Z]
[2021-04-30T04:55:03Z]   1) Loki API test suite
[2021-04-30T04:55:03Z]        log push load with pbuf, multi stream fragments:
[2021-04-30T04:55:03Z]      RequestError: Timeout awaiting 'request' for 60000ms
[2021-04-30T04:55:03Z]       at ClientRequest.<anonymous> (/build/node_modules/got/dist/source/core/index.js:956:65)
[2021-04-30T04:55:03Z]       at ClientRequest.EventEmitter.emit (domain.js:467:12)
[2021-04-30T04:55:03Z]       at ClientRequest.origin.emit (/build/node_modules/@szmarczak
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2198#2b86b84f-c45b-458b-8697-6803ba2f3a28/2880-8349

**Comment by sreis** [comment]
```
[2021-06-12T16:48:25Z]
[2021-06-12T16:48:25Z]   1) Loki API test suite
[2021-06-12T16:48:25Z]        log push load with pbuf, multi stream fragments:
[2021-06-12T16:48:25Z]      RequestError: Timeout awaiting 'request' for 60000ms
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2467#5e040f69-d852-46a4-b07f-bfdfafdbdb79/2652-7032

**Comment by terrcin** [comment]
```
[2021-07-13T05:43:59Z]   1) Loki API test suite
--
  | [2021-07-13T05:43:59Z]        POST protobuf to /loki/api/v1/push, then query:
  | [2021-07-13T05:43:59Z]      RequestError: Timeout awaiting 'request' for 60000ms
  | [2021-07-13T05:43:59Z]       at ClientRequest.<anonymous> (/build/node_modules/got/dist/source/core/index.js:956:65)
  | [2021-07-13T05:43:59Z]       at Object.onceWrapper (node:events:514:26)
  | [2021-07-13T05:43:59Z]       at ClientRequest.emit (node:events:406:35)
  | [2021-07-13T05:43:59Z]       at ClientRequest.emit (node:domain:470:12)
  | [2021-07-13T05:43:59Z]       at ClientRequest.origin.emit (/build/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
  | [2021-07-13T05:43:59Z]       at TLSSocket.socketErrorListener (node:_http_client:447:9)
  | [2021-07-13T05:43:59Z]       at TLSSocket.emit (node:events:394:28)
  | [2021-07-13T05:43:59Z]       at TLSSocket.emit (node:domain:470:12)
  | [2021-07-13T05:43:59Z]       at emitErrorNT (node:internal/streams/destroy:193:8)
  | [2021-07-13T05:43:59Z]       at emitErrorCloseNT (node:internal/streams/destroy:158:3)
  | [2021-07-13T05:43:59Z]       at processTicksAndRejections (node:internal/process/task_queues:83:21)
  | [2021-07-13T05:43:59Z]       at Timeout.timeoutHandler [as _onTimeout] (/build/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
  | [2021-07-13T05:43:59Z]       at listOnTimeout (node:internal/timers:559:11)
  | [2021-07-13T05:43:59Z]       at processTimers (node:internal/timers:500:7)
  | [2021-07-13T05:43:59Z]
  | [2021-07-13T05:43:59Z]
  | [2021-07-13T05:43:59Z]
  | error Command failed with exit code 1.
  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  | [2021-07-13T05:43:59Z] make[1]: *** [Makefile:601: test-remote] Error 1
```

https://buildkite.com/opstrace/prs/builds/5062#e31ee33a-9b93-4a54-8b98-10b529007b49/2990-7194

https://github.com/opstrace/opstrace/pull/1037

**Comment by sreis** [comment]
```
[2021-07-22T17:09:52Z]   1) Loki API test suite
[2021-07-22T17:09:52Z]        log push load with pbuf, multi stream fragments:
[2021-07-22T17:09:52Z]      RequestError: Timeout awaiting 'request' for 60000ms
[2021-07-22T17:09:52Z]       at ClientRequest.<anonymous> (/build/node_modules/got/dist/source/core/index.js:956:65)
[2021-07-22T17:09:52Z]       at Object.onceWrapper (node:events:514:26)
[2021-07-22T17:09:52Z]       at ClientRequest.emit (node:events:406:35)
[2021-07-22T17:09:52Z]       at ClientRequest.emit (node:domain:470:12)
[2021-07-22T17:09:52Z]       at ClientRequest.origin.emit (/build/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
[2021-07-22T17:09:52Z]       at TLSSocket.socketErrorListener (node:_http_client:447:9)
[2021-07-22T17:09:52Z]       at TLSSocket.emit (node:events:394:28)
[2021-07-22T17:09:52Z]       at TLSSocket.emit (node:domain:470:12)
[2021-07-22T17:09:52Z]       at emitErrorNT (node:internal/streams/destroy:157:8)
[2021-07-22T17:09:52Z]       at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[2021-07-22T17:09:52Z]       at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2021-07-22T17:09:52Z]       at Timeout.timeoutHandler [as _onTimeout] (/build/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
[2021-07-22T17:09:52Z]       at listOnTimeout (node:internal/timers:559:11)
[2021-07-22T17:09:52Z]       at processTimers (node:internal/timers:500:7)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2713#3d8a4aa1-f2f5-4bfe-97f8-ceac02872604/134-5186

**Comment by nickbp** [comment]
No new instances reported since July
