### ISSUE TITLE
Error creating cluster on GCP: connect ETIMEDOUT 

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#682]
`**Describe` the bug**

```
[2021-05-05T01:00:14Z] 2021-05-05T01:00:14.616Z error: error during cluster creation (attempt 3):
[2021-05-05T01:00:14Z] Error: connect ETIMEDOUT 34.94.169.154:443
[2021-05-05T01:00:14Z]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
[2021-05-05T01:00:14Z]   errno: -110,
[2021-05-05T01:00:14Z]   code: 'ETIMEDOUT',
[2021-05-05T01:00:14Z]   syscall: 'connect',
[2021-05-05T01:00:14Z]   address: '34.94.169.154',
[2021-05-05T01:00:14Z]   port: 443
[2021-05-05T01:00:14Z] }
[2021-05-05T01:00:14Z] 2021-05-05T01:00:14.617Z debug: `err?.stack`: Error: connect ETIMEDOUT 34.94.169.154:443
[2021-05-05T01:00:14Z]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
[2021-05-05T01:00:14Z] 2021-05-05T01:00:14.617Z error: JSON representation of err: {
[2021-05-05T01:00:14Z]   "errno": -110,
[2021-05-05T01:00:14Z]   "code": "ETIMEDOUT",
[2021-05-05T01:00:14Z]   "syscall": "connect",
[2021-05-05T01:00:14Z]   "address": "34.94.169.154",
[2021-05-05T01:00:14Z]   "port": 443
[2021-05-05T01:00:14Z] }
[2021-05-05T01:00:14Z] 2021-05-05T01:00:14.617Z error: 3 attempt(s) failed. Stop retrying. Exit.
[2021-05-05T01:00:14Z] 2021-05-05T01:00:14.617Z debug: shut down logger, then exit with code 1
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2227#a8fd0ac7-55d7-4934-aaed-31b3f2f260b8/240-2267

**Comment by jgehrcke** [comment]
A proper solution for this ticket here would involve making the k8s client lib retry all tcp-level transient issues. Quoting myself from elsewhere:

> we should find an approach for centrally hooking in to this client lib to make all HTTP client interaction retry for at least TCP-level transient problems, such as connect() and recv() timeouts, kubernetes-client/javascript#96 is a little sad, but there at least is the invitation for contributions.
