### ISSUE TITLE
Error: Failed to download chromium

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#694]
**Describe the bug**
```
error /build/node_modules/playwright: Command failed.
[2021-05-06T08:07:52Z] Exit code: 1
[2021-05-06T08:07:52Z] Command: node install.js
[2021-05-06T08:07:52Z] Arguments:
[2021-05-06T08:07:52Z] Directory: /build/node_modules/playwright
[2021-05-06T08:07:52Z] Output:
[2021-05-06T08:07:52Z] (node:1965) UnhandledPromiseRejectionWarning: Error: Failed to download chromium, caused by
[2021-05-06T08:07:52Z] Error: unexpected end of file
[2021-05-06T08:07:52Z]     at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
[2021-05-06T08:07:52Z]     at /build/node_modules/playwright/lib/install/installer.js:130:19
[2021-05-06T08:07:52Z]     at async validateCache (/build/node_modules/playwright/lib/install/installer.js:129:9)
[2021-05-06T08:07:52Z]     at async installBrowsersWithProgressBar (/build/node_modules/playwright/lib/install/installer.js:80:9)
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2235#84a7cb41-c757-410d-b2e1-0420a0fe47b5/1709-1758

**Comment by jgehrcke** [comment]
closing in favor of https://github.com/opstrace/opstrace/issues/275
