### ISSUE TITLE
ci instability: playwright error: Failed to download chromium/firefox

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#696]
Have had this happen three times in the list 16 hours:

```
[2021-05-06T08:07:53Z] Exit code: 1
--
  | [2021-05-06T08:07:53Z] Command: node install.js
  | [2021-05-06T08:07:53Z] Arguments:
  | [2021-05-06T08:07:53Z] Directory: /build/node_modules/playwright
  | [2021-05-06T08:07:53Z] Output:
  | [2021-05-06T08:07:53Z] (node:2035) UnhandledPromiseRejectionWarning: Error: Failed to download chromium, caused by
  | [2021-05-06T08:07:53Z] Error: ENOENT: no such file or directory, open '/tmp/playwright-download-chromium-ubuntu20.04-857950.zip'
  | [2021-05-06T08:07:53Z]     at /build/node_modules/playwright/lib/install/installer.js:130:19
  | [2021-05-06T08:07:53Z]     at async validateCache (/build/node_modules/playwright/lib/install/installer.js:129:9)
  | [2021-05-06T08:07:53Z]     at async installBrowsersWithProgressBar (/build/node_modules/playwright/lib/install/installer.js:80:9)
```

**Comment by nickbp** [comment]
Similar failure to download Firefox in PR CI from last night: https://buildkite.com/opstrace/prs/builds/4063#eb4aeec6-d39a-4119-a160-63dfe4937061

Rebuilding the `lint, compile build` step in the Buildkite UI succeeded and the CI resumed from there.

**Comment by jgehrcke** [comment]
> Have had this happen three times in the list 16 hours:

It's always good to link to the original build log for some additional context @terrcin  :)

**Comment by terrcin** [comment]
Again, this time Firefox
https://buildkite.com/opstrace/prs/builds/4180#ddeb6a5e-ee6f-48bb-bfe1-cebe7f4f03d5/3486-3535

**Comment by jgehrcke** [comment]
```
[2021-05-25T12:25:29Z] Output:
[2021-05-25T12:25:29Z] (node:4655) UnhandledPromiseRejectionWarning: Error: Failed to download chromium, caused by
[2021-05-25T12:25:29Z] Error: ENOENT: no such file or directory, open '/tmp/playwright-download-chromium-ubuntu20.04-878941.zip'
[2021-05-25T12:25:29Z]     at /build/node_modules/playwright/lib/install/installer.js:130:19
[2021-05-25T12:25:29Z]     at async validateCache (/build/node_modules/playwright/lib/install/installer.js:129:9)
[2021-05-25T12:25:29Z]     at async installBrowsersWithProgressBar (/build/node_modules/playwright/lib/install/installer.js:80:9)
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2356#74a5d36d-1419-4f6c-bebc-346afbb03d29/3038-3079

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2405#b84a169d-d0d1-465f-9a50-2dded8dbb215/4517-4559

```
[2021-06-02T08:24:07Z] (node:4401) UnhandledPromiseRejectionWarning: Error: Failed to download firefox, caused by
[2021-06-02T08:24:07Z] Error: ENOENT: no such file or directory, open '/tmp/playwright-download-firefox-ubuntu20.04-1250.zip'
```

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2405#b84a169d-d0d1-465f-9a50-2dded8dbb215/4517-4564
```
[2021-06-02T08:24:07Z] chromium v878941 downloaded to /build/.cache/ms-playwright/chromium-878941
[2021-06-02T08:24:07Z]
[2021-06-02T08:24:07Z] (node:4401) UnhandledPromiseRejectionWarning: Error: Failed to download firefox, caused by
[2021-06-02T08:24:07Z] Error: ENOENT: no such file or directory, open '/tmp/playwright-download-firefox-ubuntu20.04-1250.zip'
[2021-06-02T08:24:07Z]     at /build/node_modules/playwright/lib/install/installer.js:130:19
[2021-06-02T08:24:07Z]     at async validateCache (/build/node_modules/playwright/lib/install/installer.js:129:9)
[2021-06-02T08:24:07Z]     at async installBrowsersWithProgressBar (/build/node_modules/playwright/lib/install/installer.js:80:9)
[2021-06-02T08:24:07Z] (Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by terrcin** [comment]
FYI: I've put up a [PR](https://github.com/opstrace/opstrace/issues/696) that only installs chromium with playwright.

I'm actively working on multi-browser playwright tests at the moment, but figured it wouldn't hurt to put this PR out there to see what effect it had. Obviously the underlying issue still needsto be resolved.

**Comment by terrcin** [comment]
I now have a different and [betterer PR](https://github.com/opstrace/opstrace/pull/851) that's passing CI, but I'm not 100% certain it will solve the problem as I need it to occur so I can see if it the PR corrects for it. Yay intermittent. I'm running CI a few times and checking the output. If it doesn't break CI then it can't make things worse.

**Comment by terrcin** [comment]
Closing issue as it's been two weeks since I merged the PR trying to fix this and it's not been reported again. :partying_face:
