### ISSUE TITLE
AWS: destroy: fails when non-Opstrace EKS cluster is visible

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#734]
```
[2021-05-14T13:06:01Z] 2021-05-14T13:06:01.520Z info: listing EKS clusters for region ap-east-1 failed with a 403 error (not authorized), skip region
[2021-05-14T13:06:01Z] 2021-05-14T13:06:01.552Z debug: aws sdk: [AWS eks 200 0.184s 0 retries] describeCluster({ name: 'chris6' })
[2021-05-14T13:06:01Z] 2021-05-14T13:06:01.574Z debug: aws sdk: [AWS eks 200 0.287s 0 retries] describeCluster({ name: 'sreis-test' })
[2021-05-14T13:06:01Z] AssertionError [ERR_ASSERTION]: undefined == true
[2021-05-14T13:06:01Z]     at EKSgetOpstraceClustersInRegion (/snapshot/build/packages/cli/src/list.ts:203:5)
[2021-05-14T13:06:01Z]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-05-14T13:06:01Z]     at async Promise.all (index 17)
[2021-05-14T13:06:01Z]     at EKSgetOpstraceClustersAcrossManyRegions (/snapshot/build/packages/cli/src/list.ts:115:58)
[2021-05-14T13:06:01Z]     at Object.list (/snapshot/build/packages/cli/src/list.ts:38:22)
[2021-05-14T13:06:01Z]     at main (/snapshot/build/packages/cli/src/index.ts:96:5)
[2021-05-14T13:06:01Z]     at mainWrapper (/snapshot/build/packages/cli/src/index.ts:584:5)
[2021-05-14T13:06:01Z] + teardown
[2021-05-14T13:06:01Z] + LAST_EXITCODE_BEFORE_TEARDOWN=1
```

https://github.com/opstrace/opstrace/blob/cfe2bc6fdca8f70f722bedd813366e227898177b/packages/cli/src/list.ts#L202

```
    const ocn = dcresp.cluster?.tags?.opstrace_cluster_name;
    assert(ocn);
    assert(dcresp.cluster);
```

**Comment by sreis** [comment]
Created that just now using terraform to test the operator. It's not an opstrace cluster. 

Should the CLI abort in this scenario?

**Comment by jgehrcke** [comment]
I think I introduced a bug with https://github.com/opstrace/opstrace/commit/b0db65f083f93f8ea1912dc4ef0778ebc49d7c73 where this assertion blows up for any EKS cluster that is listed that is not an Opstrace cluster.

**Comment by jgehrcke** [comment]
Huh. When working on the patch I realized that I added the assertions to get rid of compiler warnings in code below. Oh oh. Patch here: https://github.com/opstrace/opstrace/pull/735/files

**Comment by jgehrcke** [comment]
Adjusted the title to clarify the actual scope/significance of this bug.
