### ISSUE TITLE
Error creating externaldns policy

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#739]
**Describe the bug**

The Policy does not exist and a create request is issued and did not fail
```
[2021-05-16T13:27:43Z] 2021-05-16T13:27:43.957Z info: Ensuring upgrade-bk-609-318-a-externaldns policy exists
[2021-05-16T13:27:44Z] 2021-05-16T13:27:44.670Z debug: aws sdk: [AWS iam 200 0.712s 0 retries] listPolicies({})
[2021-05-16T13:27:45Z] 2021-05-16T13:27:45.016Z debug: aws sdk: [AWS iam 200 0.345s 0 retries] createPolicy({
[2021-05-16T13:27:45Z]   PolicyName: 'upgrade-bk-609-318-a-externaldns',
[2021-05-16T13:27:45Z]   PolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"route53:GetChange","Resource":"arn:aws:route53:::change/*"},{"Effect":"Allow","Action":["route53:ChangeResourceRecordSets"],"Resource":["arn:aws:route53:::hostedzone/*"]},{"Effect":"Allow","Action":["route53:ListHostedZones","route53:ListHostedZonesByName","route53:ListResourceRecordSets"],"Resource":["*"]}]}'
[2021-05-16T13:27:45Z] })
```

The `listPolicies` request then doesn't seem to return any values and retries the [create request which fails](https://buildkite.com/opstrace/upgrade-tests/builds/609#f0f9506e-531b-43ff-841d-734f3df17411/1756-9826). This [happens twice](https://buildkite.com/opstrace/upgrade-tests/builds/609#f0f9506e-531b-43ff-841d-734f3df17411/1756-10574
) and then stops retrying failing the build.

```
[2021-05-16T13:28:19Z] 2021-05-16T13:28:19.110Z info: Ensuring upgrade-bk-609-318-a-externaldns policy exists
[2021-05-16T13:28:19Z] 2021-05-16T13:28:19.551Z debug: aws sdk: [AWS iam 200 0.441s 0 retries] listPolicies({})
[2021-05-16T13:28:19Z] 2021-05-16T13:28:19.891Z debug: aws-sdk-js request failed (attempt 0): EntityAlreadyExists: A policy called upgrade-bk-609-318-a-externaldns already exists. Duplicate names are not allowed. (retryable, according to sdk: false), retry in 1.36 seconds
[2021-05-16T13:28:19Z] 2021-05-16T13:28:19.892Z debug: aws sdk: [AWS iam 409 0.34s 0 retries] createPolicy({
[2021-05-16T13:28:19Z]   PolicyName: 'upgrade-bk-609-318-a-externaldns',
[2021-05-16T13:28:19Z]   PolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"route53:GetChange","Resource":"arn:aws:route53:::change/*"},{"Effect":"Allow","Action":["route53:ChangeResourceRecordSets"],"Resource":["arn:aws:route53:::hostedzone/*"]},{"Effect":"Allow","Action":["route53:ListHostedZones","route53:ListHostedZonesByName","route53:ListResourceRecordSets"],"Resource":["*"]}]}'
[2021-05-16T13:28:19Z] })
[2021-05-16T13:28:19Z] 2021-05-16T13:28:19.893Z error: error during cluster creation (attempt 2):
[2021-05-16T13:28:19Z] EntityAlreadyExists: A policy called upgrade-bk-609-318-a-externaldns already exists. Duplicate names are not allowed.
[2021-05-16T13:28:19Z]     at Request.extractError (/snapshot/build/node_modules/aws-sdk/lib/protocol/query.js:50:29)
[2021-05-16T13:28:19Z]     at Request.callListeners (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
[2021-05-16T13:28:19Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[2021-05-16T13:28:19Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/request.js:688:14)
[2021-05-16T13:28:19Z]     at Request.transition (/snapshot/build/node_modules/aws-sdk/lib/request.js:22:10)
[2021-05-16T13:28:19Z]     at AcceptorStateMachine.runTo (/snapshot/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
[2021-05-16T13:28:19Z]     at /snapshot/build/node_modules/aws-sdk/lib/state_machine.js:26:10
[2021-05-16T13:28:19Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:38:9)
[2021-05-16T13:28:19Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:690:12)
[2021-05-16T13:28:19Z]     at Request.callListeners (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
[2021-05-16T13:28:19Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[2021-05-16T13:28:19Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/request.js:688:14)
[2021-05-16T13:28:19Z]     at Request.transition (/snapshot/build/node_modules/aws-sdk/lib/request.js:22:10)
[2021-05-16T13:28:19Z]     at AcceptorStateMachine.runTo (/snapshot/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
[2021-05-16T13:28:19Z]     at /snapshot/build/node_modules/aws-sdk/lib/state_machine.js:26:10
[2021-05-16T13:28:19Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:38:9)
[2021-05-16T13:28:19Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:690:12)
[2021-05-16T13:28:19Z]     at Request.callListeners (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
[2021-05-16T13:28:19Z]     at callNextListener (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
[2021-05-16T13:28:19Z]     at IncomingMessage.onEnd (/snapshot/build/node_modules/aws-sdk/lib/event_listeners.js:313:13)
[2021-05-16T13:28:19Z]     at IncomingMessage.emit (events.js:327:22)
[2021-05-16T13:28:19Z]     at IncomingMessage.EventEmitter.emit (domain.js:485:12)
[2021-05-16T13:28:19Z]     at endReadableNT (_stream_readable.js:1224:12)
[2021-05-16T13:28:19Z]     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[2021-05-16T13:28:19Z]   code: 'EntityAlreadyExists',
[2021-05-16T13:28:19Z]   time: 2021-05-16T13:28:19.891Z,
[2021-05-16T13:28:19Z]   requestId: 'b5ac1fe8-4d9d-4751-b590-2eb7b91b988d',
[2021-05-16T13:28:19Z]   statusCode: 409,
[2021-05-16T13:28:19Z]   retryable: false,
[2021-05-16T13:28:19Z]   retryDelay: 1356.6671434119148
[2021-05-16T13:28:19Z] }
```

**Comment by sreis** [comment]
https://buildkite.com/opstrace/upgrade-tests/builds/703#693f9298-d0ac-491e-bbaa-12266d5025ca/533-1755

```
[2021-05-31T08:54:51Z] 2021-05-31T08:54:51.184Z info: Ensuring upgrade-bk-703-17b-a-externaldns policy exists
[2021-05-31T08:54:51Z] 2021-05-31T08:54:51.795Z debug: aws sdk: [AWS iam 200 0.611s 0 retries] listPolicies({})
[2021-05-31T08:54:52Z] 2021-05-31T08:54:52.195Z debug: aws sdk: [AWS iam 200 0.398s 0 retries] createPolicy({
[2021-05-31T08:54:52Z]   PolicyName: 'upgrade-bk-703-17b-a-externaldns',
[2021-05-31T08:54:52Z]   PolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"route53:GetChange","Resource":"arn:aws:route53:::change/*"},{"Effect":"Allow","Action":["route53:ChangeResourceRecordSets"],"Resource":["arn:aws:route53:::hostedzone/*"]},{"Effect":"Allow","Action":["route53:ListHostedZones","route53:ListHostedZonesByName","route53:ListResourceRecordSets"],"Resource":["*"]}]}'
[2021-05-31T08:54:52Z] })
[2021-05-31T08:54:53Z] 2021-05-31T08:54:53.883Z debug: aws sdk: [AWS iam 200 0.686s 0 retries] listPolicies({})
[2021-05-31T08:54:54Z] 2021-05-31T08:54:54.180Z debug: aws-sdk-js request failed (attempt 0): EntityAlreadyExists: A policy called upgrade-bk-703-17b-a-externaldns already exists. Duplicate names are not allowed. (retryable, according to sdk: false), retry in 1.64 seconds
[2021-05-31T08:54:54Z] 2021-05-31T08:54:54.180Z debug: aws sdk: [AWS iam 409 0.296s 0 retries] createPolicy({
[2021-05-31T08:54:54Z]   PolicyName: 'upgrade-bk-703-17b-a-externaldns',
[2021-05-31T08:54:54Z]   PolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"route53:GetChange","Resource":"arn:aws:route53:::change/*"},{"Effect":"Allow","Action":["route53:ChangeResourceRecordSets"],"Resource":["arn:aws:route53:::hostedzone/*"]},{"Effect":"Allow","Action":["route53:ListHostedZones"
```

The AWS IAM page lists the policy that failed the test. The creation date matches the first create request sent.

![Screenshot from 2021-05-31 10-31-33](https://user-images.githubusercontent.com/495294/120181409-8c9dc000-c1fc-11eb-8a57-1cbed08fcf41.png)

FTR, the failure occurs creating the initial cluster and not during the upgrade.

**Comment by sreis** [comment]
All the tests failed since yesterday.

https://buildkite.com/opstrace/upgrade-tests/builds/707#5b1811d7-7b4a-4489-8661-c22889022c03/537-1817
https://buildkite.com/opstrace/upgrade-tests/builds/708#8f462194-1c7c-4b42-829c-689e4db1c7ae/535-1828
https://buildkite.com/opstrace/upgrade-tests/builds/706#e5a7aa11-c0b6-45ac-88da-6f685f2e3cfa/532-1808
https://buildkite.com/opstrace/upgrade-tests/builds/705#15dd62c9-f158-4f0b-87be-646096fc0eef/537-1832
https://buildkite.com/opstrace/upgrade-tests/builds/704#8ecf3c4f-8ffb-4b18-8a34-d9edefb267bf/534-1810

AWS IAM page lists all the policies:

![Screenshot from 2021-06-01 08-50-10](https://user-images.githubusercontent.com/495294/120295308-8d932800-c2b6-11eb-8955-6977f7201702.png)

**Comment by nickbp** [comment]
No new instances since linked #818, so might have been fixed by that
