### ISSUE TITLE
End-to-end alerts for default tenant test failed with TypeError: Cannot read property 'result' of undefined

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#759]
**Describe the bug**

In a [scheduled upgrade test](https://buildkite.com/opstrace/upgrade-tests/builds/624#3d946ce3-f1b5-4dd7-a26a-3a025a39ffdd/6-5283):

```
[2021-05-19T01:44:16Z]   25 passing (16m)
[2021-05-19T01:44:16Z]   1 failing
[2021-05-19T01:44:16Z]
[2021-05-19T01:44:16Z]   1) End-to-end alert tests
[2021-05-19T01:44:16Z]        End-to-end alerts for default tenant:
[2021-05-19T01:44:16Z]      TypeError: Cannot read property 'result' of undefined
[2021-05-19T01:44:16Z]       at /build/test/test-remote/testutils/metrics.ts:53:39
[2021-05-19T01:44:16Z]       at Object.waitForQueryResult (testutils/index.ts:948:24)
[2021-05-19T01:44:16Z]       at runMicrotasks (<anonymous>)
[2021-05-19T01:44:16Z]       at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2021-05-19T01:44:16Z]       at getE2EAlertCountMetric (test_alerts.ts:301:23)
[2021-05-19T01:44:16Z]       at testE2EAlertsForTenant (test_alerts.ts:381:19)
[2021-05-19T01:44:16Z]       at Context.<anonymous> (test_alerts.ts:422:5)
```

**Comment by nickbp** [comment]
Only occurred once in May. IIRC the E2E alert tests had some work done so maybe this had been fixed in the tests.
