### ISSUE TITLE
Error: kubectl port-forward setup failed: Error from server: etcdserver: request timed out

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#774]
**Describe the bug**

After an upgrade `kubectl` failed to set up port forwarding. Looks like a transient network error since all the other tests are green.

https://buildkite.com/opstrace/upgrade-tests/builds/630#3a800d4f-0220-4664-9954-7cf8b1e0413f/6-2265

```
2021-05-20T01:46:00Z]   1) Metric exporter tests
[2021-05-20T01:46:00Z]        Cloudwatch exporter:
[2021-05-20T01:46:00Z]      Error: kubectl port-forward setup failed
[2021-05-20T01:46:00Z]       at PortForward.setup (testutils/portforward.ts:245:11)
[2021-05-20T01:46:00Z]       at Object.waitForPrometheusTarget (testutils/metrics.ts:75:21)
[2021-05-20T01:46:00Z]       at testExporterMetric (test_exporters.ts:184:3)
[2021-05-20T01:46:00Z]       at Context.<anonymous> (test_exporters.ts:271:5)
```

```
[2021-05-20T01:38:19Z] 2021-05-20T01:38:19.794Z info: PortForward(tenant-prometheus-system): exec in child: 'kubectl port-forward --namespace system-tenant statefulsets/prometheus-system-prometheus 0:9090' -- redirect output to /tmp/opstrace-test-remote/kubectl-port-forward--30-ilJ0blxRNgcc-.outerr
[2021-05-20T01:38:19Z] 2021-05-20T01:38:19.812Z info: PortForward(tenant-prometheus-system): waiting for port-forward to become ready, deadline in 30s
[2021-05-20T01:38:28Z] 2021-05-20T01:38:28.578Z info: PortForward(tenant-prometheus-system): 'exit' handler: process exited. Code: 1, signal: null
[2021-05-20T01:38:28Z] 2021-05-20T01:38:28.654Z error: PortForward(tenant-prometheus-system): kubectl process exited unexpectedly, stop waiting
[2021-05-20T01:38:28Z] 2021-05-20T01:38:28.655Z info: PortForward(tenant-prometheus-system): child process exit code: 1
[2021-05-20T01:38:28Z] 2021-05-20T01:38:28.655Z info: PortForward(tenant-prometheus-system): process stdout/err:
[2021-05-20T01:38:28Z] Error from server: etcdserver: request timed out
```

**Comment by nickbp** [comment]
Only seen once in May, might have been very unlucky. IIRC kubectl port-forward handling in the test suite has had some cleanup which could have helped.
