### ISSUE TITLE
test_ui_with_headless_browser failed: page.goto: net::ERR_NETWORK_CHANGED

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#826]
```
[2021-06-02T21:19:06Z]   1) test_ui_with_headless_browser
[2021-06-02T21:19:06Z]        "before all" hook for "create_tenant_and_use_custom_authn_token":
[2021-06-02T21:19:06Z]      page.goto: net::ERR_NETWORK_CHANGED at https://upgrade-bk-720-a02-g.opstrace.io
[2021-06-02T21:19:06Z] =========================== logs ===========================
[2021-06-02T21:19:06Z] navigating to "https://upgrade-bk-720-a02-g.opstrace.io", waiting until "load"
[2021-06-02T21:19:06Z] ============================================================
[2021-06-02T21:19:06Z] Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```
https://buildkite.com/opstrace/upgrade-tests/builds/720#49dc73fc-391a-451c-a368-06fc48f8296e/6978-7067

**Comment by sreis** [comment]
Same `net::ERR_NETWORK_CHANGED` error this time in a different test.

```
[2021-06-22T09:39:06Z]   1) test_ui_api
[2021-06-22T09:39:06Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-06-22T09:39:06Z]      page.goto: net::ERR_NETWORK_CHANGED at https://upgrade-bk-839-d76-g.opstrace.io
[2021-06-22T09:39:06Z] =========================== logs ===========================
[2021-06-22T09:39:06Z] navigating to "https://upgrade-bk-839-d76-g.opstrace.io", waiting until "load"
[2021-06-22T09:39:06Z] ============================================================
[2021-06-22T09:39:06Z] Note: use DEBUG=pw:api environment variable to capture Playwright logs.
[2021-06-22T09:39:06Z]   Error: 
[2021-06-22T09:39:06Z]       at Object.captureStackTrace (/build/node_modules/playwright/lib/utils/stackTrace.js:51:19)
[2021-06-22T09:39:06Z]       at Connection.sendMessageToServer (/build/node_modules/playwright/lib/client/connection.js:69:48)
[2021-06-22T09:39:06Z]       at Proxy.<anonymous> (/build/node_modules/playwright/lib/client/channelOwner.js:64:61)
[2021-06-22T09:39:06Z]       at /build/node_modules/playwright/lib/client/frame.js:100:65
[2021-06-22T09:39:06Z]       at Frame._wrapApiCall (/build/node_modules/playwright/lib/client/channelOwner.js:77:34)
[2021-06-22T09:39:06Z]       at Frame.goto (/build/node_modules/playwright/lib/client/frame.js:98:21)
[2021-06-22T09:39:06Z]       at /build/node_modules/playwright/lib/client/page.js:267:60
[2021-06-22T09:39:06Z]       at Page._attributeToPage (/build/node_modules/playwright/lib/client/page.js:202:20)
[2021-06-22T09:39:06Z]       at Page.goto (/build/node_modules/playwright/lib/client/page.js:267:21)
[2021-06-22T09:39:06Z]       at performLoginFlow (test_ui.ts:94:14)
[2021-06-22T09:39:06Z]       at Context.<anonymous> (test_ui.ts:208:5)
```

https://buildkite.com/opstrace/upgrade-tests/builds/839#4c6b8820-7920-4820-9c0d-9ecd4504f84c/7861-7950

Looks like Chromium driver running in docker doesn't like ipv6 in Linux and sometimes fails with this error.
  
https://bugs.chromium.org/p/chromium/issues/detail?id=974711#c4 
https://stackoverflow.com/questions/44678168/docker-and-chromium-neterr-network-changed

**Comment by sreis** [comment]
```
[2021-07-05T12:52:07Z]   1) test_ui_api
[2021-07-05T12:52:07Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-05T12:52:07Z]      page.goto: net::ERR_NETWORK_CHANGED at https://schedul-bk-2610-d40-g.opstrace.io
[2021-07-05T12:52:07Z] =========================== logs ===========================
[2021-07-05T12:52:07Z] navigating to "https://schedul-bk-2610-d40-g.opstrace.io", waiting until "load"
[2021-07-05T12:52:07Z] ============================================================
[2021-07-05T12:52:07Z] Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2610#51fd8b7e-c05c-42c1-983e-6b6147cb4f48/7274-7363

**Comment by sreis** [comment]
Closing in favor of #340
