### ISSUE TITLE
ci instability: getaddrinfo ENOTFOUND during test-remote, for system tenant Cortex API

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#835]
Mid way during test-remote, suddenly certain DNS names didn't resolve anymore:
```
[2021-06-03T20:50:03Z] 2021-06-03T20:50:03.396Z info: Waiting for cortex E2E alerting metric for tenant=system job=testalerts-rDf6g-job with nonzero value
[2021-06-03T20:50:03Z] 2021-06-03T20:50:03.396Z info: Cortex query parameter (object):

...

[2021-06-03T20:52:57Z] 2021-06-03T20:52:57.736Z info: Got alert count value: 0
[2021-06-03T20:52:58Z] 2021-06-03T20:52:58.737Z info: Cortex query parameter (object):
[2021-06-03T20:52:58Z] {
[2021-06-03T20:52:58Z]   "query": "e2ealerting_webhook_receiver_evaluations_total{job=\"testalerts-rDf6g-job\"}"
[2021-06-03T20:52:58Z] }
[2021-06-03T20:52:58Z] 2021-06-03T20:52:58.738Z info: Cortex query parameters (query string):
[2021-06-03T20:52:58Z] query=e2ealerting_webhook_receiver_evaluations_total%7Bjob%3D%22testalerts-rDf6g-job%22%7D
[2021-06-03T20:52:58Z] 2021-06-03T20:52:58.738Z info: Waiting for query to return a match, deadline in 30s
[2021-06-03T20:52:58Z] 2021-06-03T20:52:58.738Z info: read token from /tmp/opstrace-bk-2414-e9201e6-1-gcp/tenant-api-token-system
[2021-06-03T20:53:01Z] 2021-06-03T20:53:01.977Z info: waitForQueryResult() loop: http request failed: getaddrinfo ENOTFOUND cortex.system.schedul-bk-2414-e92-g.opstrace.io -- ignore, proceed with next iteration

...

[2021-06-03T20:53:23Z] 2021-06-03T20:53:23.563Z info: read token from /tmp/opstrace-bk-2414-e9201e6-1-gcp/tenant-api-token-system
[2021-06-03T20:53:26Z] 2021-06-03T20:53:26.650Z info: waitForQueryResult() loop: http request failed: getaddrinfo ENOTFOUND cortex.system.schedul-bk-2414-e92-g.opstrace.io -- ignore, proceed with next iteration
[2021-06-03T20:53:26Z] 2021-06-03T20:53:26.650Z info: read token from /tmp/opstrace-bk-2414-e9201e6-1-gcp/tenant-api-token-system
[2021-06-03T20:53:29Z] 2021-06-03T20:53:29.678Z info: waitForQueryResult() loop: http request failed: getaddrinfo ENOTFOUND cortex.system.schedul-bk-2414-e92-g.opstrace.io -- ignore, proceed with next iteration
[2021-06-03T20:53:29Z] 2021-06-03T20:53:29.678Z error: Reached 30s deadline, giving up
[2021-06-03T20:53:29Z]     1) End-to-end alerts for system tenant
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2414#26f72fcd-4a5f-4f11-96d8-ef0d35edb75d/3394-5884

and then also, in the same sessions:

```
[2021-06-03T20:54:56Z]   system metrics test suite
[2021-06-03T20:54:56Z] 2021-06-03T20:54:56.675Z info: suite setup
[2021-06-03T20:54:56Z] 2021-06-03T20:54:56.675Z info: globalTestSuiteSetupOnce()
[2021-06-03T20:54:56Z] 2021-06-03T20:54:56.676Z info: Cortex query parameter (object):
[2021-06-03T20:54:56Z] {
[2021-06-03T20:54:56Z]   "end": "1622757296",
[2021-06-03T20:54:56Z]   "query": "process_cpu_seconds_total{container=\"ingester\", namespace=\"cortex\"}",
[2021-06-03T20:54:56Z]   "start": "1622750096",
[2021-06-03T20:54:56Z]   "step": "1"
[2021-06-03T20:54:56Z] }
[2021-06-03T20:54:56Z] 2021-06-03T20:54:56.676Z info: Cortex query parameters (query string):
[2021-06-03T20:54:56Z] query=process_cpu_seconds_total%7Bcontainer%3D%22ingester%22%2C+namespace%3D%22cortex%22%7D&start=1622750096&end=1622757296&step=1

...


[2021-06-03T20:54:56Z] 2021-06-03T20:54:56.676Z info: Waiting for query to return a match, deadline in 30s
[2021-06-03T20:54:56Z] 2021-06-03T20:54:56.676Z info: read token from /tmp/opstrace-bk-2414-e9201e6-1-gcp/tenant-api-token-system
[2021-06-03T20:54:59Z] 2021-06-03T20:54:59.831Z info: waitForQueryResult() loop: http request failed: getaddrinfo ENOTFOUND cortex.system.schedul-bk-2414-e92-g.opstrace.io -- ignore, proceed with next iteration
[2021-06-03T20:54:59Z] 2021-06-03T20:54:59.831Z info: read token from /tmp/opstrace-bk-2414-e9201e6-1-gcp/tenant-api-token-system
...
[2021-06-03T20:55:24Z] 2021-06-03T20:55:24.808Z info: waitForQueryResult() loop: http request failed: getaddrinfo ENOTFOUND cortex.system.schedul-bk-2414-e92-g.opstrace.io -- ignore, proceed with next iteration
[2021-06-03T20:55:24Z] 2021-06-03T20:55:24.808Z info: read token from /tmp/opstrace-bk-2414-e9201e6-1-gcp/tenant-api-token-system
[2021-06-03T20:55:27Z] 2021-06-03T20:55:27.982Z info: waitForQueryResult() loop: http request failed: getaddrinfo ENOTFOUND cortex.system.schedul-bk-2414-e92-g.opstrace.io -- ignore, proceed with next iteration
[2021-06-03T20:55:27Z] 2021-06-03T20:55:27.982Z error: Reached 30s deadline, giving up
[2021-06-03T20:55:27Z]     2) check if container metrics exist
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2414#26f72fcd-4a5f-4f11-96d8-ef0d35edb75d/3394-7623

Affected platform for the log snippets above: GCP

**Comment by jgehrcke** [comment]
```
[2021-06-06T16:45:55Z]   20 passing (8m)
[2021-06-06T16:45:55Z]   4 pending
[2021-06-06T16:45:55Z]   2 failing
[2021-06-06T16:45:55Z]
[2021-06-06T16:45:55Z]   1) End-to-end alert tests
[2021-06-06T16:45:55Z]        End-to-end alerts for default tenant:
[2021-06-06T16:45:55Z]      Error: Expectation not fulfilled within 30 s
[2021-06-06T16:45:55Z]       at Object.waitForQueryResult (testutils/index.ts:955:9)
[2021-06-06T16:45:55Z]       at runMicrotasks (<anonymous>)
[2021-06-06T16:45:55Z]       at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2021-06-06T16:45:55Z]       at getE2EAlertCountMetric (test_alerts.ts:301:23)
[2021-06-06T16:45:55Z]       at testE2EAlertsForTenant (test_alerts.ts:381:19)
[2021-06-06T16:45:55Z]       at Context.<anonymous> (test_alerts.ts:422:5)
[2021-06-06T16:45:55Z] 
[2021-06-06T16:45:55Z]   2) DD API test suite
[2021-06-06T16:45:55Z]        dd_api_insert_single_ts_fragment:
[2021-06-06T16:45:55Z]      Error: Expectation not fulfilled within 30 s
[2021-06-06T16:45:55Z]       at Object.waitForQueryResult (testutils/index.ts:955:9)
[2021-06-06T16:45:55Z]       at runMicrotasks (<anonymous>)
[2021-06-06T16:45:55Z]       at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2021-06-06T16:45:55Z]       at Context.<anonymous> (test_dd.ts:297:25)
[2021-06-06T16:45:55Z] 
```

```
[2021-06-06T16:44:28Z] 2021-06-06T16:44:28.209Z info: read token from /tmp/opstrace-bk-2431-bb131b2-1-gcp/tenant-api-token-default
[2021-06-06T16:44:31Z] 2021-06-06T16:44:31.315Z info: waitForQueryResult() loop: http request failed: getaddrinfo ENOTFOUND cortex.default.schedul-bk-2431-bb1-g.opstrace.io -- ignore, proceed with next iteration
[2021-06-06T16:44:31Z] 2021-06-06T16:44:31.316Z error: Reached 30s deadline, giving up
[2021-06-06T16:44:31Z]     2) dd_api_insert_single_ts_fragment
```

and

```
[2021-06-06T16:40:16Z] 2021-06-06T16:40:16.282Z info: read token from /tmp/opstrace-bk-2431-bb131b2-1-gcp/tenant-api-token-default
[2021-06-06T16:40:19Z] 2021-06-06T16:40:19.400Z info: waitForQueryResult() loop: http request failed: getaddrinfo ENOTFOUND cortex.default.schedul-bk-2431-bb1-g.opstrace.io -- ignore, proceed with next iteration
[2021-06-06T16:40:19Z] 2021-06-06T16:40:19.400Z error: Reached 30s deadline, giving up
[2021-06-06T16:40:19Z]     1) End-to-end alerts for default tenant
```

**Comment by jgehrcke** [comment]
now tracked in https://github.com/opstrace/opstrace/issues/834.
