### ISSUE TITLE
installer: aws: MalformedPolicyDocument during createRole() not handled properly

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#88]
Should not consume a high-level retry attempt:
```
[2020-12-02T21:57:59Z] 2020-12-02T21:57:59.729Z debug: aws sdk: [AWS iam 400 0.332s 0 retries] createRole({
[2020-12-02T21:57:59Z]   AssumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"AWS":"arn:aws:iam::959325414060:role/bk-1294-f61-a-eks-nodes"},"Action":"sts:AssumeRole"}]}',
[2020-12-02T21:57:59Z]   RoleName: 'bk-1294-f61-a-cert-manager'
[2020-12-02T21:57:59Z] })
[2020-12-02T21:57:59Z] 2020-12-02T21:57:59.734Z error: error during cluster creation (attempt 1):
[2020-12-02T21:57:59Z] MalformedPolicyDocument: Invalid principal in policy: "AWS":"arn:aws:iam::959325414060:role/bk-1294-f61-a-eks-nodes"
[2020-12-02T21:57:59Z]     at Request.extractError (/snapshot/build/node_modules/aws-sdk/lib/protocol/query.js:50:29)
[2020-12-02T21:57:59Z]     at Request.callListeners (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
[2020-12-02T21:57:59Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[2020-12-02T21:57:59Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/request.js:688:14)
[2020-12-02T21:57:59Z]     at Request.transition (/snapshot/build/node_modules/aws-sdk/lib/request.js:22:10)
[2020-12-02T21:57:59Z]     at AcceptorStateMachine.runTo (/snapshot/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
[2020-12-02T21:57:59Z]     at /snapshot/build/node_modules/aws-sdk/lib/state_machine.js:26:10
[2020-12-02T21:57:59Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:38:9)
[2020-12-02T21:57:59Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:690:12)
[2020-12-02T21:57:59Z]     at Request.callListeners (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
[2020-12-02T21:57:59Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[2020-12-02T21:57:59Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/request.js:688:14)
[2020-12-02T21:57:59Z]     at Request.transition (/snapshot/build/node_modules/aws-sdk/lib/request.js:22:10)
[2020-12-02T21:57:59Z]     at AcceptorStateMachine.runTo (/snapshot/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
[2020-12-02T21:57:59Z]     at /snapshot/build/node_modules/aws-sdk/lib/state_machine.js:26:10
[2020-12-02T21:57:59Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:38:9)
[2020-12-02T21:57:59Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:690:12)
[2020-12-02T21:57:59Z]     at Request.callListeners (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
[2020-12-02T21:57:59Z]     at callNextListener (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
[2020-12-02T21:57:59Z]     at IncomingMessage.onEnd (/snapshot/build/node_modules/aws-sdk/lib/event_listeners.js:313:13)
[2020-12-02T21:57:59Z]     at IncomingMessage.emit (events.js:327:22)
[2020-12-02T21:57:59Z]     at IncomingMessage.EventEmitter.emit (domain.js:485:12)
[2020-12-02T21:57:59Z]     at endReadableNT (_stream_readable.js:1224:12)
[2020-12-02T21:57:59Z]     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[2020-12-02T21:57:59Z]   code: 'MalformedPolicyDocument',
[2020-12-02T21:57:59Z]   time: 2020-12-02T21:57:59.729Z,
[2020-12-02T21:57:59Z]   requestId: '0487635b-a75f-4168-8a32-ccb65cae157b',
[2020-12-02T21:57:59Z]   statusCode: 400,
[2020-12-02T21:57:59Z]   retryable: false,
[2020-12-02T21:57:59Z]   retryDelay: 1000
[2020-12-02T21:57:59Z] }
[2020-12-02T21:57:59Z] 2020-12-02T21:57:59.734Z error: JSON representation of err: {
[2020-12-02T21:57:59Z]   "message": "Invalid principal in policy: \"AWS\":\"arn:aws:iam::959325414060:role/bk-1294-f61-a-eks-nodes\"",
[2020-12-02T21:57:59Z]   "code": "MalformedPolicyDocument",
[2020-12-02T21:57:59Z]   "time": "2020-12-02T21:57:59.729Z",
[2020-12-02T21:57:59Z]   "requestId": "0487635b-a75f-4168-8a32-ccb65cae157b",
[2020-12-02T21:57:59Z]   "statusCode": 400,
[2020-12-02T21:57:59Z]   "retryable": false,
[2020-12-02T21:57:59Z]   "retryDelay": 1000
[2020-12-02T21:57:59Z] }
```

Let's move the `createRole()` call under the [AWSResource](https://github.com/opstrace/opstrace/blob/f610692c86d0da1d16165c89c22d814594940523/lib/aws/src/resource.ts#L25) control.

Well. This resolved itself through retrying, i.e. the underlying issue was eventual consistency within AWS.

**Comment by triclambert** [comment]
```
[2021-01-19T16:22:59Z] 2021-01-19T16:22:59.705Z info: Ensuring bk-1588-092-a-cert-manager role exists
[2021-01-19T16:23:00Z] 2021-01-19T16:23:00.131Z debug: aws sdk: [AWS iam 200 0.425s 0 retries] listRoles({})
[2021-01-19T16:23:00Z] 2021-01-19T16:23:00.437Z debug: aws-sdk-js request failed (attempt 0): MalformedPolicyDocument: Invalid principal in policy: "AWS":"arn:aws:iam::959325414060:role/bk-1588-092-a-eks-nodes" (retryable, according to sdk: false)
[2021-01-19T16:23:00Z] 2021-01-19T16:23:00.438Z debug: aws sdk: [AWS iam 400 0.306s 0 retries] createRole({
[2021-01-19T16:23:00Z]   AssumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"AWS":"arn:aws:iam::959325414060:role/bk-1588-092-a-eks-nodes"},"Action":"sts:AssumeRole"}]}',
[2021-01-19T16:23:00Z]   RoleName: 'bk-1588-092-a-cert-manager'
[2021-01-19T16:23:00Z] })
[2021-01-19T16:23:00Z] 2021-01-19T16:23:00.439Z error: error during cluster creation (attempt 3):
[2021-01-19T16:23:00Z] MalformedPolicyDocument: Invalid principal in policy: "AWS":"arn:aws:iam::959325414060:role/bk-1588-092-a-eks-nodes"
[2021-01-19T16:23:00Z]     at Request.extractError (/snapshot/build/node_modules/aws-sdk/lib/protocol/query.js:50:29)
[2021-01-19T16:23:00Z]     at Request.callListeners (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
[2021-01-19T16:23:00Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[2021-01-19T16:23:00Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/request.js:688:14)
[2021-01-19T16:23:00Z]     at Request.transition (/snapshot/build/node_modules/aws-sdk/lib/request.js:22:10)
[2021-01-19T16:23:00Z]     at AcceptorStateMachine.runTo (/snapshot/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
[2021-01-19T16:23:00Z]     at /snapshot/build/node_modules/aws-sdk/lib/state_machine.js:26:10
[2021-01-19T16:23:00Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:38:9)
[2021-01-19T16:23:00Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:690:12)
[2021-01-19T16:23:00Z]     at Request.callListeners (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
[2021-01-19T16:23:00Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[2021-01-19T16:23:00Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/request.js:688:14)
[2021-01-19T16:23:00Z]     at Request.transition (/snapshot/build/node_modules/aws-sdk/lib/request.js:22:10)
[2021-01-19T16:23:00Z]     at AcceptorStateMachine.runTo (/snapshot/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
[2021-01-19T16:23:00Z]     at /snapshot/build/node_modules/aws-sdk/lib/state_machine.js:26:10
[2021-01-19T16:23:00Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:38:9)
[2021-01-19T16:23:00Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:690:12)
[2021-01-19T16:23:00Z]     at Request.callListeners (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
[2021-01-19T16:23:00Z]     at callNextListener (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
[2021-01-19T16:23:00Z]     at IncomingMessage.onEnd (/snapshot/build/node_modules/aws-sdk/lib/event_listeners.js:313:13)
[2021-01-19T16:23:00Z]     at IncomingMessage.emit (events.js:327:22)
[2021-01-19T16:23:00Z]     at IncomingMessage.EventEmitter.emit (domain.js:485:12)
[2021-01-19T16:23:00Z]     at endReadableNT (_stream_readable.js:1224:12)
[2021-01-19T16:23:00Z]     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[2021-01-19T16:23:00Z]   code: 'MalformedPolicyDocument',
[2021-01-19T16:23:00Z]   time: 2021-01-19T16:23:00.437Z,
[2021-01-19T16:23:00Z]   requestId: '96f573d8-fac5-4d5c-b366-aaeab5cd9166',
[2021-01-19T16:23:00Z]   statusCode: 400,
[2021-01-19T16:23:00Z]   retryable: false,
[2021-01-19T16:23:00Z]   retryDelay: 1000
[2021-01-19T16:23:00Z] }
[2021-01-19T16:23:00Z] 2021-01-19T16:23:00.439Z debug: `err?.stack`: MalformedPolicyDocument: Invalid principal in policy: "AWS":"arn:aws:iam::959325414060:role/bk-1588-092-a-eks-nodes"
[2021-01-19T16:23:00Z]     at Request.extractError (/snapshot/build/node_modules/aws-sdk/lib/protocol/query.js:50:29)
[2021-01-19T16:23:00Z]     at Request.callListeners (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
[2021-01-19T16:23:00Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[2021-01-19T16:23:00Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/request.js:688:14)
[2021-01-19T16:23:00Z]     at Request.transition (/snapshot/build/node_modules/aws-sdk/lib/request.js:22:10)
[2021-01-19T16:23:00Z]     at AcceptorStateMachine.runTo (/snapshot/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
[2021-01-19T16:23:00Z]     at /snapshot/build/node_modules/aws-sdk/lib/state_machine.js:26:10
[2021-01-19T16:23:00Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:38:9)
[2021-01-19T16:23:00Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:690:12)
[2021-01-19T16:23:00Z]     at Request.callListeners (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
[2021-01-19T16:23:00Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[2021-01-19T16:23:00Z]     at Request.emit (/snapshot/build/node_modules/aws-sdk/lib/request.js:688:14)
[2021-01-19T16:23:00Z]     at Request.transition (/snapshot/build/node_modules/aws-sdk/lib/request.js:22:10)
[2021-01-19T16:23:00Z]     at AcceptorStateMachine.runTo (/snapshot/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
[2021-01-19T16:23:00Z]     at /snapshot/build/node_modules/aws-sdk/lib/state_machine.js:26:10
[2021-01-19T16:23:00Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:38:9)
[2021-01-19T16:23:00Z]     at Request.<anonymous> (/snapshot/build/node_modules/aws-sdk/lib/request.js:690:12)
[2021-01-19T16:23:00Z]     at Request.callListeners (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
[2021-01-19T16:23:00Z]     at callNextListener (/snapshot/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
[2021-01-19T16:23:00Z]     at IncomingMessage.onEnd (/snapshot/build/node_modules/aws-sdk/lib/event_listeners.js:313:13)
[2021-01-19T16:23:00Z]     at IncomingMessage.emit (events.js:327:22)
[2021-01-19T16:23:00Z]     at IncomingMessage.EventEmitter.emit (domain.js:485:12)
[2021-01-19T16:23:00Z]     at endReadableNT (_stream_readable.js:1224:12)
[2021-01-19T16:23:00Z]     at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-01-19T16:23:00Z] 2021-01-19T16:23:00.439Z error: JSON representation of err: {
[2021-01-19T16:23:00Z]   "message": "Invalid principal in policy: \"AWS\":\"arn:aws:iam::959325414060:role/bk-1588-092-a-eks-nodes\"",
[2021-01-19T16:23:00Z]   "code": "MalformedPolicyDocument",
[2021-01-19T16:23:00Z]   "time": "2021-01-19T16:23:00.437Z",
[2021-01-19T16:23:00Z]   "requestId": "96f573d8-fac5-4d5c-b366-aaeab5cd9166",
[2021-01-19T16:23:00Z]   "statusCode": 400,
[2021-01-19T16:23:00Z]   "retryable": false,
[2021-01-19T16:23:00Z]   "retryDelay": 1000
[2021-01-19T16:23:00Z] }
[2021-01-19T16:23:00Z] 2021-01-19T16:23:00.440Z error: 3 attempt(s) failed. Stop retrying. Exit.
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/1588#981d52c6-beaa-4ae4-bf24-9fab17d23279/229-3451

**Comment by jgehrcke** [comment]
@triclambert thanks for linking that here. Interestingly, in that scenario that you linked to that error did not go away with the next retry attempt. I would still assume that this was a temporary hiccup within AWS.

`Invalid principal in policy: "AWS":"arn:aws:iam::959325414060:role/bk-1588-092-a-eks-nodes"` is unexpected: the account ID 959325414060 is valid -- otherwise many other things would have failed. I.e. the principal is known and valid.

The timestamps:

```
[2021-01-19T16:22:23Z] MalformedPolicyDocument:
[2021-01-19T16:22:41Z] MalformedPolicyDocument:
[2021-01-19T16:23:00Z] MalformedPolicyDocument: 
```

This is only O(1 min), it's likely that retrying more/longer would address this. That is, I still think the solution is

> Let's move the createRole() call under the AWSResource control.

See https://github.com/opstrace/opstrace/issues/272
