### ISSUE TITLE
test_ui_api: "before all" hook failed `waiting for selector "css=button" to be visible`

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#917]
**Describe the bug**

```
[2021-06-21T05:05:05Z]   1) test_ui_api
[2021-06-21T05:05:05Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-06-21T05:05:05Z]      page.waitForSelector: Timeout 30000ms exceeded.
[2021-06-21T05:05:05Z] =========================== logs ===========================
[2021-06-21T05:05:05Z] waiting for selector "css=button" to be visible
[2021-06-21T05:05:05Z] ============================================================
[2021-06-21T05:05:05Z] Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

**Comment by jgehrcke** [comment]
another one here: https://github.com/opstrace/opstrace/pull/932#issuecomment-868375413

**Comment by jgehrcke** [comment]
This means that the `Login` button does not pop up. 
https://github.com/opstrace/opstrace/blob/bc7a44f4e232a6e914fbdb577e83587cbe2059ec/test/test-remote/test_ui.ts#L100

**Comment by jgehrcke** [comment]
```
[2021-07-04T22:42:52Z]   1) tests/authentication.spec.ts:25:3 › [Chromium] after auth0 authentication user should see homepage 
[2021-07-04T22:42:52Z]
[2021-07-04T22:42:52Z]     page.waitForSelector: Timeout 30000ms exceeded.
[2021-07-04T22:42:52Z]     =========================== logs ===========================
[2021-07-04T22:42:52Z]     waiting for selector "css=button" to be visible
[2021-07-04T22:42:52Z]     ============================================================
[2021-07-04T22:42:52Z]     Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2606#d257fdb0-629d-4107-934b-86aa627ac111/8751-8777

**Comment by sreis** [comment]
https://buildkite.com/opstrace/upgrade-tests/builds/1040#d54ebf68-1c9f-4d1c-9982-b6904e930b67/3237-3257

```


[2021-07-20T06:31:10Z]   1) tests/7l3OW_tenant.spec.ts:35:3 › [Chromium] after auth0 authentication user can create a new Tenant
--
  | [2021-07-20T06:31:10Z]
  | [2021-07-20T06:31:10Z]     Pending operations:
  | [2021-07-20T06:31:10Z]       - page.waitForSelector at utils/authentication.ts:24:14
  | [2021-07-20T06:31:10Z]
  | [2021-07-20T06:31:10Z]     page.waitForSelector: Protocol error (Runtime.callFunctionOn): Target closed.
  | [2021-07-20T06:31:10Z]     =========================== logs ===========================
  | [2021-07-20T06:31:10Z]     waiting for selector "css=button" to be visible
  | [2021-07-20T06:31:10Z]     ============================================================
  | [2021-07-20T06:31:10Z]     Note: use DEBUG=pw:api environment variable to capture Playwright logs.


```

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2692#94af77ac-516e-4f7c-bb12-aecb5be99dd2/2972-3095

```
[2021-07-19T05:14:24Z]   1) test_ui_api
[2021-07-19T05:14:24Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-19T05:14:24Z]      page.waitForSelector: Timeout 60000ms exceeded.
[2021-07-19T05:14:24Z] =========================== logs ===========================
[2021-07-19T05:14:24Z] waiting for selector "css=button" to be visible
[2021-07-19T05:14:24Z] ============================================================
[2021-07-19T05:14:24Z] Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

**Comment by jgehrcke** [comment]
I think we need to distinguish

`page.waitForSelector: Timeout 30000ms exceeded.` from `page.waitForSelector: Protocol error (Runtime.callFunctionOn): Target closed.`

**Comment by sreis** [comment]
```
[2021-07-22T05:38:45Z]   1) test_ui_api
[2021-07-22T05:38:45Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-22T05:38:45Z]      page.waitForSelector: Timeout 60000ms exceeded.
[2021-07-22T05:38:45Z] =========================== logs ===========================
[2021-07-22T05:38:45Z] waiting for selector "css=button" to be visible
[2021-07-22T05:38:45Z] ============================================================
[2021-07-22T05:38:45Z]       at performLoginFlow (test_ui_api.ts:102:16)
[2021-07-22T05:38:45Z]       at runNextTicks (node:internal/process/task_queues:61:5)
[2021-07-22T05:38:45Z]       at processImmediate (node:internal/timers:437:9)
[2021-07-22T05:38:45Z]       at Context.<anonymous> (test_ui_api.ts:222:5)
```

https://buildkite.com/opstrace/upgrade-tests/builds/1052#61a66463-91c1-4af8-9019-5d80f1466829/8456-8569

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2717#d1063c88-2277-4f1c-9647-b8c4948739d8/9321-9341

```
[2021-07-23T09:43:09Z]   1) tests/MZIO7_tenant.spec.ts:50:3 › [Chromium] after auth0 authentication user can delete a Tenant 
[2021-07-23T09:43:09Z]
[2021-07-23T09:43:09Z]     Pending operations:
[2021-07-23T09:43:09Z]       - page.waitForSelector at utils/authentication.ts:24:14
[2021-07-23T09:43:09Z]
[2021-07-23T09:43:09Z]     page.waitForSelector: Protocol error (Runtime.callFunctionOn): Target closed.
[2021-07-23T09:43:09Z]     =========================== logs ===========================
[2021-07-23T09:43:09Z]     waiting for selector "css=button" to be visible
[2021-07-23T09:43:09Z]     ============================================================
[2021-07-23T09:43:09Z]     Note: use DEBUG=pw:api environment variable to capture Playwright log
```

**Comment by nickbp** [comment]
May have been fixed via the above test-remote change in July, no repros since
