### ISSUE TITLE
ci instability: during `page.click()`  `The page has been closed`

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#959]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2572#032b5116-b7bf-44c1-92cc-3f7d681a6a28/9320-9341
```
[2021-06-29T08:58:35Z] Running 2 tests using 1 worker
[2021-06-29T09:01:07Z] ·T
[2021-06-29T09:01:07Z]
[2021-06-29T09:01:07Z]   1) tests/everywhere.spec.ts:25:8 › [WebKit] after auth0 authentication user should click around the entire site 
[2021-06-29T09:01:07Z]
[2021-06-29T09:01:07Z]     Timeout of 120000ms exceeded.
[2021-06-29T09:01:07Z]
[2021-06-29T09:01:07Z]     Pending operations:
[2021-06-29T09:01:07Z]       - page.click at tests/everywhere.spec.ts:71:16
[2021-06-29T09:01:07Z]
[2021-06-29T09:01:07Z]     page.click: Protocol error (Runtime.callFunctionOn): The page has been closed.
[2021-06-29T09:01:07Z]     =========================== logs ===========================
[2021-06-29T09:01:07Z]     waiting for selector "[data-test='sidebar/clusterAdmin/Users']"
[2021-06-29T09:01:07Z]     ============================================================
[2021-06-29T09:01:07Z]     Note: use DEBUG=pw:api environment variable to capture Playwright logs.
[2021-06-29T09:01:07Z]
[2021-06-29T09:01:07Z]       69 |
[2021-06-29T09:01:07Z]       70 |     await page.hover("[data-test='sidebar/clusterAdmin/Users']");
[2021-06-29T09:01:07Z]     > 71 |     await page.click("[data-test='sidebar/clusterAdmin/Users']");
[2021-06-29T09:01:07Z]          |                ^
[2021-06-29T09:01:07Z]       72 |     expect(
[2021-06-29T09:01:07Z]       73 |       await page.isVisible(`[data-test='userList/${user.email}']`)
[2021-06-29T09:01:07Z]       74 |     ).toBeTruthy();
[2021-06-29T09:01:07Z]
[2021-06-29T09:01:07Z]     Error
[2021-06-29T09:01:07Z]         at Object.captureStackTrace (/build/test/browser/node_modules/@playwright/test/lib/utils/stackTrace.js:51:19)
[2021-06-29T09:01:07Z]         at Connection.sendMessageToServer (/build/test/browser/node_modules/@playwright/test/lib/client/connection.js:73:48)
[2021-06-29T09:01:07Z]         at Proxy.<anonymous> (/build/test/browser/node_modules/@playwright/test/lib/client/channelOwner.js:64:61)
[2021-06-29T09:01:07Z]         at /build/test/browser/node_modules/@playwright/test/lib/client/frame.js:270:34
[2021-06-29T09:01:07Z]         at Frame._wrapApiCall (/build/test/browser/node_modules/@playwright/test/lib/client/channelOwner.js:77:34)
[2021-06-29T09:01:07Z]         at Frame.click (/build/test/browser/node_modules/@playwright/test/lib/client/frame.js:269:21)
[2021-06-29T09:01:07Z]         at /build/test/browser/node_modules/@playwright/test/lib/client/page.js:422:60
[2021-06-29T09:01:07Z]         at Page._attributeToPage (/build/test/browser/node_modules/@playwright/test/lib/client/page.js:202:20)
[2021-06-29T09:01:07Z]         at Page.click (/build/test/browser/node_modules/@playwright/test/lib/client/page.js:422:21)
[2021-06-29T09:01:07Z]         at /build/test/browser/tests/everywhere.spec.ts:71:16
[2021-06-29T09:01:07Z]         at WorkerRunner._runTestWithBeforeHooks (/build/test/browser/node_modules/@playwright/test/lib/test/workerRunner.js:290:13)
[2021-06-29T09:01:07Z]
[2021-06-29T09:01:07Z]   Slow test: everywhere.spec.ts (3m)
[2021-06-29T09:01:07Z]
[2021-06-29T09:01:07Z]   1 failed
[2021-06-29T09:01:07Z]     tests/everywhere.spec.ts:25:8 › [WebKit] after auth0 authentication user should click around the entire site 
[2021-06-29T09:01:07Z]   1 passed (3m)
error Command failed with exit code 1.
```

`hover()` worked, `click()` failed with `page.click: Protocol error (Runtime.callFunctionOn): The page has been closed.` -- huh. @terrcin can you have a look?

**Comment by jgehrcke** [comment]
another one here: https://buildkite.com/opstrace/scheduled-main-builds/builds/2572#2c180adc-d866-486e-893f-83b46e10e9b7/2746-2792

Is really an instability or broken on `main`?

**Comment by jgehrcke** [comment]
another one: https://buildkite.com/opstrace/upgrade-tests/builds/894#819a205d-379c-4496-acdb-84bc6523a346/10562-10586

**Comment by terrcin** [comment]
Frustratingly this was passing in the PR which is why I merged the new long running test. I've got a [PR](https://github.com/opstrace/opstrace/pull/961) that marks that test as `slow` which tripples it's allowable run time. The problem here is the Playwright has a time limit for each test run then fails the test if it exceeds this - but doesn't obviously say that's the reason for the timeout. I'd previously increased the limit and that seemed to work. Obviously now.

**Comment by terrcin** [comment]
Hmmm, I may be wrong about the reason. Marking the test as slow was my gut reaction to that test failing - CI is slow, get a PR up quickly so I can hurry up and wait for the results - type thing. Now looking at the linked failures above it's not actually a timeout, but rather an actual error, here is a screenshot:

![test-failed-1](https://user-images.githubusercontent.com/17045/123859627-fd113b80-d978-11eb-9da7-c1922504e07b.png)

This is happening when trying to view the list of users for the cluster on Webkit. It's not happening all the time. I've also not seen it in the PR, then it was only timeout problems hence my initial thought as to the problem.

**Comment by terrcin** [comment]
BTW the key part of the output is `Timeout of 120000ms exceeded.` the `page` error is caused I believe by playwright yanking the test once it exceeds the max run time which I've set to 120_000ms.

**Comment by jgehrcke** [comment]
this was another one: https://buildkite.com/opstrace/scheduled-main-builds/builds/2575#7877cf01-8442-4663-b1d9-ead79722d7f6/9374-9398

> Frustratingly this was passing in the PR which is why I merged the new long running test.

Yes. I really can't stress this often enough; in a distributed system there is a wide distribution of the different involved timings. Each repetition yields a _different_ outcome. The ensemble of outcomes provides an idea of the involved distribution(s). Looking at a small number of test executions is _undersampling_ and of course that means nothing but simply a lack of knowledge :-). In other words, what happened here is perfectly expected. We use CI _after merge_ towards acquiring knowledge, and that's precisely why we do the bookkeeping dance :).
