### ISSUE TITLE
ci instability: timeout during `waiting for selector "[data-test=getting-started]" to be visible`

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#990]
```
[2021-07-05T17:18:44Z] Running 20 tests using 1 worker
[2021-07-05T17:21:09Z] °F·····°···°°······°
[2021-07-05T17:21:09Z]
[2021-07-05T17:21:09Z]   1) tests/authentication.spec.ts:25:3 › [Chromium] after auth0 authentication user should see homepage 
[2021-07-05T17:21:09Z]
[2021-07-05T17:21:09Z]     page.waitForSelector: Timeout 30000ms exceeded.
[2021-07-05T17:21:09Z]     =========================== logs ===========================
[2021-07-05T17:21:09Z]     waiting for selector "[data-test=getting-started]" to be visible
[2021-07-05T17:21:09Z]     ============================================================
[2021-07-05T17:21:09Z]     Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```
https://buildkite.com/opstrace/prs/builds/4943#fe335df1-340f-4278-bd33-6019e7292dc0/1661-1706

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2613#3b418eca-bf23-4850-9404-b14faf91848d/1435-1456

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2625#f501a6a2-a1a4-45d2-9f9a-ca60e8088d94/1886-1910

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2636#22967163-3d4d-41ed-bff6-42c7050065bb/7206-7382

```
[2021-07-09T20:57:38Z]   1) test_ui_api
[2021-07-09T20:57:38Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-09T20:57:38Z]      page.waitForSelector: Timeout 30000ms exceeded.
[2021-07-09T20:57:38Z] =========================== logs ===========================
[2021-07-09T20:57:38Z] waiting for selector "text=Getting Started" to be visible
```

**Comment by sreis** [comment]
https://buildkite.com/opstrace/upgrade-tests/builds/978#2572a3c0-4f0d-4b99-8202-a27a0773b198/7550-7724

**Comment by jgehrcke** [comment]
```
[2021-07-15T17:39:24Z] [31m  1) tests/1q8wa_authentication.spec.ts:31:3 › [Chromium] after auth0 authentication user should see own email in user list [39m
[2021-07-15T17:39:24Z] 
[2021-07-15T17:39:24Z]     Pending operations:
[2021-07-15T17:39:24Z]       - page.waitForSelector at utils/authentication.ts:38:14
[2021-07-15T17:39:24Z] 
[2021-07-15T17:39:24Z]     page.waitForSelector: Protocol error (Runtime.callFunctionOn): Target closed.
[2021-07-15T17:39:24Z]     =========================== logs ===========================
[2021-07-15T17:39:24Z]     waiting for selector "[data-test=getting-started]" to be visible
[2021-07-15T17:39:24Z]     ============================================================
[2021-07-15T17:39:24Z]     Note: use DEBUG=pw:api environment variable to capture Playwright logs.
[2021-07-15T17:39:24Z] 
[2021-07-15T17:39:24Z]     [0m [90m 1 |[39m [90m/**[39m[0m
[2021-07-15T17:39:24Z]     [0m [90m 2 |[39m [90m * Copyright 2021 Opstrace, Inc.[39m[0m
[2021-07-15T17:39:24Z]     [0m [90m 3 |[39m [90m *[39m[0m
[2021-07-15T17:39:24Z] 
```
In `main-test-aws` in https://buildkite.com/opstrace/prs/builds/5089.

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2706#4a6ee998-bf68-44d6-b53a-87d96ceb1df5/6862-7037

```
[2021-07-21T12:50:53Z]   1) test_ui_api
[2021-07-21T12:50:53Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-21T12:50:53Z]      page.waitForSelector: Timeout 60000ms exceeded.
[2021-07-21T12:50:53Z] =========================== logs ===========================
[2021-07-21T12:50:53Z] waiting for selector "text=Getting Started" to be visible
[2021-07-21T12:50:53Z] ============================================================
[2021-07-21T12:50:53Z] Note: use DEBUG=pw:api environment variable to capture Playwright logs.
[2021-07-21T12:50:53Z]   Error: 
[2021-07-21T12:50:53Z]       at Object.captureStackTrace (/build/node_modules/playwright/lib/utils/stackTrace.js:51:19)
[2021-07-21T12:50:53Z]       at Connection.sendMessageToServer (/build/node_modules/playwright/lib/client/connection.js:73:48)
[2021-07-21T12:50:53Z]       at Proxy.<anonymous> (/build/node_modules/playwright/lib/client/channelOwner.js:64:61)
[2021-07-21T12:50:53Z]       at /build/node_modules/playwright/lib/client/frame.js:193:42
[2021-07-21T12:50:53Z]       at Frame._wrapApiCall (/build/node_modules/playwright/lib/client/channelOwner.js:77:34)
[2021-07-21T12:50:53Z]       at Frame.waitForSelector (/build/node_modules/playwright/lib/client/frame.js:188:21)
[2021-07-21T12:50:53Z]       at /build/node_modules/playwright/lib/client/page.js:212:60
[2021-07-21T12:50:53Z]       at Page._attributeToPage (/build/node_modules/playwright/lib/client/page.js:202:20)
[2021-07-21T12:50:53Z]       at Page.waitForSelector (/build/node_modules/playwright/lib/client/page.js:212:21)
[2021-07-21T12:50:53Z]       at performLoginFlow (test_ui_api.ts:138:14)
[2021-07-21T12:50:53Z]       at Context.<anonymous> (test_ui_api.ts:222:5)
```

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2707#e79d34c8-4f13-4a9e-ae86-1741e03907cd/7826-7997
```
[2021-07-21T16:47:58Z]   1) test_ui_api
[2021-07-21T16:47:58Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-21T16:47:58Z]      page.waitForSelector: Timeout 60000ms exceeded.
[2021-07-21T16:47:58Z] =========================== logs ===========================
[2021-07-21T16:47:58Z] waiting for selector "text=Getting Started" to be visible
[2021-07-21T16:47:58Z] ============================================================
[2021-07-21T16:47:58Z] Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

**Comment by MatApple** [comment]
@terrcin looks like this is occurring with high frequency

**Comment by sreis** [comment]
https://buildkite.com/opstrace/upgrade-tests/builds/1056#12f2c82c-747c-476d-9bcd-aea7bc337933

```
[2021-07-22T18:42:09Z]   1) tests/rKrl2_tenant.spec.ts:126:5 › [Chromium] after auth0 authentication validation of tenant name single character names are NOT allowed 
[2021-07-22T18:42:09Z]
[2021-07-22T18:42:09Z]     Pending operations:
[2021-07-22T18:42:09Z]       - page.waitForSelector at utils/authentication.ts:38:14
[2021-07-22T18:42:09Z]
[2021-07-22T18:42:09Z]     page.waitForSelector: Protocol error (Runtime.callFunctionOn): Target closed.
[2021-07-22T18:42:09Z]     =========================== logs ===========================
[2021-07-22T18:42:09Z]     waiting for selector "[data-test=getting-started]" to be visible
[2021-07-22T18:42:09Z]     ============================================================
[2021-07-22T18:42:09Z]     Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

**Comment by sreis** [comment]
```
[2021-07-22T18:24:46Z]   1) tests/rKrl2_tenant.spec.ts:77:5 › [iPhone-11] after auth0 authentication validation of tenant name valid alphanumeric lowercase name IS allowed 
[2021-07-22T18:24:46Z]
[2021-07-22T18:24:46Z]     Pending operations:
[2021-07-22T18:24:46Z]       - page.waitForSelector at utils/authentication.ts:38:14
[2021-07-22T18:24:46Z]
[2021-07-22T18:24:46Z]     page.waitForSelector: Protocol error (Runtime.callFunctionOn): The page has been closed.
[2021-07-22T18:24:46Z]     =========================== logs ===========================
[2021-07-22T18:24:46Z]     waiting for selector "[data-test=getting-started]" to be visible
[2021-07-22T18:24:46Z]     ============================================================
[2021-07-22T18:24:46Z]     Note: use DEBUG=pw:api environment variable to capture Playwright logs.
[2021-07-22T18:24:46Z]
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2713#712f6a4b-4225-4a22-8115-a5a1bcce282f/3596-3616

**Comment by jgehrcke** [comment]
```
[2021-07-23T11:07:29Z] Running 90 tests using 1 worker
[2021-07-23T11:40:56Z] °°············×··±···············°°······×··F°·······°··°···········×··F°···×°±·
[2021-07-23T11:44:37Z] ············°
[2021-07-23T11:44:37Z]
[2021-07-23T11:44:37Z]   1) tests/MZIO7_tenant.spec.ts:131:5 › [WebKit] after auth0 authentication validation of tenant name spaces are NOT allowed 
[2021-07-23T11:44:37Z]
[2021-07-23T11:44:37Z]     Pending operations:
[2021-07-23T11:44:37Z]       - page.waitForSelector at utils/authentication.ts:38:14
[2021-07-23T11:44:37Z]
[2021-07-23T11:44:37Z]     page.waitForSelector: Protocol error (Runtime.callFunctionOn): The page has been closed.
[2021-07-23T11:44:37Z]     =========================== logs ===========================
[2021-07-23T11:44:37Z]     waiting for selector "[data-test=getting-started]" to be visible
[2021-07-23T11:44:37Z]     ============================================================
[2021-07-23T11:44:37Z]     Note: use DEBUG=pw:api environment variable to capture Playwright logs.
[2021-07-23T11:44:37Z]
```
https://buildkite.com/opstrace/prs/builds/5140#885142d3-2d6b-44c5-904b-523737318a77/8189-8212

**Comment by jgehrcke** [comment]
```
[2021-07-26T06:30:13Z] [31m  1) tests/qT4kM_tenant.spec.ts:146:5 › [WebKit] after auth0 authentication validation of tenant name colons are NOT allowed [39m
[2021-07-26T06:30:13Z] 
[2021-07-26T06:30:13Z]     Pending operations:
[2021-07-26T06:30:13Z]       - page.waitForSelector at utils/authentication.ts:38:14
[2021-07-26T06:30:13Z] 
[2021-07-26T06:30:13Z]     page.waitForSelector: Protocol error (Runtime.callFunctionOn): The page has been closed.
[2021-07-26T06:30:13Z]     =========================== logs ===========================
[2021-07-26T06:30:13Z]     waiting for selector "[data-test=getting-started]" to be visible
[2021-07-26T06:30:13Z]     ============================================================
```

**Comment by jgehrcke** [comment]
```
[2021-07-26T06:41:37Z] [31m  1) tests/qT4kM_tenant.spec.ts:168:5 › [iPhone-11] after auth0 authentication validation of tenant name duplicate names are NOT allowed [39m
[2021-07-26T06:41:37Z] 
[2021-07-26T06:41:37Z]     Pending operations:
[2021-07-26T06:41:37Z]       - page.waitForSelector at utils/authentication.ts:38:14
[2021-07-26T06:41:37Z] 
[2021-07-26T06:41:37Z]     page.waitForSelector: Protocol error (Runtime.callFunctionOn): The page has been closed.
[2021-07-26T06:41:37Z]     =========================== logs ===========================
[2021-07-26T06:41:37Z]     waiting for selector "[data-test=getting-started]" to be visible
[2021-07-26T06:41:37Z]     ============================================================
[2021-07-26T06:41:37Z]     Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```
upgrade test on https://buildkite.com/opstrace/scheduled-main-builds/builds/2734

**Comment by sreis** [comment]
```
[2021-07-27T04:52:05Z]   1) test_ui_api
[2021-07-27T04:52:05Z]        "before all" hook for "test_grafana_datasource_proxy_loki_get_labels":
[2021-07-27T04:52:05Z]      page.waitForSelector: Timeout 60000ms exceeded.
[2021-07-27T04:52:05Z] =========================== logs ===========================
[2021-07-27T04:52:05Z] waiting for selector "text=Getting Started" to be visible
[2021-07-27T04:52:05Z] ============================================================
[2021-07-27T04:52:05Z]       at performLoginFlow (test_ui_api.ts:138:14)
[2021-07-27T04:52:05Z]       at Context.<anonymous> (test_ui_api.ts:222:5)
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2740#6d3a2843-f808-49c6-a2c9-d53797b60670/2057-2233

**Comment by sreis** [comment]
```
[2021-08-02T01:52:45Z]   1) [Chromium] › tests/wr25g_regression.spec.ts:30:7 › regressions we don't want to reappear issue #1000 - Cannot directly load 'cluster' based pages check cluster tenant listing 
[2021-08-02T01:52:45Z]
[2021-08-02T01:52:45Z]     page.waitForSelector: Timeout 30000ms exceeded.
[2021-08-02T01:52:45Z]     =========================== logs ===========================
[2021-08-02T01:52:45Z]     waiting for selector "[data-test=getting-started]" to be visible
[2021-08-02T01:52:45Z]     ============================================================
```

https://buildkite.com/opstrace/upgrade-tests/builds/1118#e0b5f239-015c-47bd-9737-2963e414207a

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2780#0d920a0e-1391-4275-99fe-add209d6f777/3080-3102

**Comment by nickbp** [comment]
Not seen since start of august, may have been fixed in the UI?
